"""Build the dependency license inventory for a fast-mlsirm release.

Offline and stdlib-only: every input is a file that was fetched beforehand, so
the output can be regenerated byte-for-byte from the recorded inputs. The
procedure that produces the inputs is documented in
``docs/security/license-evidence-0.11.5.md``.

For every dependency the inventory records the declared SPDX expression
(package metadata) separately from what the license files shipped inside the
actual artifact say, plus whether the package is inside the published
artifact scope. It never infers a license from a missing field: a package with
no declared license and no recognisable license text is reported as UNKNOWN.
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import re
import tomllib
import zipfile
from pathlib import Path

LICENSE_NAME = re.compile(r"^(licen[cs]e|copying|notice|authors|copyright|unlicense)", re.IGNORECASE)

# Ordered text fingerprints. A file may match several (e.g. a triple-license AUTHORS).
TEXT_FINGERPRINTS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("AGPL", ("GNU AFFERO GENERAL PUBLIC LICENSE",)),
    # Grant-form phrases only: MPL-2.0 names the GNU licenses as "Secondary
    # Licenses" without granting under them, which must not read as (L)GPL.
    ("LGPL", ("GNU LESSER GENERAL PUBLIC LICENSE Version", "under the terms of the GNU Lesser General Public",
              "under the terms of the GNU Library General Public")),
    ("GPL", ("GNU GENERAL PUBLIC LICENSE Version", "under the terms of the GNU General Public License")),
    ("MPL-2.0", ("Mozilla Public License Version 2.0", "Mozilla Public License, v. 2.0")),
    ("Apache-2.0 WITH LLVM-exception", ("LLVM Exceptions to the Apache 2.0 License",)),
    ("Apache-2.0", ("Apache License", "apache.org/licenses/LICENSE-2.0")),
    ("MIT", ("Permission is hereby granted, free of charge",)),
    ("BSD", ("Redistribution and use in source and binary forms",)),
    ("Zlib", ("This software is provided 'as-is'",)),
    ("ISC", ("Permission to use, copy, modify, and/or distribute this software for any",)),
    ("Unlicense", ("This is free and unencumbered software released into the public domain",)),
    ("Unicode-3.0", ("UNICODE LICENSE V3", "Unicode, Inc.")),
    ("PSF-2.0", ("PYTHON SOFTWARE FOUNDATION LICENSE",)),
)

COPYLEFT_PREFIXES = ("GPL-", "LGPL-", "AGPL-")
CLASSIFIER_SPDX = {
    "License :: OSI Approved :: MIT License": "MIT",
    "License :: OSI Approved :: Apache Software License": "Apache-2.0",
    "License :: OSI Approved :: BSD License": "BSD",
}
WEAK_COPYLEFT = ("MPL-2.0",)
# Election order for disjunctive (OR) expressions. MIT first because it is the
# project's own license and imposes only notice retention; Apache-2.0 next
# (adds NOTICE/patent terms); then the other permissive grants.
ELECTION_ORDER = ("MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "BSD-3-Clause", "BSD-2-Clause", "ISC", "Zlib", "Unlicense")
ELECTION_RATIONALE = (
    "Disjunctive license: MIT elected. It is the license fast-mlsirm itself ships under, "
    "is permissive, and carries the smallest obligation set (retain the copyright and "
    "permission notice); no copyleft alternative is exercised."
)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def detect(text: str) -> list[str]:
    text = " ".join(text.split())
    found = []
    for label, needles in TEXT_FINGERPRINTS:
        if any(n in text for n in needles):
            if label == "Apache-2.0" and "Apache-2.0 WITH LLVM-exception" in found:
                continue
            found.append(label)
    if "BSD" in found:
        found[found.index("BSD")] = "BSD-3-Clause" if "Neither the name" in text else "BSD-2-Clause"
    return found


def normalize_spdx(expr: str | None) -> str | None:
    if expr is None:
        return None
    # Legacy crates.io "A/B" and "A / B" syntax means "A OR B".
    return re.sub(r"\s*/\s*", " OR ", expr.strip())


def spdx_terms(expr: str) -> list[str]:
    return [t for t in re.split(r"\s+(?:OR|AND)\s+|[()]", expr) if t.strip()]


def elect(expr: str | None) -> tuple[str | None, str | None]:
    """Return (elected expression, rationale) for a normalized SPDX expression."""
    if expr is None:
        return None, None
    if " OR " not in expr:
        return expr, None
    # (A OR B) AND C  ->  elect inside the disjunction, keep the conjunct.
    m = re.fullmatch(r"\((.+)\)\s+AND\s+(.+)", expr)
    if m:
        inner, _ = elect(m.group(1))
        return f"{inner} AND {m.group(2)}", ELECTION_RATIONALE
    options = [o.strip() for o in expr.split(" OR ")]
    for pref in ELECTION_ORDER:
        if pref in options:
            rationale = ELECTION_RATIONALE if pref == "MIT" else (
                f"Disjunctive license without MIT: {pref} elected as the first permissive option "
                "in the policy order MIT > Apache-2.0 > BSD > ISC > Zlib > Unlicense."
            )
            return pref, rationale
    return None, "no permissive alternative in disjunction"


def classify(expr: str | None) -> str:
    if expr is None:
        return "UNKNOWN"
    terms = spdx_terms(expr)
    if any(t.startswith(COPYLEFT_PREFIXES) for t in terms):
        return "COPYLEFT"
    if any(t in WEAK_COPYLEFT for t in terms):
        return "WEAK-COPYLEFT"
    return "PERMISSIVE"


def license_files_in_dir(root: Path) -> list[dict]:
    out = []
    for path in sorted(p for p in root.iterdir() if p.is_file() and LICENSE_NAME.match(p.name)):
        data = path.read_bytes()
        out.append({"path": path.name, "sha256": sha256_bytes(data), "detected": detect(data.decode("utf-8", "replace"))})
    return out


def cargo_lock_checksums(lock: Path) -> dict[tuple[str, str], str]:
    data = tomllib.loads(lock.read_text())
    return {(p["name"], p["version"]): p.get("checksum") for p in data["package"]}


def read_target_sets(tree_dir: Path, kind: str) -> dict[str, set[str]]:
    sets = {}
    for f in sorted(tree_dir.glob(f"{kind}-*.txt")):
        target = f.stem[len(kind) + 1:]
        sets[target] = {line.strip().replace("@v", "@") for line in f.read_text().splitlines() if line.strip()}
    return sets


def rust_inventory(args) -> list[dict]:
    ws = json.loads(Path(args.cargo_metadata_workspace).read_text())
    binding = json.loads(Path(args.cargo_metadata_binding).read_text())
    checksums = {}
    for lock in args.cargo_lock:
        checksums.update(cargo_lock_checksums(Path(lock)))
    sbom = json.loads(Path(args.wheel_sbom).read_text())

    def walk(components):
        for c in components:
            yield c
            yield from walk(c.get("components", []))

    sbom_set = {(c["name"], c["version"]) for c in walk(sbom.get("components", []))}
    root = sbom.get("metadata", {}).get("component", {})
    sbom_set.add((root.get("name"), root.get("version")))
    linked = read_target_sets(Path(args.tree_dir), "linked")
    build = read_target_sets(Path(args.tree_dir), "build")
    binding_ids = {(p["name"], p["version"]) for p in binding["packages"]}
    registry = Path(args.cargo_registry_src)

    rows = {}
    for graph, meta in (("workspace", ws), ("binding", binding)):
        for p in meta["packages"]:
            key = (p["name"], p["version"])
            if key in rows:
                continue
            src_dir = Path(p["manifest_path"]).parent
            if p["source"] and p["source"].startswith("registry+"):
                src_dir = next(registry.glob(f"*/{p['name']}-{p['version']}"))
            files = license_files_in_dir(src_dir)
            declared = p["license"]
            norm = normalize_spdx(declared)
            elected, rationale = elect(norm)
            ident = f"{p['name']}@{p['version']}"
            file_labels = {label for f in files for label in f["detected"]}
            elected_terms = spdx_terms(elected) if elected else []
            rows[key] = {
                "ecosystem": "cargo",
                "name": p["name"],
                "version": p["version"],
                "source": p["source"] or "path (this repository)",
                "source_hash": {"algorithm": "sha256", "value": checksums.get(key), "origin": "Cargo.lock checksum"} if checksums.get(key) else None,
                "declared_license": declared,
                "declared_license_file": p["license_file"],
                "spdx_normalized": norm,
                "declared_license_class": classify(norm),
                "license_class": classify(elected),
                "elected_license": elected,
                "election_rationale": rationale,
                "license_files_in_artifact": files,
                "elected_text_present_in_artifact": all(
                    any(t == lbl or (t.startswith("BSD") and lbl.startswith("BSD")) for lbl in file_labels) for t in elected_terms
                ) if elected_terms else False,
                "value_origin": "package metadata (Cargo.toml license)" + (
                    "; license text verified in .crate" if files else "; NO license file in .crate"
                ),
                "in_workspace_lock": key in {(q["name"], q["version"]) for q in ws["packages"]},
                "in_binding_lock_graph": key in binding_ids,
                "in_wheel_sbom": key in sbom_set,
                "linked_into_core_for_targets": sorted(t for t, s in linked.items() if ident in s),
                "compiled_at_build_for_targets": sorted(t for t, s in build.items() if ident in s),
            }
    for row in rows.values():
        row["in_published_artifact_scope"] = row["in_binding_lock_graph"]
        row["scope_note"] = (
            "compiled into fast_mlsirm/_core for the listed targets" if row["linked_into_core_for_targets"]
            else "build-time only (proc-macro/build script) for the listed targets" if row["compiled_at_build_for_targets"]
            else "in binding lock graph and wheel SBOM but not compiled for any published target" if row["in_binding_lock_graph"]
            else "workspace lock only (dev/test path); not in any published artifact"
        )
    return sorted(rows.values(), key=lambda r: (r["name"], r["version"]))


def parse_notice_stanzas(text: str) -> list[dict]:
    stanzas = []
    for block in re.split(r"\n(?=Name: )", text):
        fields = dict(re.findall(r"^(Name|Files|Description|License): (.*)$", block, re.MULTILINE))
        if "Name" in fields and "Files" in fields:
            stanzas.append(fields)
    return stanzas


def python_artifact_evidence(path: Path) -> dict:
    data = path.read_bytes()
    ev = {"artifact": path.name, "sha256": sha256_bytes(data), "license_files": [], "metadata": {}, "vendored_native": []}
    if path.suffix != ".whl":
        return ev
    with zipfile.ZipFile(path) as zf:
        names = zf.namelist()
        meta = next(n for n in names if n.endswith(".dist-info/METADATA"))
        for line in zf.read(meta).decode("utf-8", "replace").splitlines():
            if not line:
                break
            k, _, v = line.partition(": ")
            if k in ("License", "License-Expression", "License-File") or (k == "Classifier" and v.startswith("License")):
                ev["metadata"].setdefault(k, []).append(v)
        notice_text = ""
        for n in names:
            base = n.rsplit("/", 1)[-1]
            if ".dist-info/" in n and LICENSE_NAME.match(base):
                raw = zf.read(n)
                text = raw.decode("utf-8", "replace")
                notice_text += "\n" + text
                ev["license_files"].append({"path": n, "sha256": sha256_bytes(raw), "detected": detect(text)})
        stanzas = parse_notice_stanzas(notice_text)
        for n in names:
            base = n.rsplit("/", 1)[-1]
            if re.search(r"\.(so(\.[0-9]+)*|dylib|dll|a)$", base) and (
                ".libs/" in n or ".dylibs/" in n or "/" not in n
            ):
                norm = n.replace("\\", "/")
                match = [s for s in stanzas if any(fnmatch.fnmatch(norm, g.strip().replace("\\", "/")) or fnmatch.fnmatch(norm, g.strip().replace("\\", "/").replace(".so", "*")) for g in s["Files"].split(","))]
                ev["vendored_native"].append({
                    "path": n,
                    "sha256": sha256_bytes(zf.read(n)),
                    "notice_stanza": [{"name": s["Name"], "license": s.get("License"), "description": s.get("Description")} for s in match],
                })
        ev["notice_stanzas_declared"] = [{"name": s["Name"], "files": s["Files"], "license": s.get("License")} for s in stanzas]
    return ev


def python_inventory(args) -> list[dict]:
    uv = tomllib.loads(Path(args.uv_lock).read_text())
    entries: dict[tuple[str, str], dict] = {}
    for p in uv["package"]:
        if p["source"].get("editable"):
            continue
        hashes = [p["sdist"]["hash"]] if "sdist" in p else []
        hashes += [w["hash"] for w in p.get("wheels", [])]
        entries.setdefault((p["name"], p["version"]), {"locks": {}})["locks"]["uv.lock"] = hashes
    for req in args.requirements:
        text = Path(req).read_text()
        for m in re.finditer(r"^([A-Za-z0-9_.-]+)==([^\s\\]+) \\\n((?:\s+--hash=sha256:[0-9a-f]{64}(?: \\)?\n)+)", text, re.MULTILINE):
            name = m.group(1).lower().replace("_", "-")
            hashes = ["sha256:" + h for h in re.findall(r"sha256:([0-9a-f]{64})", m.group(3))]
            entries.setdefault((name, m.group(2)), {"locks": {}})["locks"][Path(req).as_posix()] = hashes
    for extra in args.extra_python or []:
        name, version, why = extra.split("==", 1)[0], extra.split("==", 1)[1].split(":", 1)[0], extra.split(":", 1)[1]
        entries.setdefault((name, version), {"locks": {}})["locks"][why] = []

    scope = json.loads(Path(args.python_scope).read_text())
    meta_dir, art_dir = Path(args.pypi_meta_dir), Path(args.pypi_artifact_dir)
    rows = []
    for (name, version), e in sorted(entries.items()):
        meta = json.loads((meta_dir / f"{name}-{version}.json").read_text())["info"]
        declared = meta.get("license_expression") or None
        classifiers = [c for c in meta.get("classifiers") or [] if c.startswith("License ::")]
        paths = {a for stem in {name, name.replace("-", "_")} for a in art_dir.glob(f"{stem}-{version}[-.]*")}
        artifacts = [python_artifact_evidence(a) for a in sorted(paths)]
        text_labels = sorted({lbl for a in artifacts for f in a["license_files"] for lbl in f["detected"]})
        norm = normalize_spdx(declared)
        elected, rationale = elect(norm)
        if declared:
            determination = {"spdx": norm, "origin": "package metadata License-Expression",
                             "text_agrees": all(any(t == lbl or (t.startswith("BSD") and lbl.startswith("BSD")) for lbl in text_labels)
                                                for t in spdx_terms(elected or norm) if t not in ("0BSD", "CC0-1.0"))}
        else:
            cls_terms = {CLASSIFIER_SPDX.get(c) for c in classifiers} - {None}
            text_only = [lbl for lbl in text_labels if lbl not in ("GPL", "LGPL", "AGPL")]
            if cls_terms and len(text_only) == 1 and all(text_only[0].startswith(t) for t in cls_terms):
                determination = {"spdx": text_only[0], "origin": "trove classifier confirmed by the license file in the artifact (no License-Expression)", "text_agrees": True}
            elif not cls_terms and len(text_only) == 1:
                determination = {"spdx": text_only[0], "origin": "license file in the artifact ONLY - package metadata declares no license; recorded as an explicit evidence-based exception, not inferred from absence", "text_agrees": True}
            else:
                determination = {"spdx": None, "origin": "UNKNOWN - on hold", "text_agrees": False}
            elected = determination["spdx"]
        rows.append({
            "ecosystem": "pypi",
            "name": name,
            "version": version,
            "locks": {k: {"hash_count": len(v), "hashes": v} for k, v in e["locks"].items()},
            "declared_license_expression": declared,
            "declared_license_field": (meta.get("license") or None) and meta["license"][:200],
            "declared_classifiers": classifiers,
            "license_text_detected_in_artifact": text_labels,
            "license_class_from_metadata": classify(norm) if declared else ("UNKNOWN" if not classifiers else "CLASSIFIER-ONLY"),
            "license_determination": determination,
            "license_class": classify(determination["spdx"]),
            "elected_license": elected,
            "election_rationale": rationale,
            "artifacts_examined": artifacts,
            **scope.get(name, {"scope": "unclassified", "in_published_artifact_scope": False}),
        })
    return rows


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--cargo-metadata-workspace", required=True)
    ap.add_argument("--cargo-metadata-binding", required=True)
    ap.add_argument("--cargo-lock", nargs="+", required=True, help="workspace and binding-crate Cargo.lock files")
    ap.add_argument("--cargo-registry-src", required=True)
    ap.add_argument("--wheel-sbom", required=True)
    ap.add_argument("--tree-dir", required=True)
    ap.add_argument("--uv-lock", required=True)
    ap.add_argument("--requirements", nargs="+", required=True)
    ap.add_argument("--extra-python", nargs="*", help="name==version:reason for build tools outside the locks")
    ap.add_argument("--python-scope", required=True)
    ap.add_argument("--pypi-meta-dir", required=True)
    ap.add_argument("--pypi-artifact-dir", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args(argv)

    rust = rust_inventory(args)
    python = python_inventory(args)
    summary = {
        "cargo_workspace_lock_packages": sum(r["in_workspace_lock"] for r in rust),
        "cargo_binding_graph_packages": sum(r["in_binding_lock_graph"] for r in rust),
        "cargo_wheel_sbom_packages": sum(r["in_wheel_sbom"] for r in rust),
        "cargo_by_class": {c: sum(r["license_class"] == c for r in rust) for c in ("PERMISSIVE", "WEAK-COPYLEFT", "COPYLEFT", "UNKNOWN")},
        "cargo_by_declared_class": {c: sum(r["declared_license_class"] == c for r in rust) for c in ("PERMISSIVE", "WEAK-COPYLEFT", "COPYLEFT", "UNKNOWN")},
        "cargo_disjunctive_with_copyleft_alternative": [f"{r['name']}@{r['version']}" for r in rust if " OR " in (r["spdx_normalized"] or "") and any(t.startswith(COPYLEFT_PREFIXES) for t in spdx_terms(r["spdx_normalized"]))],
        "cargo_without_license_file_in_crate": [f"{r['name']}@{r['version']}" for r in rust if not r["license_files_in_artifact"] and r["source"] != "path (this repository)"],
        "cargo_elected_text_missing": [f"{r['name']}@{r['version']}" for r in rust if not r["elected_text_present_in_artifact"] and r["source"] != "path (this repository)"],
        "cargo_registry_without_checksum": [f"{r['name']}@{r['version']}" for r in rust if r["source_hash"] is None and r["source"] != "path (this repository)"],
        "pypi_packages": len(python),
        "pypi_metadata_unknown": [f"{r['name']}@{r['version']}" for r in python if r["license_class_from_metadata"] == "UNKNOWN"],
        "pypi_by_class": {c: [f"{r['name']}@{r['version']}" for r in python if r["license_class"] == c] for c in ("WEAK-COPYLEFT", "COPYLEFT", "UNKNOWN")},
        "pypi_vendored_native_by_notice_license": sorted({(s.get("license") or "NO NOTICE IN ARTIFACT") for r in python for a in r["artifacts_examined"] for v in a["vendored_native"] for s in (v["notice_stanza"] or [{}])}),
    }
    Path(args.out).write_text(json.dumps({"summary": summary, "cargo": rust, "pypi": python}, indent=1, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
