"""Build the dependency license inventory for a fast-mlsirm release.

Offline and stdlib-only: every input is a file that was fetched beforehand, so
the output can be regenerated byte-for-byte from the recorded inputs. The
procedure that produces the inputs is documented in
``docs/security/license-evidence-0.11.5.md``.

For every dependency the inventory records the declared SPDX expression
(package metadata) separately from what the license files shipped inside the
actual artifact say, plus whether the package is inside the published
artifact scope. The generator fails closed:

- an expression that does not parse under the supported SPDX grammar, or that
  names an identifier outside the reviewed list (``NOASSERTION``,
  ``LicenseRef-*``, empty), is UNKNOWN, and so is a disjunction with no fully
  permissive alternative;
- copyleft grant text found in an artifact is kept and puts the row on HOLD,
  never dropped in favour of a permissive reading;
- every package in every lock must produce exactly one row, every requirements
  pin must parse with its hashes, and every PyPI row needs a scope entry;
  otherwise the run reports completeness gaps and exits 1;
- license text is read only from artifact bytes whose measured sha256 equals
  the lock's expected hash; anything unbound is HOLD.
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import io
import json
import os
import posixpath
import re
import stat
import tarfile
import tomllib
import zipfile
from email import policy
from email.parser import BytesParser
from pathlib import Path

LICENSE_NAME = re.compile(r"^(licen[cs]e|copying|notice|authors|copyright|unlicense)", re.IGNORECASE)

# Ordered text fingerprints. A file may match several (e.g. a triple-license AUTHORS).
TEXT_FINGERPRINTS: tuple[tuple[str, tuple[str, ...]], ...] = (
    # Title/grant forms only: GPL-3.0 section 13 names the Affero license
    # without granting under it, which must not read as AGPL.
    ("AGPL", ("GNU AFFERO GENERAL PUBLIC LICENSE Version", "under the terms of the GNU Affero General Public")),
    # Grant-form phrases only: MPL-2.0 names the GNU licenses as "Secondary
    # Licenses" without granting under them, which must not read as (L)GPL.
    ("LGPL", ("GNU LESSER GENERAL PUBLIC LICENSE Version", "under the terms of the GNU Lesser General Public",
              "under the terms of the GNU Library General Public")),
    ("GPL", ("GNU GENERAL PUBLIC LICENSE Version", "under the terms of the GNU General Public License")),
    ("MPL-2.0", ("Mozilla Public License Version 2.0", "Mozilla Public License, v. 2.0")),
    ("Apache-2.0 WITH LLVM-exception", ("LLVM Exceptions to the Apache 2.0 License",)),
    ("Apache-2.0", ("Apache License", "apache.org/licenses/LICENSE-2.0")),
    ("MIT", ("Permission is hereby granted, free of charge",)),
    ("BSD", ("Redistribution and use in source and binary forms",)),
    ("Zlib", ("This software is provided 'as-is'",)),
    ("ISC", ("Permission to use, copy, modify, and/or distribute this software for any",)),
    ("Unlicense", ("This is free and unencumbered software released into the public domain",)),
    ("Unicode-3.0", ("UNICODE LICENSE V3", "Unicode, Inc.")),
    ("PSF-2.0", ("PYTHON SOFTWARE FOUNDATION LICENSE",)),
)
# A short name or one copied sentence is not license evidence.  These labels
# need independent grant and warranty/liability clauses from the standard text.
FULL_TEXT_MARKERS: dict[str, tuple[str, ...]] = {
    "MIT": (
        "permission is hereby granted, free of charge",
        "the software is provided \"as is\"",
        "in no event shall the authors or copyright holders be liable",
    ),
}
NEGATING_OR_CONDITIONAL_MARKERS = (
    "does not apply",
    "permission is not granted",
    "commercial distribution prohibited",
    "commercial redistribution is prohibited",
    "non-commercial use only",
)
MIT_CANONICAL_BODY = """Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."""
COPYLEFT_TEXT_LABELS = ("AGPL", "LGPL", "GPL")
WEAK_COPYLEFT_TEXT_LABELS = ("MPL-2.0",)

# Organization policy markers, mirrored from ContextualWisdomLab/.github
# scripts/ci/sbom_inventory_aggregator.py (COPYLEFT_LICENSE_MARKERS at
# bd94a89a). Any identifier containing one of them can never classify as
# PERMISSIVE, whatever the reviewed lists below say.
CENTRAL_POLICY_MARKERS = ("GPL", "AGPL", "LGPL", "MPL", "EPL", "CDDL", "CC-BY-SA", "SSPL", "OSL", "EUPL")

# Reviewed SPDX identifiers. Anything else - including NOASSERTION, NONE and
# LicenseRef-* - is UNKNOWN until a human reviews it and adds it here.
PERMISSIVE_IDS = frozenset({
    "MIT", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-3-Clause-Open-MPI", "ISC", "Zlib",
    "Unlicense", "Unicode-3.0", "0BSD", "CC0-1.0", "PSF-2.0",
})
WEAK_COPYLEFT_IDS = frozenset({"MPL-2.0"})
COPYLEFT_IDS = frozenset({
    "GPL-2.0-only", "GPL-2.0-or-later", "GPL-3.0-only", "GPL-3.0-or-later",
    "LGPL-2.0-only", "LGPL-2.0-or-later", "LGPL-2.1-only", "LGPL-2.1-or-later",
    "LGPL-3.0-only", "LGPL-3.0-or-later", "AGPL-3.0-only", "AGPL-3.0-or-later",
})
EXCEPTION_IDS = frozenset({"LLVM-exception", "GCC-exception-3.1"})
if any(m in i.upper() for i in PERMISSIVE_IDS for m in CENTRAL_POLICY_MARKERS):
    raise RuntimeError("a PERMISSIVE_IDS entry matches a central copyleft policy marker")

CLASSIFIER_SPDX = {
    "License :: OSI Approved :: MIT License": "MIT",
    "License :: OSI Approved :: Apache Software License": "Apache-2.0",
    "License :: OSI Approved :: BSD License": "BSD",
}
# Election order for disjunctive (OR) expressions. MIT first because it is the
# project's own license and imposes only notice retention; Apache-2.0 next
# (adds NOTICE/patent terms); then the other permissive grants.
ELECTION_ORDER = ("MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "BSD-3-Clause", "BSD-2-Clause", "ISC", "Zlib", "Unlicense")
ELECTION_RATIONALE = (
    "Disjunctive license: MIT elected. It is the license fast-mlsirm itself ships under, "
    "is permissive, and carries the smallest obligation set (retain the copyright and "
    "permission notice); no copyleft alternative is exercised."
)
ELECTION_FAILED = "election failed: no fully permissive alternative in the disjunction; held as UNKNOWN"
CLASS_RANK = {"PERMISSIVE": 0, "WEAK-COPYLEFT": 1, "COPYLEFT": 2, "UNKNOWN": 3}
CLASSES = ("PERMISSIVE", "WEAK-COPYLEFT", "COPYLEFT", "HOLD", "UNKNOWN")
# Declared ids without a text fingerprint; their absence from artifact text is
# not counted as a disagreement (they are public-domain style dedications).
UNFINGERPRINTED_IDS = frozenset({"0BSD", "CC0-1.0", "BSD-3-Clause-Open-MPI"})


class SpdxError(ValueError):
    """Raised for an expression outside the supported SPDX grammar or id list."""


class EvidenceReadError(OSError):
    """Raised when artifact bytes cannot be bound to one stable source path."""


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_stable_bytes(path: Path) -> bytes:
    """Read a regular file once and reject path or descriptor mutation."""
    before = path.lstat()
    if not stat.S_ISREG(before.st_mode):
        raise EvidenceReadError(f"artifact path is not a regular non-symlink file: {path}")
    with path.open("rb") as handle:
        opened = os.fstat(handle.fileno())
        if (before.st_dev, before.st_ino) != (opened.st_dev, opened.st_ino):
            raise EvidenceReadError(f"artifact path changed before read: {path}")
        data = handle.read()
        after_fd = os.fstat(handle.fileno())
    after_path = path.lstat()
    def identity(file_stat):
        return (file_stat.st_dev, file_stat.st_ino, file_stat.st_size, file_stat.st_mtime_ns)
    if identity(before) != identity(opened) or identity(opened) != identity(after_fd):
        raise EvidenceReadError(f"artifact changed while being read: {path}")
    if identity(after_fd) != identity(after_path):
        raise EvidenceReadError(f"artifact path was replaced after read: {path}")
    if len(data) != after_fd.st_size:
        raise EvidenceReadError(f"artifact read was incomplete: {path}")
    return data


def detect(text: str) -> list[str]:
    text = " ".join(text.split()).casefold()
    found = []
    for label, needles in TEXT_FINGERPRINTS:
        folded_needles = tuple(n.casefold() for n in needles)
        markers = FULL_TEXT_MARKERS.get(label)
        valid_standard_text = markers is None or all(marker in text for marker in markers)
        # Negating/conditional language may void a permissive grant, but it
        # never removes copyleft evidence: GPL-3.0 itself says a clause "does
        # not apply", and dropping the label would hide the copyleft component.
        copyleft = label in COPYLEFT_TEXT_LABELS + WEAK_COPYLEFT_TEXT_LABELS
        unqualified = copyleft or not any(marker in text for marker in NEGATING_OR_CONDITIONAL_MARKERS)
        if any(n in text for n in folded_needles) and valid_standard_text and unqualified:
            if label == "Apache-2.0" and "Apache-2.0 WITH LLVM-exception" in found:
                continue
            found.append(label)
    if "BSD" in found:
        found[found.index("BSD")] = "BSD-3-Clause" if "Neither the name" in text else "BSD-2-Clause"
    return found


# Reviewed pointer notices (normalized sha256 -> licenses they point to), from s1
# text-review-20260926. A pointer is not a license text: with --reviewed-pointer-notices it
# is satisfied only when every named license has a verified full text in the same
# hash-bound .crate and the names equal the declared SPDX expression's terms.
POINTER_NOTICES = {
    "9fba058782d4dbf4eda66df225dfc11e8afdc5618f6bc36c2dafbb087cda3971": ("Apache-2.0", "MIT"),  # unicode-width COPYRIGHT 23860c2a
    "7e7a2c785f3db52a3daf64a62b76b09b940355e4fe1b7f7092f473b7663416b1": ("Unlicense", "MIT"),  # memchr-family COPYING 01c266bc
    "db11fec9946737df39ca3898d9cd8c10ec6f6c3a884a6802b0ad0b81b4e8f23a": ("MIT", "Apache-2.0"),  # typenum LICENSE db11fec9
}


def verified_standard_text(text: str) -> list[str]:
    """Return licenses whose complete canonical grant has no extra conditions."""
    # Reviewed entire archive members, with source hashes and exact bytes in
    # tests/fixtures/license_inventory_reviewed_texts.json. This folds ASCII
    # layout whitespace only; headers, case, extra terms and component notices
    # are never stripped. It grants no exemption from all-candidate validation.
    reviewed = {
        "0ffddef9e48f8a09aed5caf2d44f7ba1c1be2d9b8e0a6f693b1635b2d5566645": "Apache-2.0",
        "59d8f0ba87ad9a2f1a431123c8d16646e5b89ba53653e818f16d136d77263c99": "Apache-2.0",
        "3a31f72fe7c9baf376c3da1d7d0154366be8ef0bab0a3f7531db4c2abf1ad062": "Zlib",
        "444399c3da8f18f32878c6f8b7348110f33985558ca7abe98d4c8ed26f013109": "Zlib",
        # 66 copyright-header/appendix-only variants, reviewed in s1 text-review-20260926.
        "25c95a7b50ce321f537754cab2f5b1de56413ccdcbc492671d569851d62ce276": "BSD-2-Clause",  # zerocopy-0.8.57/LICENSE-BSD (same bytes in zerocopy-derive): coordinator verdict (user-delegated, 2026-09-26), not legal review; SPDX BSD-2-Clause template var spans
        "bbb0c7a72cdfa383f0a62db4e19033942ed3f909eac4e865334e22e1c0a17c92": "MIT",  # bytemuck-1.25.2/LICENSE-MIT (same bytes in bytemuck_derive): coordinator verdict (user-delegated, 2026-09-26), not legal review; SPDX MIT template optional span
        "f42a00ac54d036890559853a40f95622ab3e63d52173f5714284134b2af11e3c": "Apache-2.0 WITH LLVM-exception",  # target-lexicon-0.13.5/LICENSE: coordinator verdict (user-delegated, 2026-09-26), not legal review
        "a66ace7bb1d24a3290b823ae25fcd5f95fc5a3dd5af95c45dd77dc37ee593bcd": "BSD-2-Clause",  # numpy-0.29.0/LICENSE: coordinator verdict (user-delegated, 2026-09-26), not legal review
        "272a160fd2085e79bc5aa395e9fbbc267d0830e5b66757677a87ce93f4401727": "MIT",  # ndarray-0.17.2/LICENSE-MIT: coordinator verdict (user-delegated, 2026-09-26), not legal review
        "f7539d10705fa2869dabf2d5ecaf51ed026d337e26865967e8d431a30b71833a": "MIT",  # matrixmultiply-0.3.11/LICENSE-MIT: coordinator verdict (user-delegated, 2026-09-26), not legal review
        "02b0b107669e54b03f028ee6b07c3e35be05a7fe60495a5933a55324885abf0f": "Apache-2.0",  # ash-0.38.0+1.3.281/LICENSE-APACHE: coordinator verdict (user-delegated, 2026-09-26), not legal review
        "121aea2578cd98e64faa0ca32acfd4f83551b1ecd293730a9541a4f5a37bf85c": "ISC",  # libloading-0.8.9/LICENSE: ISC with copyright header only (no-template-reclass STANDARD_COPYRIGHT_ONLY)
        "2069c208cba553e43cd0b730df8a0c10bf1b1101b96f661e2f1307c73b9722e3": "Unlicense",  # UNLICENSE 7e12e5df, byte-identical to SPDX v3.29.0 (memchr/termcolor/winapi-util)
        "21b7ffe46249356209d64748a5179bf37a704880d8af02c77bd65d20800503f0": "Unicode-3.0",  # unicode-ident LICENSE-UNICODE f7db8105, byte-identical to SPDX v3.29.0
        "f5ac0308cf2b3f96a0f49a8c0c9e4a2a02c483afc72a646af8de1f356983de06": "MIT",  # fast-mlsirm LICENSE (wheel dist-info/licenses/LICENSE; own crates bind via --own-crate-wheel)
        "1834e4a70e47109cc013a1fa4f34cb0e5b32753be1247a116ec1f1357b87115f": "MIT",  # upstream aclysma/profiling@8271551172eb LICENSE-MIT (profiling-1.0.18 .crate has none)
        "8b496867ab4da1182d754c6dbd948db3e0f08598d6c685155f4481f9afc98d86": "Apache-2.0",  # deranged-0.5.8/LICENSE-Apache
        "52b86d7cac180bbb9dca8ebe3c9e66ac7cc8e704735ef151a514b6beff85600e": "Apache-2.0",  # futures-core-0.3.34/LICENSE-APACHE
        "6cd11fd5f811c88bac0b0e9d03c79ee8f72ef808a31fe7b31109f5d1d6a46d88": "Apache-2.0",  # gpu-allocator-0.28.0/LICENSE-APACHE
        "ad90af82d790fc53e9b247434d2ae5382df1941b6a380c1c16d43bbb7cfce7f1": "Apache-2.0",  # powerfmt-0.2.0/LICENSE-Apache
        "c8f231e806990fbae26a329908ad335584ee2448af43f743e40353675841e373": "Apache-2.0",  # pyo3-0.29.2/LICENSE-APACHE
        "3c2971a948fcb684bfb692b3dc13aee15e9a8bcafc7444e160ba33d93c0c392e": "Apache-2.0",  # typenum-1.20.1/LICENSE-APACHE
        "145806f1918280735937d8be844ea1da8d912251b1a234ce3406e9338e8cf9e0": "Apache-2.0",  # windows-0.62.2/license-apache-2.0
        "534e8240bf07aab05c15a12e0599b8daa248f6bbcc84c82894ace32ddfc2858e": "Apache-2.0",  # zerocopy-0.8.57/LICENSE-APACHE
        "2bcdc0b2d0f39f744a3295a725725ffd3f7477a8a76c76ac671e26e1b5af4bf5": "MIT",  # android_system_properties-0.1.6/LICENSE-MIT
        "625eb062458d42d2eb8c69913a4ad35e01753490350d8de9cddddb6cde8d7e62": "MIT",  # arrayvec-0.7.8/LICENSE-MIT
        "4bd94c8c3a98fcffa62cb91de62dd4a75996040e775e973ef428b28be8a5420a": "MIT",  # ash-0.38.0+1.3.281/LICENSE-MIT
        "9cee45046fedfd0bde5b25dc3bba824c92b6e4e7bfe89d3f58ec5e664cba579a": "MIT",  # autocfg-1.5.1/LICENSE-MIT
        "71bc93e83568101862883f070290bd873f1d9a720727e99ab96f3ede6b2dc91d": "MIT",  # bit-set-0.10.0/LICENSE-MIT
        "5376f07638d3fd777c45e872500a3a11b785b79c2fff2d67bc0361d0d87f5a80": "MIT",  # bit-vec-0.9.1/LICENSE-MIT
        "c25311c4c60e634637fe8148151c9fc62b749205a8c83ad0bd02baeaf71c3209": "MIT",  # bitflags-2.13.2/LICENSE-MIT
        "5df37ed67c513072d5fe279e179bd1d8a49dd20fd61b1f1c7f1f07379fc17591": "MIT",  # block-buffer-0.10.4/LICENSE-MIT
        "d36be0aa3bf9c24679d232041f324b417567b6d61db00e9c8267de3c67432ec7": "MIT",  # bumpalo-3.20.3/LICENSE-MIT
        "6bf6d79db7f6f622c369dc3a36429c9bfd0351ddfdcadd046e0bcf575f3d2614": "MIT",  # cfg-if-1.0.5/LICENSE-MIT
        "ceb65ec3e793eb098d672594a12fde934db8508b7de6238d7f23a8567625eaac": "MIT",  # cfg_aliases-0.2.2/LICENSE
        "516c5a27fb50acd9d2fba2432afd0a729065a19d020989ffdd66b327a918de84": "MIT",  # cpufeatures-0.2.17/LICENSE-MIT
        "12af027810fb17f70ee3df906c5793979ce4564607114e46a301b7a54a72a9f4": "MIT",  # crunchy-0.2.4/LICENSE
        "6e40c7393f7c3a7f8d7e950067d6c6fddeace4d29cea85bb10c3e824fb2a8c5d": "MIT",  # crypto-common-0.1.7/LICENSE-MIT
        "b99d57e1913bd860d1145d49a14715bd65e077dd15c4efb70c0ec29d05508cce": "MIT",  # deranged-0.5.8/LICENSE-MIT
        "c84ea1490b494b7687fcce5d4af0cd51a6b3ca99d8d169941882391934f277c9": "MIT",  # digest-0.10.7/LICENSE-MIT
        "164b92de4d5de31acc77023494891c3ea72283296eff6e69f0c2fb35e35a7d2e": "MIT",  # dlib-0.5.3/LICENSE.txt
        "e723f0aaad2740b74a5042e19c02f312c567b0b26ccbc5eacc7b6fb4023d13ca": "MIT",  # document-features-0.2.12/LICENSE-MIT
        "3c7d8bcc6f358ab370c9153e0ca3a77ad0589daa316d23f17f58e1e89ac8b2a6": "MIT",  # equivalent-1.0.2/LICENSE-MIT
        "be1847dc49ef1ef89acc076d21a0499c7dd8131db9b5322a2a0333f4a16c1c64": "MIT",  # futures-core-0.3.34/LICENSE-MIT
        "2f1ac698186584433271fd1c5ea35ec0da31cacfa13d75ae278969ddeed12f78": "MIT",  # generic-array-0.14.7/LICENSE
        "b0696be97bff992e45b18754fc0ae85b18c4f0142d6c317c05deec6692d9b8ff": "MIT",  # gpu-allocator-0.28.0/LICENSE-MIT
        "7e1f7cb813ec8afdb27afbb7162b48874c3f6c5b55f2affcbc5f4c132d8861c4": "MIT",  # hashbrown-0.16.1/LICENSE-MIT
        "d1442c3bc874608ba5ed80a044a1f7aa115565c30214e2e4ef8563acf0309d39": "MIT",  # heck-0.5.0/LICENSE-MIT
        "72c966073ea33b7014ce2d23cc0bba6d184017cca50703ee4808c02af4624f46": "MIT",  # indexmap-2.14.2/LICENSE-MIT
        "f416d58a13d825df923c71e898567758b3f595c706a9b5da23abfbd94737dcc7": "MIT",  # jni-sys-0.3.1/LICENSE-MIT
        "6ebd8d40ce1b5685fdb9b3689d815d802022732e8504c1c513bc9d309575758c": "MIT",  # libc-0.2.189/LICENSE-MIT
        "1816a1f362c89aa6d4b41fd44c14a8f6dc2bc788ac03877e48cb76d3e1b15784": "MIT",  # litrs-1.0.0/LICENSE-MIT
        "2810737fc58c4fa01c84559aa0b48db577fb0d7e0f871a2459b2551976b9a446": "MIT",  # lock_api-0.4.14/LICENSE-MIT
        "952115fb93510335fd97e1e479516553fa0c4da1b49acddf9cd5d18392a3e1cf": "MIT",  # memchr-2.8.3/LICENSE-MIT
        "1876d90fad39cffe11fb7db9bce71ac60795643b00c71d8f88661558b4426586": "MIT",  # naga-30.0.1/LICENSE.MIT
        "5e7a18f489b9b089f6946ccfc5190ab073199054b7ed58fe65fe8650ebc3b9ea": "MIT",  # num-conv-0.2.2/LICENSE-MIT
        "e0d942dfe6038ddff3ec62d78064580c23119971b55a8854bba4b612757fffc0": "MIT",  # ordered-float-5.5.0/LICENSE-MIT
        "31639cdc357735ba41f11654af24649688897149e857718df92dbd4fb746fad4": "MIT",  # pollster-1.0.1/LICENSE-MIT
        "93bb3b571eb0df578c76b844cefc929ed8573413c763cafcd36c63408251e8ba": "MIT",  # powerfmt-0.2.0/LICENSE-MIT
        "8195dbce873a94a4c279100e99a9cbc0e90472044b06669aa4fe183801d214d1": "MIT",  # presser-0.3.1/LICENSE-MIT
        "500e97bb9db8f7ed04ac270750cad498669224f165ed554531894f1cfb963434": "MIT",  # pyo3-0.29.2/LICENSE-MIT
        "3ad193b1e1de2efd71d467fda89d0d906e508d2e9980464444f48c95a7d1cb61": "MIT",  # range-alloc-0.1.5/LICENSE.MIT
        "279ce0b86b8d12d7f1ee41a38e62214daaca48e151ce43e111eae0869ad48009": "MIT",  # raw-window-handle-0.6.2/LICENSE-MIT.md
        "f6b06eca855bbfd854ba2f545c684dade8593e27cc95877587fa21a8932100bb": "MIT",  # rawpointer-0.2.1/LICENSE-MIT
        "d26280807255cbdc7b6df0416ed435765790c9775574466d6c3c5b7fb496e2d6": "MIT",  # redox_syscall-0.5.18/LICENSE
        "cbb061a9e2168fff25c66311fea587c24dd6cbd8f2849ac87d60beabff88b30f": "MIT",  # renderdoc-sys-1.1.0/LICENSE-MIT
        "4e212f4528c9ceca0d7a6dbcc0833cd19a84fb113fff70144bd4c172324bdf5b": "MIT",  # scopeguard-1.2.0/LICENSE-MIT
        "5327d3e76b455dce2f1110d7717bb6a8e4efd8673a3ba5282338f5a60dd90153": "MIT",  # sha2-0.10.9/LICENSE-MIT
        "075c3581049481a7dccdf4c1e643fdb764c29b7e8ffd832ab423f8f1f420c1f3": "MIT",  # slab-0.4.12/LICENSE
        "2736d79caea349a8296cf4b17009aee66cb09683beee42232e27a86252aab766": "MIT",  # smallvec-1.16.1/LICENSE-MIT
        "8ec9de4a8300964b9806862de209aea912c02413c5303f040ef1d25734679296": "MIT",  # static_assertions-1.1.0/LICENSE-MIT
        "a8f60d2a6461811c1f38b179a651379ea28ec38b6158314a957e372a3b93f91a": "MIT",  # time-0.3.55/LICENSE-MIT
        "574f47f354afb5af89b1ea4de48bbb1d4e9064c334fe590ee35895ab39b3d3da": "MIT",  # typenum-1.20.1/LICENSE-MIT
        "de1bcb73d8f5f58556f70ed0681b98700bdbfd33a6bf554d245c3caddafb3463": "MIT",  # uuid-1.26.1/LICENSE-MIT
        "8963f9b21e899360aa4add8b67cc1c9d6319a073011db97829381fc267d515a3": "MIT",  # version_check-0.9.5/LICENSE-MIT
        "a38abdc9d438e7c88550e68100ad09f16ebe90d0f4529c47ea5764725a6ed15f": "MIT",  # wayland-sys-0.31.11/LICENSE.txt
        "dd83c703f6d90d1dfff17f4d18c26c26da327ae1398a27398913bf3333587df4": "MIT",  # winapi-util-0.1.11/LICENSE-MIT
        "502292ebd8d883e73d2b433a3bb4531fe5c7d917959377f1cb6e75bf4cbd89ad": "MIT",  # xml-rs-0.8.29/LICENSE
        "bc6715c4aa80f44647f3afe233cbc0409cad091d77fb94925a257770714f42c3": "MIT",  # zerocopy-0.8.57/LICENSE-MIT
        "7ab00508d3cf6798339908ff677796063e2d9260adeb67d22e0cd66b864a2bbb": "Zlib",  # bytemuck-1.25.2/LICENSE-ZLIB
        "6533009df0e5dd56f0a2d720b4396123453b4e6d212224b755c0f9b3573754bd": "Zlib",  # raw-window-handle-0.6.2/LICENSE-ZLIB.md
        "e9e88becb88223fa0cdb694393e9dc1aa6cfc803d3805e60a6d66bc990647011": "Zlib",  # slotmap-1.1.1/LICENSE
    }
    normalized = re.sub(r"[ \t\r\n]+", " ", text).strip(" \t\r\n")
    recognized = reviewed.get(sha256_bytes(normalized.encode("utf-8")))
    if recognized:
        return [recognized]
    lines = text.replace("\r\n", "\n").replace("\r", "\n").strip().splitlines()
    while lines and not lines[0].strip():
        lines.pop(0)
    if lines and lines[0].strip().casefold() == "mit license":
        lines.pop(0)
    while lines and not lines[0].strip():
        lines.pop(0)
    # A copyright-looking line is not syntax: arbitrary conditions can be
    # appended using the same ASCII words as a person's or organization's
    # name.  Without exact pre-reviewed bytes, do not discard any header.
    candidate = " ".join("\n".join(lines).split()).casefold()
    canonical = " ".join(MIT_CANONICAL_BODY.split()).casefold()
    return ["MIT"] if candidate == canonical else []


def normalize_spdx(expr: str | None) -> str | None:
    if expr is None:
        return None
    # Legacy crates.io "A/B" and "A / B" syntax means "A OR B".
    return re.sub(r"\s*/\s*", " OR ", expr.strip())


def id_class(license_id: str, exception: str | None = None) -> str:
    """Classify one identifier; unreviewed identifiers are UNKNOWN."""
    if exception is not None and exception not in EXCEPTION_IDS:
        return "UNKNOWN"
    if license_id in COPYLEFT_IDS:
        return "COPYLEFT"  # a WITH exception does not auto-approve copyleft
    if license_id in WEAK_COPYLEFT_IDS:
        return "WEAK-COPYLEFT"
    if license_id in PERMISSIVE_IDS:
        return "PERMISSIVE"
    if any(m in license_id.upper() for m in CENTRAL_POLICY_MARKERS):
        return "COPYLEFT"
    return "UNKNOWN"


def parse_spdx(expr: str | None):
    """Parse ``expr`` into ("lic", id, exc) / ("and", [...]) / ("or", [...]).

    Grammar: or := and ("OR" and)*; and := atom ("AND" atom)*;
    atom := "(" or ")" | ID ["WITH" EXCEPTION]. Raises SpdxError.
    """
    if expr is None or not expr.strip():
        raise SpdxError("empty license expression")
    tokens = re.findall(r"\(|\)|[^\s()]+", expr)
    pos = 0

    def peek():
        return tokens[pos] if pos < len(tokens) else None

    def take():
        nonlocal pos
        tok = peek()
        if tok is None:
            raise SpdxError(f"unexpected end of expression: {expr!r}")
        pos += 1
        return tok

    def parse_or():
        items = [parse_and()]
        while peek() == "OR":
            take()
            items.append(parse_and())
        return items[0] if len(items) == 1 else ("or", items)

    def parse_and():
        items = [parse_atom()]
        while peek() == "AND":
            take()
            items.append(parse_atom())
        return items[0] if len(items) == 1 else ("and", items)

    def parse_atom():
        tok = take()
        if tok == "(":
            node = parse_or()
            if take() != ")":
                raise SpdxError(f"unbalanced parenthesis in {expr!r}")
            return node
        if tok in (")", "AND", "OR", "WITH"):
            raise SpdxError(f"unexpected {tok!r} in {expr!r}")
        exc = None
        if peek() == "WITH":
            take()
            exc = take()
        if id_class(tok, exc) == "UNKNOWN":
            raise SpdxError(f"unreviewed license identifier {tok!r}" + (f" WITH {exc!r}" if exc else "") + f" in {expr!r}")
        return ("lic", tok, exc)

    node = parse_or()
    if pos != len(tokens):
        raise SpdxError(f"trailing tokens in {expr!r}")
    return node


def render(node) -> str:
    kind = node[0]
    if kind == "lic":
        return node[1] + (f" WITH {node[2]}" if node[2] else "")
    parts = [f"({render(c)})" if c[0] != "lic" and c[0] != kind else render(c) for c in node[1]]
    return f" {kind.upper()} ".join(parts)


def node_class(node) -> str:
    """Worst class over every term (fail-closed view of a declared expression)."""
    if node[0] == "lic":
        return id_class(node[1], node[2])
    return max((node_class(c) for c in node[1]), key=CLASS_RANK.__getitem__)


def node_ids(node) -> list[str]:
    """License terms of an expression, each rendered with its WITH exception."""
    if node[0] == "lic":
        return [render(node)]
    return [i for c in node[1] for i in node_ids(c)]


def _elect_node(node):
    if node[0] == "lic":
        return node
    if node[0] == "and":
        parts = [_elect_node(c) for c in node[1]]
        return None if any(p is None for p in parts) else ("and", parts)
    options = [e for e in (_elect_node(c) for c in node[1]) if e is not None and node_class(e) == "PERMISSIVE"]
    if not options:
        return None

    def rank(option):
        text = render(option)
        return ELECTION_ORDER.index(text) if text in ELECTION_ORDER else len(ELECTION_ORDER)

    return min(options, key=rank)


def _has_or(node) -> bool:
    return node[0] == "or" or (node[0] == "and" and any(_has_or(c) for c in node[1]))


def elect(expr: str | None) -> tuple[str | None, str | None]:
    """Return (elected expression, rationale); (None, reason) when it cannot be elected."""
    if expr is None:
        return None, None
    try:
        node = parse_spdx(expr)
    except SpdxError as err:
        return None, f"unparseable or unreviewed expression: {err}"
    chosen = _elect_node(node)
    if chosen is None:
        return None, ELECTION_FAILED
    if not _has_or(node):
        return render(chosen), None
    ids = node_ids(chosen)
    if "MIT" in ids:
        return render(chosen), ELECTION_RATIONALE
    return render(chosen), (
        f"Disjunctive license without MIT: {render(chosen)} elected as the first permissive option "
        "in the policy order MIT > Apache-2.0 > BSD > ISC > Zlib > Unlicense."
    )


def classify(expr: str | None) -> str:
    """Fail-closed class of an expression; anything unparseable is UNKNOWN."""
    try:
        return node_class(parse_spdx(expr))
    except SpdxError:
        return "UNKNOWN"


def spdx_terms(expr: str | None) -> list[str]:
    try:
        return node_ids(parse_spdx(expr))
    except SpdxError:
        return []


def _label_covers(term: str, label: str) -> bool:
    return term == label or (term.startswith("BSD") and label.startswith("BSD"))


def _text_covered_by(label: str, declared_ids: list[str]) -> bool:
    """Is a copyleft text label (GPL/LGPL/AGPL) covered by a declared identifier?"""
    return any(i.startswith(label + "-") for i in declared_ids)


def normalized_archive_path(path: str) -> str | None:
    """Return one canonical relative POSIX member path, or reject it."""
    if not path or "\\" in path or "\x00" in path or path.startswith("/"):
        return None
    normalized = posixpath.normpath(path)
    if normalized in ("", ".", "..") or normalized.startswith("../"):
        return None
    if normalized != path.rstrip("/"):
        return None
    return normalized


def read_crate_license_files(
    data: bytes, artifact_sha256: str, declared_license_file: str | None, pointer_rule: bool = False
) -> tuple[list[dict], list[str]]:
    """Read every license-named member and the metadata-declared license file."""
    out = []
    errors = []
    declared = normalized_archive_path(declared_license_file or "") or ""
    if declared_license_file and not declared:
        errors.append("Cargo metadata license_file is not a safe canonical relative path")
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tf:
        seen = set()
        for member in sorted(tf.getmembers(), key=lambda m: m.name):
            normalized = normalized_archive_path(member.name)
            if normalized is None:
                errors.append(f"unsafe or non-canonical archive member path: {member.name!r}")
                continue
            if normalized in seen:
                errors.append(f"duplicate archive member path: {normalized!r}")
                continue
            seen.add(normalized)
            parts = normalized.split("/")
            relative = "/".join(parts[1:])
            base = parts[-1]
            if member.isfile() and (LICENSE_NAME.match(base) or (declared and relative == declared)):
                raw = tf.extractfile(member).read()
                out.append({"path": relative, "sha256": sha256_bytes(raw),
                            "artifact_sha256": artifact_sha256,
                            "declared_license_file": bool(declared and relative == declared),
                            "detected": detect(raw.decode("utf-8", "replace")),
                            "verified_standard_text": verified_standard_text(
                                raw.decode("utf-8", "replace")
                            )})
                if pointer_rule:
                    text = raw.decode("utf-8", "replace")
                    names = POINTER_NOTICES.get(sha256_bytes(re.sub(r"[ \t\r\n]+", " ", text).strip(" \t\r\n").encode()))
                    if names:
                        out[-1]["pointer_notice"] = {"names": list(names)}
    return out, errors


def bind_upstream_license_files(archive: bytes, name: str, version: str, entry: dict, base: Path) -> tuple[list[dict], list[str]]:
    """Use upstream license files for a hash-bound .crate that ships none.

    Binds only when the in-crate .cargo_vcs_info.json names the recorded commit
    and path and every local file matches its recorded sha256; otherwise no
    file is returned and the row stays HOLD.
    """
    errors = []
    try:
        with tarfile.open(fileobj=io.BytesIO(archive), mode="r:gz") as tf:
            vcs = json.loads(tf.extractfile(f"{name}-{version}/.cargo_vcs_info.json").read())
    except (KeyError, AttributeError, ValueError, tarfile.TarError):
        return [], ["upstream license evidence: the .crate has no readable .cargo_vcs_info.json"]
    sha1 = vcs.get("git", {}).get("sha1")
    if sha1 != entry.get("vcs_sha1"):
        errors.append(f"upstream license evidence: .cargo_vcs_info.json sha1 {sha1!r} != recorded {entry.get('vcs_sha1')!r}")
    if vcs.get("path_in_vcs", "") != entry.get("path_in_vcs", ""):
        errors.append("upstream license evidence: .cargo_vcs_info.json path_in_vcs differs from the record")
    files = []
    for f in entry.get("files") or []:
        try:
            raw = (base / f["local_path"]).read_bytes()
        except OSError as exc:
            errors.append(f"upstream license evidence: {f.get('path')!r} unreadable: {exc}")
            continue
        if sha256_bytes(raw) != f["sha256"]:
            errors.append(f"upstream license evidence: {f['path']!r} sha256 does not match the record")
            continue
        text = raw.decode("utf-8", "replace")
        files.append({"path": f["path"], "sha256": f["sha256"], "artifact_sha256": None,
                      "declared_license_file": False, "detected": detect(text),
                      "verified_standard_text": verified_standard_text(text),
                      "origin": "upstream-vcs", "repository": entry.get("repository"),
                      "vcs_sha1": entry.get("vcs_sha1"), "url": f.get("url")})
    if not entry.get("files"):
        errors.append("upstream license evidence lists no files")
    return ([], errors) if errors else (files, [])


def own_crate_wheel_license_files(wheel: Path, expected_sha256: str) -> tuple[str | None, list[dict], list[str]]:
    """Return (METADATA Version, license files, errors) from the published wheel for this repository's crates.

    Files are returned only when the wheel sha256 matches and every declared
    METADATA License-File member exists; otherwise the caller keeps HOLD.
    """
    try:
        data = wheel.read_bytes()
    except OSError as exc:
        return None, [], [f"own-crate wheel unreadable: {exc}"]
    digest = sha256_bytes(data)
    if digest != expected_sha256:
        return None, [], [f"own-crate wheel sha256 {digest} != expected {expected_sha256}"]
    errors, files = [], []
    with zipfile.ZipFile(io.BytesIO(data)) as zf:
        metas = [n for n in zf.namelist() if n.count("/") == 1 and n.endswith(".dist-info/METADATA")]
        if len(metas) != 1:
            return None, [], ["own-crate wheel has no single top-level .dist-info/METADATA"]
        message = BytesParser(policy=policy.compat32).parsebytes(zf.read(metas[0]))
        versions = message.get_all("Version", [])
        declared = [str(v).strip() for v in message.get_all("License-File", [])]
        if len(versions) != 1:
            errors.append("own-crate wheel METADATA has no single Version")
        if not declared:
            errors.append("own-crate wheel METADATA declares no License-File")
        dist_info = metas[0].rsplit("/", 1)[0]
        for value in declared:
            rel = normalized_archive_path(value)
            member = f"{dist_info}/licenses/{rel}" if rel else None
            if member is None or member not in zf.namelist():
                errors.append(f"own-crate wheel License-File member is absent: {value!r}")
                continue
            raw = zf.read(member)
            text = raw.decode("utf-8", "replace")
            files.append({"path": member, "sha256": sha256_bytes(raw), "artifact_sha256": digest,
                          "declared_license_file": True, "detected": detect(text),
                          "verified_standard_text": verified_standard_text(text), "origin": "published-wheel"})
    version = str(versions[0]).strip() if len(versions) == 1 else None
    return version, ([] if errors else files), errors


def license_files_in_dir(root: Path) -> list[dict]:
    out = []
    for path in sorted(p for p in root.iterdir() if p.is_file() and LICENSE_NAME.match(p.name)):
        data = path.read_bytes()
        out.append({"path": path.name, "sha256": sha256_bytes(data), "detected": detect(data.decode("utf-8", "replace"))})
    return out


def cargo_lock_packages(lock: Path) -> dict[tuple[str, str], dict]:
    data = tomllib.loads(lock.read_text())
    return {(p["name"], p["version"]): {"source": p.get("source"), "checksum": p.get("checksum")} for p in data["package"]}


def read_target_sets(tree_dir: Path, kind: str) -> dict[str, set[str]]:
    sets = {}
    for f in sorted(tree_dir.glob(f"{kind}-*.txt")):
        target = f.stem[len(kind) + 1:]
        sets[target] = {line.strip().replace("@v", "@") for line in f.read_text().splitlines() if line.strip()}
    return sets


def rust_inventory(args, gaps: list[str]) -> list[dict]:
    ws_meta = json.loads(Path(args.cargo_metadata_workspace).read_text())
    binding_meta = json.loads(Path(args.cargo_metadata_binding).read_text())
    ws_lock = cargo_lock_packages(Path(args.cargo_lock_workspace))
    binding_lock = cargo_lock_packages(Path(args.cargo_lock_binding))
    # Optional per-target binding graph: `cargo metadata --filter-platform <triple>` resolve nodes.
    # Absent, rows and summary are unchanged (union over the binding Cargo.lock).
    target_keys = None
    if getattr(args, "cargo_metadata_binding_target", None):
        target_meta = json.loads(Path(args.cargo_metadata_binding_target).read_text())
        node_ids = {n["id"] for n in target_meta["resolve"]["nodes"]}
        target_keys = {(p["name"], p["version"]) for p in target_meta["packages"] if p["id"] in node_ids}
        for key in sorted(target_keys - set(binding_lock)):
            gaps.append(f"cargo binding target {args.binding_target}: {key[0]}@{key[1]} is not in the binding Cargo.lock")
    sbom = json.loads(Path(args.wheel_sbom).read_text())

    def walk(components):
        for c in components:
            yield c
            yield from walk(c.get("components", []))

    sbom_set = {(c["name"], c["version"]) for c in walk(sbom.get("components", []))}
    root = sbom.get("metadata", {}).get("component", {})
    sbom_set.add((root.get("name"), root.get("version")))
    linked = read_target_sets(Path(args.tree_dir), "linked")
    build = read_target_sets(Path(args.tree_dir), "build")
    cache = Path(args.cargo_registry_cache)
    upstream_path = getattr(args, "cargo_upstream_license_evidence", None)
    upstream = json.loads(Path(upstream_path).read_text()) if upstream_path else {}
    own_wheel = (own_crate_wheel_license_files(Path(args.own_crate_wheel), args.own_crate_wheel_sha256)
                 if getattr(args, "own_crate_wheel", None) else None)

    # Completeness: the lock files are the expected set; metadata must match them.
    for label, lock, meta in (("workspace", ws_lock, ws_meta), ("binding", binding_lock, binding_meta)):
        meta_keys = {(p["name"], p["version"]) for p in meta["packages"]}
        for key in sorted(set(lock) - meta_keys):
            gaps.append(f"cargo {label}: {key[0]}@{key[1]} is in Cargo.lock but not in cargo metadata")
        for key in sorted(meta_keys - set(lock)):
            gaps.append(f"cargo {label}: {key[0]}@{key[1]} is in cargo metadata but not in Cargo.lock")
    meta_by_key = {(p["name"], p["version"]): p for meta in (ws_meta, binding_meta) for p in meta["packages"]}

    rows = []
    for key in sorted(set(ws_lock) | set(binding_lock)):
        name, version = key
        lock_entry = ws_lock.get(key) or binding_lock[key]
        p = meta_by_key.get(key)
        hold = []
        source = lock_entry["source"]
        if source and source.startswith("registry+"):
            crates = sorted(cache.glob(f"*/{name}-{version}.crate"))
            archive_bytes = None
            read_error = None
            if crates:
                try:
                    archive_bytes = read_stable_bytes(crates[0])
                except OSError as exc:
                    read_error = str(exc)
            measured = sha256_bytes(archive_bytes) if archive_bytes is not None else None
            expected = lock_entry["checksum"]
            bound = measured is not None and expected is not None and measured == expected
            source_hash = {"algorithm": "sha256", "expected": expected, "expected_origin": "Cargo.lock checksum",
                           "measured": measured, "measured_origin": ".crate bytes in the cargo registry cache",
                           "match": bound}
            files, archive_errors = read_crate_license_files(
                archive_bytes, measured, p.get("license_file") if p else None,
                bool(getattr(args, "reviewed_pointer_notices", False)),
            ) if bound else ([], [])
            hold.extend(archive_errors)
            text_origin = None
            if bound and not files and f"{name}@{version}" in upstream:
                files, upstream_errors = bind_upstream_license_files(
                    archive_bytes, name, version, upstream[f"{name}@{version}"], Path(upstream_path).parent)
                hold.extend(upstream_errors)
                text_origin = "upstream-vcs" if files else None
            if not bound:
                hold.append("the .crate bytes are missing or do not match the Cargo.lock checksum")
            if read_error:
                hold.append(f"the .crate source path was not stable: {read_error}")
            if bound and not files:
                hold.append("the hash-bound .crate contains no license file")
            if bound and text_origin and p and p.get("license_file"):
                hold.append("Cargo metadata license_file is absent from the hash-bound .crate")
            if bound and not text_origin and p and p.get("license_file") and not any(
                f["declared_license_file"] for f in files
            ):
                hold.append("Cargo metadata license_file is absent from the hash-bound .crate")
            origin = ("package metadata (Cargo.toml license); license files read from the .crate whose sha256 "
                      "equals the Cargo.lock checksum" + ("" if files else "; the .crate contains NO license file")
                      ) if bound else "UNVERIFIED: no hash-bound .crate, license text not read"
            if text_origin:
                origin = ("package metadata (Cargo.toml license); the hash-bound .crate contains NO license file; "
                          "license files from upstream at the commit named by its .cargo_vcs_info.json, sha256-pinned")
        elif source is None and p is not None:
            text_origin = None
            source_hash = None
            files = license_files_in_dir(Path(p["manifest_path"]).parent)
            origin = "package metadata (Cargo.toml license); this repository's own source"
            if own_wheel is not None:
                wheel_version, wheel_files, wheel_errors = own_wheel
                hold.extend(wheel_errors)
                if not wheel_errors and wheel_version != version:
                    hold.append(f"own-crate wheel METADATA Version {wheel_version!r} != crate version {version!r}")
                elif not wheel_errors:
                    files = files + wheel_files
                    text_origin = "published-wheel"
                    origin += "; license files from the sha256-pinned published wheel's METADATA License-File"
        else:
            source_hash, files, origin, text_origin = None, [], "UNVERIFIED: unsupported source", None
            hold.append(f"unsupported source {source!r}")
        if p is None:
            hold.append("no cargo metadata row for this lock entry")
        declared = p["license"] if p else None
        norm = normalize_spdx(declared)
        elected, rationale = elect(norm)
        ident = f"{name}@{version}"
        for f in files:
            if "pointer_notice" not in f:
                continue
            names = set(f["pointer_notice"]["names"])
            full = {lbl for g in files if g is not f and g.get("artifact_sha256") == f["artifact_sha256"]
                    for lbl in g.get("verified_standard_text", [])}
            missing = sorted(names - full)
            mismatch = names != set(spdx_terms(norm))
            f["pointer_notice"]["satisfied"] = not missing and not mismatch
            if missing:
                hold.append(f"reviewed pointer {f['path']!r} names {missing} without a verified full text in this .crate")
            if mismatch:
                hold.append(f"reviewed pointer {f['path']!r} names {sorted(names)} but the declared expression is {norm!r}")
        satisfied_pointers = {f["path"] for f in files if f.get("pointer_notice", {}).get("satisfied")}
        file_labels = {label for f in files for label in f["detected"]}
        verified_labels = {
            label for f in files for label in f.get("verified_standard_text", [])
        }
        unrecognized_files = sorted(f["path"] for f in files if not f["detected"] and f["path"] not in satisfied_pointers)
        if unrecognized_files:
            hold.append(f"license candidate text is unrecognized: {unrecognized_files}")
        unverified_files = sorted(
            f["path"] for f in files if not f.get("verified_standard_text") and f["path"] not in satisfied_pointers
        )
        if unverified_files:
            hold.append(f"license candidate text is not canonically verified: {unverified_files}")
        declared_ids = spdx_terms(norm)
        uncovered_copyleft = sorted(
            label for label in file_labels if label in COPYLEFT_TEXT_LABELS
            and not _text_covered_by(label, declared_ids)
        )
        if uncovered_copyleft:
            hold.append(
                f"artifact text also grants {uncovered_copyleft}, which the declared expression does not name"
            )
        elected_terms = spdx_terms(elected)
        elected_text_present = all(
            t in UNFINGERPRINTED_IDS or any(_label_covers(t, lbl) for lbl in verified_labels)
            for t in elected_terms
        ) if elected_terms else False
        if elected_terms and not elected_text_present:
            hold.append("elected license text was not verified in the hash-bound artifact")
        base = classify(elected) if elected else "UNKNOWN"
        rows.append({
            "ecosystem": "cargo",
            "name": name,
            "version": version,
            "source": source or "path (this repository)",
            "source_hash": source_hash,
            "declared_license": declared,
            "declared_license_file": p["license_file"] if p else None,
            "spdx_normalized": norm,
            "declared_license_class": classify(norm),
            "license_class": "HOLD" if hold and base != "UNKNOWN" else base,
            "hold_reasons": hold,
            "elected_license": elected,
            "election_rationale": rationale,
            "license_files_in_artifact": files,
            "elected_text_present_in_artifact": elected_text_present,
            "value_origin": origin,
            "in_workspace_lock": key in ws_lock,
            "in_binding_lock_graph": key in binding_lock,
            "in_wheel_sbom": key in sbom_set,
            "linked_into_core_for_targets": sorted(t for t, s in linked.items() if ident in s),
            "compiled_at_build_for_targets": sorted(t for t, s in build.items() if ident in s),
            **({"license_text_origin": text_origin} if text_origin else {}),
        })
    for row in rows:
        row["in_published_artifact_scope"] = row["in_binding_lock_graph"]
        if target_keys is not None:
            row["in_binding_target_graph"] = (row["name"], row["version"]) in target_keys
        row["scope_note"] = (
            "compiled into fast_mlsirm/_core for the listed targets" if row["linked_into_core_for_targets"]
            else "build-time only (proc-macro/build script) for the listed targets" if row["compiled_at_build_for_targets"]
            else "in binding lock graph and wheel SBOM but not compiled for any published target" if row["in_binding_lock_graph"]
            else "workspace lock only (dev/test path); not in any published artifact"
        )
    return rows


def parse_notice_stanzas(text: str) -> tuple[list[dict], bool]:
    stanzas = []
    normalized_text = text.replace("\r\n", "\n").replace("\r", "\n")
    starts = [match.start() for match in re.finditer(r"^Name: ", normalized_text, re.MULTILINE)]
    file_consumed = bool(starts) and not normalized_text[:starts[0]].strip()
    for index, start in enumerate(starts):
        end = starts[index + 1] if index + 1 < len(starts) else len(normalized_text)
        block = normalized_text[start:end].rstrip("\n")
        fields = dict(re.findall(r"^(Name|Files|Description|License): (.*)$", block, re.MULTILINE))
        if "Name" in fields and "Files" in fields:
            lines = block.splitlines()
            complete = (
                len(lines) >= 3
                and lines[0].startswith("Name: ") and bool(lines[0][len("Name: "):])
                and lines[1].startswith("Files: ") and bool(lines[1][len("Files: "):])
                and lines[2].startswith("License: ") and bool(lines[2][len("License: "):])
                and all(line == "." or line.startswith(" ") for line in lines[3:])
            )
            file_consumed = file_consumed and complete
            body = "\n".join(lines[3:]) if complete else ""
            # Debian-style notice continuation lines have one indentation
            # column and use a single dot for a blank line.
            body = "\n".join(
                "" if line.strip() == "." else line[1:] if line.startswith(" ") else line
                for line in body.splitlines()
            )
            fields["Verified-Text"] = verified_standard_text(body) if complete else []
            stanzas.append(fields)
        else:
            file_consumed = False
    if not file_consumed:
        for stanza in stanzas:
            stanza["Verified-Text"] = []
    return stanzas, file_consumed


_VERSIONED_SONAME = re.compile(r"^(?P<stem>.+)\.so(?:\.[0-9]+)+$")
_MACOS_DYLIB = re.compile(r"^(?P<stem>.+)\.dylib$")


_WINDOWS_DRIVE = re.compile(r"^[A-Za-z]:")


def notice_files_pattern_to_posix(pattern: str) -> str | None:
    """Canonicalize one notice ``Files:`` pattern, or reject it.

    Windows wheels write notice paths with backslashes
    (``numpy.libs\\libscipy_openblas*.dll``), while wheel members always use
    ``/``.  Every backslash becomes ``/`` and the result must then pass the same
    canonical relative-path checks as any member path, so traversal (``..\\``),
    absolute or UNC roots (``\\``, ``\\\\server``) and drive letters (``C:``) are
    still rejected.  fnmatch has no escape character, so this cannot change
    what a glob means.  Only the notice side is converted; a member path that
    itself contains a backslash stays rejected when the wheel is read.
    """
    converted = pattern.replace("\\", "/")
    if _WINDOWS_DRIVE.match(converted):
        return None
    return normalized_archive_path(converted)


def notice_files_pattern_matches(member: str, pattern: str) -> bool:
    """Bind one notice ``Files:`` pattern to one native wheel member.

    Exact patterns stay exact.  A glob ending in ``.so`` also binds the
    platform spellings that wheel notices describe with the generic suffix:
    versioned ELF sonames (``libquadmath-<hash>.so.0.0.0``) and, inside a
    ``.dylibs/`` directory, macOS ``.dylib`` names (``libquadmath.0.dylib``).
    The glob stem must match the member stem in the same directory, so an
    unrelated library is never bound and an unmatched member keeps failing
    closed as "no bound notice stanza".
    """
    pattern = notice_files_pattern_to_posix(pattern)
    if pattern is None:
        return False
    if fnmatch.fnmatchcase(member, pattern):
        return True
    if not pattern.endswith(".so") or not any(c in pattern for c in "*?["):
        return False
    if member.rpartition("/")[0] != pattern.rpartition("/")[0]:
        return False
    stem_pattern = pattern[: -len(".so")]
    soname = _VERSIONED_SONAME.match(member)
    if soname and fnmatch.fnmatchcase(soname["stem"], stem_pattern):
        return True
    dylib = _MACOS_DYLIB.match(member)
    return bool(
        dylib
        and member.rpartition("/")[0].rpartition("/")[2] == ".dylibs"
        and fnmatch.fnmatchcase(dylib["stem"], stem_pattern)
    )


def notice_stanza_grant_verified(stanza: dict) -> bool:
    """Require a permissive election whose exact grant is verified in this stanza."""
    declared = normalize_spdx(stanza.get("License"))
    elected, _ = elect(declared)
    terms = spdx_terms(elected) if elected else []
    return bool(terms) and classify(elected) == "PERMISSIVE" and all(
        any(_label_covers(term, label) for label in stanza["Verified-Text"])
        for term in terms
    )


def python_artifact_evidence(path: Path) -> dict:
    data = path.read_bytes()
    ev = {"artifact": path.name, "sha256": sha256_bytes(data), "license_files": [],
          "metadata": {}, "vendored_native": [], "evidence_errors": []}
    if path.suffix != ".whl":
        return ev
    with zipfile.ZipFile(io.BytesIO(data)) as zf:
        members = {}
        for info in zf.infolist():
            normalized = normalized_archive_path(info.filename)
            if normalized is None:
                ev["evidence_errors"].append(
                    f"unsafe or non-canonical wheel member path: {info.filename!r}"
                )
                continue
            if normalized in members:
                ev["evidence_errors"].append(f"duplicate wheel member path: {normalized!r}")
                continue
            members[normalized] = info
        metadata_paths = sorted(n for n in members if n.endswith(".dist-info/METADATA"))
        if len(metadata_paths) != 1:
            ev["evidence_errors"].append(
                f"wheel must contain exactly one .dist-info/METADATA member; found {len(metadata_paths)}"
            )
            return ev
        meta = metadata_paths[0]
        metadata_message = BytesParser(policy=policy.default).parsebytes(
            zf.read(members[meta]), headersonly=True
        )
        metadata_defects = list(metadata_message.defects)
        metadata_defects.extend(
            defect
            for header in metadata_message.values()
            for defect in getattr(header, "defects", ())
        )
        if metadata_defects:
            ev["evidence_errors"].append(
                "METADATA header parser reported defects: "
                + ", ".join(type(defect).__name__ for defect in metadata_defects)
            )
        for key in ("License", "License-Expression", "License-File"):
            values = [str(value).strip() for value in metadata_message.get_all(key, [])]
            if values:
                ev["metadata"][key] = values
        classifiers = [
            str(value).strip() for value in metadata_message.get_all("Classifier", [])
            if str(value).strip().startswith("License")
        ]
        if classifiers:
            ev["metadata"]["Classifier"] = classifiers
        for singleton in ("License", "License-Expression"):
            if len(ev["metadata"].get(singleton, [])) > 1:
                ev["evidence_errors"].append(f"duplicate METADATA {singleton} declaration")
        declared_values = ev["metadata"].get("License-File", [])
        if len(declared_values) != len(set(declared_values)):
            ev["evidence_errors"].append("duplicate METADATA License-File declaration")
        dist_info = meta.rsplit("/", 1)[0]
        declared_paths = set()
        for value in declared_values:
            declared = normalized_archive_path(value)
            if declared is None:
                ev["evidence_errors"].append(
                    f"METADATA License-File is not a safe canonical relative path: {value!r}"
                )
                continue
            resolved = f"{dist_info}/licenses/{declared}"
            declared_paths.add(resolved)
            if resolved not in members:
                ev["evidence_errors"].append(
                    f"declared METADATA License-File member is absent: {resolved!r}"
                )
        stanzas = []
        for n, info in members.items():
            base = n.rsplit("/", 1)[-1]
            if ".dist-info/" in n and (LICENSE_NAME.match(base) or n in declared_paths):
                raw = zf.read(info)
                text = raw.decode("utf-8", "replace")
                file_stanzas, notice_consumed = parse_notice_stanzas(text)
                for stanza in file_stanzas:
                    stanza["Source-Path"] = n
                    stanza["Matched-Native"] = []
                stanzas.extend(file_stanzas)
                whole_text = verified_standard_text(text)
                ev["license_files"].append({
                    "path": n,
                    "sha256": sha256_bytes(raw),
                    "detected": detect(text),
                    "verified_standard_text": whole_text,
                    "notice_file_fully_consumed": notice_consumed,
                    "candidate_verified": False,
                })
        for n, info in members.items():
            base = n.rsplit("/", 1)[-1]
            if re.search(r"\.(so(\.[0-9]+)*|dylib|dll|a)$", base) and (
                ".libs/" in n or ".dylibs/" in n or "/" not in n
            ):
                norm = n
                match = [s for s in stanzas if any(
                    notice_files_pattern_matches(norm, g.strip())
                    for g in s["Files"].split(",")
                )]
                for stanza in match:
                    stanza["Matched-Native"].append(norm)
                ev["vendored_native"].append({
                    "path": n,
                    "sha256": sha256_bytes(zf.read(info)),
                    "notice_stanza": [{
                        "name": s["Name"],
                        "license": s.get("License"),
                        "description": s.get("Description"),
                        "verified_text": s["Verified-Text"],
                    } for s in match],
                })
        for candidate in ev["license_files"]:
            file_stanzas = [s for s in stanzas if s["Source-Path"] == candidate["path"]]
            candidate["verified_notice_text"] = sorted({
                label for stanza in file_stanzas for label in stanza["Verified-Text"]
            })
            candidate["candidate_verified"] = bool(candidate["verified_standard_text"]) or (
                candidate["notice_file_fully_consumed"]
                and bool(file_stanzas)
                and all(
                    notice_stanza_grant_verified(stanza) and stanza["Matched-Native"]
                    for stanza in file_stanzas
                )
            )
        ev["notice_stanzas_declared"] = [{"name": s["Name"], "files": s["Files"], "license": s.get("License")} for s in stanzas]
    return ev


def vendored_native_license_holds(artifacts: list[dict]) -> list[str]:
    """Return fail-closed findings for hash-bound native wheel components."""
    findings = []
    for artifact in artifacts:
        if not artifact["hash_binding"]["match"]:
            continue
        findings.extend(
            f"{artifact['artifact']}: {error}" for error in artifact.get("evidence_errors", [])
        )
        for native in artifact["vendored_native"]:
            stanzas = native["notice_stanza"]
            if not stanzas:
                findings.append(f"{native['path']}: no bound notice stanza")
                continue
            for stanza in stanzas:
                declared = normalize_spdx(stanza.get("license"))
                if not notice_stanza_grant_verified({
                    "License": stanza.get("license"),
                    "Verified-Text": stanza["verified_text"],
                }):
                    findings.append(
                        f"{native['path']}: vendored native license is "
                        f"{declared or 'UNKNOWN'} with no verified elected grant"
                    )
        for candidate in artifact["license_files"]:
            if not candidate["candidate_verified"]:
                findings.append(
                    f"{candidate['path']}: license candidate file was not fully verified"
                )
    return sorted(set(findings))


REQ_PIN = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s\\;]+)")
REQ_BLOCK = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s\\]+) \\\n((?:[ \t]+--hash=sha256:[0-9a-f]{64}(?: \\)?\n)+)", re.MULTILINE)


def parse_requirements(path: Path, gaps: list[str]) -> dict[tuple[str, str], list[str]]:
    """Hash-pinned requirements; every top-level line must be a fully hashed pin."""
    text = path.read_text()
    parsed = {}
    for m in REQ_BLOCK.finditer(text):
        name = m.group(1).lower().replace("_", "-")
        parsed[(name, m.group(2))] = ["sha256:" + h for h in re.findall(r"sha256:([0-9a-f]{64})", m.group(3))]
    for line in text.splitlines():
        if not line.strip() or line.startswith("#") or line[0] in " \t":
            continue
        m = REQ_PIN.match(line)
        if not m:
            gaps.append(f"{path.as_posix()}: unparsed requirement line {line!r}")
        elif (m.group(1).lower().replace("_", "-"), m.group(2)) not in parsed:
            gaps.append(f"{path.as_posix()}: pin {m.group(1)}=={m.group(2)} has no parsed --hash block")
    return parsed


def python_inventory(args, gaps: list[str]) -> list[dict]:
    uv = tomllib.loads(Path(args.uv_lock).read_text())
    entries: dict[tuple[str, str], dict] = {}
    for p in uv["package"]:
        if p["source"].get("editable") or p["source"].get("virtual"):
            continue  # the project itself
        hashes = [p["sdist"]["hash"]] if "sdist" in p else []
        hashes += [w["hash"] for w in p.get("wheels", [])]
        if not hashes:
            gaps.append(f"uv.lock: {p['name']}@{p['version']} has no artifact hash")
        entries.setdefault((p["name"], p["version"]), {"locks": {}})["locks"]["uv.lock"] = hashes
    for req in args.requirements:
        for key, hashes in parse_requirements(Path(req), gaps).items():
            entries.setdefault(key, {"locks": {}})["locks"][Path(req).as_posix()] = hashes
    for extra in args.extra_python or []:
        name, version, why = extra.split("==", 1)[0], extra.split("==", 1)[1].split(":", 1)[0], extra.split(":", 1)[1]
        entries.setdefault((name, version), {"locks": {}})["locks"][why] = []

    scope = json.loads(Path(args.python_scope).read_text())
    for name in sorted(set(scope) - {n for n, _ in entries}):
        gaps.append(f"python scope entry {name!r} matches no inventoried package")
    meta_dir, art_dir = Path(args.pypi_meta_dir), Path(args.pypi_artifact_dir)
    rows = []
    for (name, version), e in sorted(entries.items()):
        hold = []
        meta_path = meta_dir / f"{name}-{version}.json"
        if meta_path.exists():
            meta_doc = json.loads(meta_path.read_text())
        else:
            meta_doc = {"info": {}, "urls": []}
            gaps.append(f"pypi: {name}@{version} has no PyPI metadata JSON")
        meta = meta_doc["info"]
        pypi_digests = {u["filename"]: u["digests"]["sha256"] for u in meta_doc.get("urls", [])}
        declared = meta.get("license_expression") or None
        classifiers = [c for c in meta.get("classifiers") or [] if c.startswith("License ::")]
        paths = {a for stem in {name, name.replace("-", "_")} for a in art_dir.glob(f"{stem}-{version}[-.]*")}
        expected = {h.split(":", 1)[1] for hs in e["locks"].values() for h in hs}
        artifacts = []
        for a in sorted(paths):
            ev = python_artifact_evidence(a)
            if expected:
                ev["hash_binding"] = {"expected_origin": "lock hashes", "match": ev["sha256"] in expected}
            else:
                ev["hash_binding"] = {"expected_origin": "PyPI JSON digest (no lock hash exists)",
                                      "match": pypi_digests.get(a.name) == ev["sha256"]}
            if not ev["hash_binding"]["match"]:
                hold.append(f"artifact {a.name} sha256 does not match its expected hash")
            artifacts.append(ev)
        if not artifacts:
            hold.append("no artifact examined, so no license text was verified")
        native_holds = vendored_native_license_holds(artifacts)
        if native_holds:
            hold.append(f"vendored native license evidence is not verified permissive: {native_holds}")
        unverified_candidates = sorted({
            f"{a['artifact']}:{candidate['path']}"
            for a in artifacts if a["hash_binding"]["match"]
            for candidate in a["license_files"] if not candidate["candidate_verified"]
        })
        if unverified_candidates:
            hold.append(f"artifact license candidate files are not fully verified: {unverified_candidates}")
        text_labels = sorted({lbl for a in artifacts if a["hash_binding"]["match"] for f in a["license_files"] for lbl in f["detected"]})
        copyleft_text = [lbl for lbl in text_labels if lbl in COPYLEFT_TEXT_LABELS + WEAK_COPYLEFT_TEXT_LABELS]
        norm = normalize_spdx(declared)
        elected, rationale = elect(norm)
        if declared:
            declared_ids = spdx_terms(norm)
            agrees = bool(text_labels) and all(any(_label_covers(t, lbl) for lbl in text_labels)
                                               for t in spdx_terms(elected or norm) if t not in UNFINGERPRINTED_IDS)
            uncovered = [lbl for lbl in copyleft_text if not _text_covered_by(lbl, declared_ids) and lbl not in declared_ids]
            determination = {"spdx": norm, "origin": "package metadata License-Expression", "text_agrees": agrees,
                             "copyleft_text_not_in_declared_expression": uncovered}
            if not agrees:
                hold.append("declared license text not found in a hash-bound artifact")
            if uncovered:
                hold.append(f"artifact text also grants {uncovered}, which the declared expression does not name")
        else:
            cls_terms = {CLASSIFIER_SPDX.get(c) for c in classifiers} - {None}
            permissive_text = [lbl for lbl in text_labels if lbl not in copyleft_text]
            if copyleft_text:
                determination = {"spdx": None, "origin": f"HOLD - artifact text contains {copyleft_text} and metadata declares no expression",
                                 "text_agrees": False, "copyleft_text_not_in_declared_expression": copyleft_text}
                hold.append(f"artifact text contains {copyleft_text} with no declared expression")
            elif cls_terms and len(permissive_text) == 1 and all(permissive_text[0].startswith(t) for t in cls_terms):
                determination = {"spdx": permissive_text[0], "origin": "trove classifier confirmed by the license file in the artifact (no License-Expression)", "text_agrees": True,
                                 "copyleft_text_not_in_declared_expression": []}
            elif not cls_terms and len(permissive_text) == 1:
                determination = {"spdx": permissive_text[0], "origin": "license file in the artifact ONLY - package metadata declares no license; recorded as an explicit evidence-based exception, not inferred from absence", "text_agrees": True,
                                 "copyleft_text_not_in_declared_expression": []}
            else:
                determination = {"spdx": None, "origin": "UNKNOWN - on hold", "text_agrees": False,
                                 "copyleft_text_not_in_declared_expression": []}
            elected = determination["spdx"]
        base = classify(elected) if elected else "UNKNOWN"
        if name in scope:
            scope_fields = scope[name]
        else:
            scope_fields = {"scope": "UNCLASSIFIED", "in_published_artifact_scope": None, "runtime_dependency_of_published_artifact": None}
            gaps.append(f"python scope: {name} has no scope entry")
        rows.append({
            "ecosystem": "pypi",
            "name": name,
            "version": version,
            "locks": {k: {"hash_count": len(v), "hashes": v} for k, v in e["locks"].items()},
            "declared_license_expression": declared,
            "declared_license_field": (meta.get("license") or None) and meta["license"][:200],
            "declared_classifiers": classifiers,
            "license_text_detected_in_artifact": text_labels,
            "license_class_from_metadata": classify(norm) if declared else ("UNKNOWN" if not classifiers else "CLASSIFIER-ONLY"),
            "license_determination": determination,
            "vendored_native_license_holds": native_holds,
            "license_class": "HOLD" if hold and base in ("PERMISSIVE", "WEAK-COPYLEFT") else base,
            "hold_reasons": hold,
            "elected_license": elected,
            "election_rationale": rationale,
            "artifacts_examined": artifacts,
            **scope_fields,
        })
    return rows


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--cargo-metadata-workspace", required=True)
    ap.add_argument("--cargo-metadata-binding", required=True)
    ap.add_argument("--cargo-lock-workspace", required=True)
    ap.add_argument("--cargo-lock-binding", required=True)
    ap.add_argument("--cargo-registry-cache", required=True, help="$CARGO_HOME/registry/cache (holds the .crate files)")
    ap.add_argument("--wheel-sbom", required=True)
    ap.add_argument("--tree-dir", required=True)
    ap.add_argument("--uv-lock", required=True)
    ap.add_argument("--requirements", nargs="+", required=True)
    ap.add_argument("--extra-python", nargs="*", help="name==version:reason for build tools outside the locks")
    ap.add_argument("--python-scope", required=True)
    ap.add_argument("--pypi-meta-dir", required=True)
    ap.add_argument("--pypi-artifact-dir", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--cargo-metadata-binding-target", help="cargo metadata --filter-platform output for --binding-target")
    ap.add_argument("--binding-target", help="target triple of --cargo-metadata-binding-target")
    ap.add_argument("--reviewed-pointer-notices", action="store_true",
                    help="accept POINTER_NOTICES files whose named licenses are verified in the same .crate and match the declared expression")
    ap.add_argument("--own-crate-wheel", help="published wheel whose METADATA License-File binds this repository's own crates")
    ap.add_argument("--own-crate-wheel-sha256", help="expected sha256 of --own-crate-wheel")
    ap.add_argument("--cargo-upstream-license-evidence",
                    help="JSON {name@version: {repository, vcs_sha1, path_in_vcs, files: [{path, url, sha256, local_path}]}}; "
                         "local_path is relative to this file")
    args = ap.parse_args(argv)
    if bool(args.cargo_metadata_binding_target) != bool(args.binding_target):
        ap.error("--cargo-metadata-binding-target and --binding-target must be given together")
    if bool(args.own_crate_wheel) != bool(args.own_crate_wheel_sha256):
        ap.error("--own-crate-wheel and --own-crate-wheel-sha256 must be given together")

    gaps: list[str] = []
    rust = rust_inventory(args, gaps)
    python = python_inventory(args, gaps)
    summary = {
        "completeness_gaps": gaps,
        "cargo_workspace_lock_packages": sum(r["in_workspace_lock"] for r in rust),
        "cargo_binding_graph_packages": sum(r["in_binding_lock_graph"] for r in rust),
        "cargo_wheel_sbom_packages": sum(r["in_wheel_sbom"] for r in rust),
        "cargo_by_class": {c: sum(r["license_class"] == c for r in rust) for c in CLASSES},
        "cargo_by_declared_class": {c: sum(r["declared_license_class"] == c for r in rust) for c in CLASSES},
        "cargo_disjunctive_with_copyleft_alternative": [f"{r['name']}@{r['version']}" for r in rust if " OR " in (r["spdx_normalized"] or "") and r["declared_license_class"] == "COPYLEFT"],
        "cargo_without_license_file_in_crate": [f"{r['name']}@{r['version']}" for r in rust if not r["license_files_in_artifact"] and r["source"] != "path (this repository)"],
        "cargo_elected_text_missing": [f"{r['name']}@{r['version']}" for r in rust if not r["elected_text_present_in_artifact"] and r["source"] != "path (this repository)"],
        "cargo_crate_hash_unbound": [f"{r['name']}@{r['version']}" for r in rust if r["source_hash"] is not None and not r["source_hash"]["match"]],
        **({"cargo_binding_target": args.binding_target,
            "cargo_binding_target_graph_packages": sum(r["in_binding_target_graph"] for r in rust),
            "cargo_binding_target_by_class": {c: sum(r["in_binding_target_graph"] and r["license_class"] == c for r in rust) for c in CLASSES}}
           if args.binding_target else {}),
        "pypi_packages": len(python),
        "pypi_metadata_unknown": [f"{r['name']}@{r['version']}" for r in python if r["license_class_from_metadata"] == "UNKNOWN"],
        "pypi_by_class": {c: [f"{r['name']}@{r['version']}" for r in python if r["license_class"] == c] for c in CLASSES if c != "PERMISSIVE"},
        "pypi_hold_reasons": {f"{r['name']}@{r['version']}": r["hold_reasons"] for r in python if r["hold_reasons"]},
        "pypi_vendored_native_by_notice_license": sorted({(s.get("license") or "NO NOTICE IN ARTIFACT") for r in python for a in r["artifacts_examined"] for v in a["vendored_native"] for s in (v["notice_stanza"] or [{}])}),
    }
    Path(args.out).write_text(json.dumps({"summary": summary, "cargo": rust, "pypi": python}, indent=1, sort_keys=True) + "\n")
    print(json.dumps(summary, indent=1))
    return 1 if gaps else 0


if __name__ == "__main__":
    raise SystemExit(main())
