//! Tests for Guttman lambda reliability (`crate::reliability`).
//!
//! Fixture literals come from an INDEPENDENT NumPy replication
//! (session files/guttman_fixture.py): np.corrcoef + np.linalg.inv +
//! itertools.combinations, with data generated by a NumPy mirror of the
//! crate LCG (np.uint64). Every assert reads a `GuttmanResult` field
//! returned by `guttman_lambdas` — no test-local recomputation of any
//! lambda.
//!
//! Mutation kills verified by hand-editing the implementation (each FAILED,
//! then was restored):
//! - M1 drop `.abs()` in `split_rb` -> fixture A/B lambda4/beta/mean_split.
//! - M2 drop the `p/(p-1)` factor inside lambda2's sqrt -> lambda2 pins.
//! - M3 lambda5 uses the SUM of `C_j` instead of the max -> lambda5 pins.
//! - M4 drop the SMC clamp / use `1/diag` without `1 -` -> lambda6 pins.
//! - M5 break the combination stepper (skip last combination) -> n_splits
//!   pin (exhaustive counts are exact binomials).
//!
//! Known identity limit (disclosed): `lambda3 = p/(p-1) * lambda1` is exact
//! algebra, so a mutation rescaling BOTH consistently cannot be caught by
//! any data fixture; the discriminating anchor is that lambda1 and lambda3
//! are pinned to independent NumPy literals, so only jointly consistent
//! mutations survive. Likewise `Vt = sum(R)` equals the per-split collapsed
//! total for every partition, so substituting one for the other is
//! mathematically identical and unkillable.
use super::*;

const TOL: f64 = 1e-9;

/// NumPy-mirrored LCG data generator (fixture input construction only; the
/// code under test never sees these helpers).
fn gen_data(
    n: usize,
    p: usize,
    seed: u64,
    loadings: &[f64],
    means: &[f64],
    scales: &[f64],
) -> Vec<f64> {
    let mut state = seed.max(1);
    let mut uniform = |state: &mut u64| -> f64 {
        *state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        (*state >> 11) as f64 / (1u64 << 53) as f64
    };
    let mut normal = |state: &mut u64| -> f64 {
        let u1 = uniform(state).max(1e-12);
        let u2 = uniform(state);
        (-2.0 * u1.ln()).sqrt() * (2.0 * std::f64::consts::PI * u2).cos()
    };
    let mut out = vec![0.0_f64; n * p];
    for i in 0..n {
        let f = normal(&mut state);
        for j in 0..p {
            let e = normal(&mut state);
            out[i * p + j] = means[j] + scales[j] * (loadings[j] * f + e);
        }
    }
    out
}

#[test]
fn fixture_a_exhaustive_even_p() {
    let data = gen_data(
        30,
        6,
        42,
        &[0.9, 0.8, 0.7, 0.6, 0.5, 0.2],
        &[10.0, -3.0, 5.0, 0.5, 100.0, 7.0],
        &[1.0, 2.0, 0.5, 3.0, 10.0, 1.5],
    );
    let g = guttman_lambdas(&data, 30, 6, 15000, 1).expect("fixture A");
    assert!((g.lambda1 - 0.41068157604336863).abs() < TOL);
    assert!((g.lambda2 - 0.5561900258418755).abs() < TOL);
    assert!((g.lambda3 - 0.49281789125204234).abs() < TOL);
    assert!((g.lambda4 - 0.6842463861953535).abs() < TOL);
    assert!((g.lambda5 - 0.5602004712206824).abs() < TOL);
    assert!((g.lambda6 - 0.59150154331973).abs() < TOL);
    assert!((g.beta - 0.1784553694910821).abs() < TOL);
    assert!((g.mean_split - 0.4928178912520423).abs() < TOL);
    assert_eq!(g.n_splits, 20); // C(6, 3)
    assert!(g.exhaustive);
}

#[test]
fn fixture_b_exhaustive_odd_p() {
    let data = gen_data(
        24,
        5,
        99,
        &[0.8, 0.7, 0.6, 0.5, 0.4],
        &[1.0, 2.0, 3.0, 4.0, 5.0],
        &[1.0, 1.0, 2.0, 1.0, 0.5],
    );
    let g = guttman_lambdas(&data, 24, 5, 15000, 1).expect("fixture B");
    assert!((g.lambda1 - 0.36304984346951963).abs() < TOL);
    assert!((g.lambda2 - 0.5427967072982294).abs() < TOL);
    assert!((g.lambda3 - 0.45381230433689956).abs() < TOL);
    assert!((g.lambda4 - 0.6863584325671727).abs() < TOL);
    assert!((g.lambda5 - 0.5668547649655623).abs() < TOL);
    assert!((g.lambda6 - 0.5667118066898096).abs() < TOL);
    assert!((g.beta - 0.04899616716352421).abs() < TOL);
    assert!((g.mean_split - 0.44545904559612853).abs() < TOL);
    assert_eq!(g.n_splits, 10); // C(5, 2): m = floor(5/2), A size 2 vs B size 3
    assert!(g.exhaustive);
}

#[test]
fn fixture_c_sampled_branch() {
    let mut loadings = vec![0.7_f64; 10];
    loadings.extend(vec![0.4_f64; 10]);
    let data = gen_data(60, 20, 7, &loadings, &[0.0; 20], &[1.0; 20]);
    let g = guttman_lambdas(&data, 60, 20, 200, 7).expect("fixture C");
    assert!((g.lambda1 - 0.8173350703037762).abs() < TOL);
    assert!((g.lambda2 - 0.8657986449939672).abs() < TOL);
    assert!((g.lambda3 - 0.8603527055829222).abs() < TOL);
    assert!((g.lambda4 - 0.921571734274876).abs() < TOL);
    assert!((g.lambda5 - 0.8439917779688363).abs() < TOL);
    assert!((g.lambda6 - 0.8931192541579849).abs() < TOL);
    assert!((g.beta - 0.7974800893409002).abs() < TOL);
    assert!((g.mean_split - 0.8623803334548827).abs() < TOL);
    assert_eq!(g.n_splits, 200);
    assert!(!g.exhaustive);
}

#[test]
fn rejections() {
    let ok = gen_data(10, 4, 3, &[0.5; 4], &[0.0; 4], &[1.0; 4]);
    assert!(guttman_lambdas(&ok, 2, 4, 100, 1).is_err()); // wrong length too
    assert!(guttman_lambdas(&ok[..8], 2, 4, 100, 1).is_err()); // n < 3
    assert!(guttman_lambdas(&ok[..20], 10, 2, 100, 1).is_err()); // p < 3
    assert!(guttman_lambdas(&ok, 10, 4, 0, 1).is_err()); // budget 0
    let mut nan = ok.clone();
    nan[5] = f64::NAN;
    assert!(guttman_lambdas(&nan, 10, 4, 100, 1).is_err());
    let mut constant = ok.clone();
    for i in 0..10 {
        constant[i * 4] = 2.5;
    }
    assert!(guttman_lambdas(&constant, 10, 4, 100, 1).is_err()); // zero variance
}

#[test]
fn singular_correlation_errs_for_lambda6() {
    // Duplicate columns: correlation_matrix succeeds (r = 1) but R is
    // exactly singular, so the SMC inverse must Err (divergence 4: psych
    // would silently Pinv; we refuse). Assert reads the crate Result.
    let base = gen_data(15, 1, 11, &[0.6], &[0.0], &[1.0]);
    let mut data = vec![0.0_f64; 15 * 3];
    for i in 0..15 {
        data[i * 3] = base[i];
        data[i * 3 + 1] = base[i]; // exact duplicate
        data[i * 3 + 2] = (i as f64).sin() + base[i];
    }
    let err = guttman_lambdas(&data, 15, 3, 100, 1).unwrap_err();
    assert!(err.contains("singular"), "unexpected error: {err}");
}

/// >= 500-replication Monte Carlo: tau-equivalent items (equal loadings,
/// equal noise), where coefficient alpha ( = lambda3) is consistent for the
/// true reliability rho = p*l^2 / (p*l^2 + p*s^2) of the unit-weighted sum
/// score under the one-factor model. With l = 0.7, s = 1, p = 8:
/// rho = 8*0.49 / (8*0.49 + 8) ... per-item communality basis; the sum-score
/// reliability is rho_sum = (p^2 l^2 sigma_f^2) / (p^2 l^2 sigma_f^2 +
/// p s^2) = (64*0.49)/(64*0.49 + 8) = 0.796696. Asserts read only crate
/// outputs (mean of returned lambda3 across reps).
#[test]
#[ignore]
fn mc_tau_equivalent_alpha_recovery() {
    let p = 8;
    let reps = 500;
    let mut sum_l3 = 0.0_f64;
    let mut ge = 0usize;
    for rep in 0..reps {
        let data = gen_data(
            300,
            p,
            1000 + rep as u64,
            &vec![0.7; p],
            &vec![0.0; p],
            &vec![1.0; p],
        );
        let g = guttman_lambdas(&data, 300, p, 500, 17).expect("mc rep");
        sum_l3 += g.lambda3;
        if g.lambda2 >= g.lambda3 - 1e-12 {
            ge += 1;
        }
    }
    let mean_l3 = sum_l3 / reps as f64;
    let rho = (64.0 * 0.49) / (64.0 * 0.49 + 8.0); // 0.796696...
    assert!(
        (mean_l3 - rho).abs() < 0.01,
        "mean lambda3 {mean_l3} vs analytic {rho}"
    );
    // Secondary (identity-adjacent, disclosed): Guttman's lambda2 >= lambda3
    // holds sample-wise; violations flag algebra mutations.
    assert_eq!(ge, reps);
}

// --- ten Berge & Zegers mu coefficients -------------------------------
//
// Fixture literals from an independent NumPy replication of tenberge.R
// (session files/tenberge_fixture.py: np.corrcoef + explicit off-diagonal
// power sums). Every assert reads TenBergeResult fields from the crate.
//
// Mutation kills verified by hand (each FAILED, then restored):
// - M1 drop the innermost `c` factor in mu2/mu3 -> mu2/mu3 pins (~5e-4
//   shift; tolerance 1e-9 kills it).
// - M2 use s2 where s4 belongs in mu2 -> mu2 pin.
// - M3 flatten one sqrt nesting level in mu3 -> mu3 pin.
//
// Disclosed identities: mu0 == guttman lambda3 and mu1 == guttman lambda2
// by exact algebra; both are pinned to independent NumPy literals (not to
// each other), so only jointly consistent mutations survive. S_2 over all
// cells vs 2x the upper triangle is identical for symmetric R; unkillable.

#[test]
fn tenberge_fixture_a() {
    let data = gen_data(
        30,
        6,
        42,
        &[0.9, 0.8, 0.7, 0.6, 0.5, 0.2],
        &[10.0, -3.0, 5.0, 0.5, 100.0, 7.0],
        &[1.0, 2.0, 0.5, 3.0, 10.0, 1.5],
    );
    let t = tenberge_mu(&data, 30, 6).expect("tenberge A");
    assert!((t.mu0 - 0.49281789125204223).abs() < TOL);
    assert!((t.mu1 - 0.5561900258418755).abs() < TOL);
    assert!((t.mu2 - 0.566334883191414).abs() < TOL);
    assert!((t.mu3 - 0.5694865282091219).abs() < TOL);
    // Cauchy-Schwarz series ordering, read from crate outputs.
    assert!(t.mu0 <= t.mu1 && t.mu1 <= t.mu2 && t.mu2 <= t.mu3);
}

#[test]
fn tenberge_fixture_b() {
    let data = gen_data(
        24,
        5,
        99,
        &[0.8, 0.7, 0.6, 0.5, 0.4],
        &[1.0, 2.0, 3.0, 4.0, 5.0],
        &[1.0, 1.0, 2.0, 1.0, 0.5],
    );
    let t = tenberge_mu(&data, 24, 5).expect("tenberge B");
    assert!((t.mu0 - 0.45381230433689973).abs() < TOL);
    assert!((t.mu1 - 0.5427967072982294).abs() < TOL);
    assert!((t.mu2 - 0.554450883437996).abs() < TOL);
    assert!((t.mu3 - 0.5577786174323536).abs() < TOL);
    assert!(t.mu0 <= t.mu1 && t.mu1 <= t.mu2 && t.mu2 <= t.mu3);
}

#[test]
fn tenberge_matches_guttman_identities() {
    // mu0 == lambda3 and mu1 == lambda2 (exact algebra, both sides crate
    // outputs from independent code paths: direct off-diag sums vs Vt - p).
    let data = gen_data(
        30,
        6,
        42,
        &[0.9, 0.8, 0.7, 0.6, 0.5, 0.2],
        &[10.0, -3.0, 5.0, 0.5, 100.0, 7.0],
        &[1.0, 2.0, 0.5, 3.0, 10.0, 1.5],
    );
    let t = tenberge_mu(&data, 30, 6).expect("mu");
    let g = guttman_lambdas(&data, 30, 6, 15000, 1).expect("lambdas");
    assert!((t.mu0 - g.lambda3).abs() < 1e-12);
    assert!((t.mu1 - g.lambda2).abs() < 1e-12);
}

#[test]
fn tenberge_rejections() {
    let ok = gen_data(10, 4, 3, &[0.5; 4], &[0.0; 4], &[1.0; 4]);
    assert!(tenberge_mu(&ok[..8], 2, 4).is_err()); // n < 3
    assert!(tenberge_mu(&ok[..20], 10, 2).is_err()); // p < 3
    assert!(tenberge_mu(&ok[..30], 10, 4).is_err()); // wrong length
    let mut nan = ok.clone();
    nan[7] = f64::INFINITY;
    assert!(tenberge_mu(&nan, 10, 4).is_err());
    let mut constant = ok.clone();
    for i in 0..10 {
        constant[i * 4 + 2] = -1.0;
    }
    assert!(tenberge_mu(&constant, 10, 4).is_err()); // zero variance
}

/// >= 500-replication Monte Carlo: same tau-equivalent design as the
/// Guttman MC. mu0 == alpha is consistent (asymptotically unbiased) for
/// rho_sum = (p^2 l^2)/(p^2 l^2 + p s^2) = 31.36/39.36 with l=0.7, s=1,
/// p=8, n=300. Also asserts the series ordering sample-wise on crate
/// outputs across all reps.
#[test]
#[ignore]
fn mc_tenberge_alpha_recovery_and_ordering() {
    let p = 8;
    let reps = 500;
    let mut sum_mu0 = 0.0_f64;
    let mut ordered = 0usize;
    for rep in 0..reps {
        let data = gen_data(
            300,
            p,
            2000 + rep as u64,
            &vec![0.7; p],
            &vec![0.0; p],
            &vec![1.0; p],
        );
        let t = tenberge_mu(&data, 300, p).expect("mc rep");
        sum_mu0 += t.mu0;
        if t.mu0 <= t.mu1 && t.mu1 <= t.mu2 && t.mu2 <= t.mu3 {
            ordered += 1;
        }
    }
    let mean_mu0 = sum_mu0 / reps as f64;
    let rho = (64.0 * 0.49) / (64.0 * 0.49 + 8.0);
    assert!(
        (mean_mu0 - rho).abs() < 0.01,
        "mean mu0 {mean_mu0} vs analytic {rho}"
    );
    assert_eq!(ordered, reps);
}

// ---------------------------------------------------------------------------
// Cronbach alpha + Feldt (1965) CI tests.
//
// Fixture literals from an independent NumPy+scipy replication
// (feldt_fixture.py; scipy.stats.f.ppf), pinned at 1e-9. Every assert reads
// crate outputs (cronbach_alpha / feldt_alpha_ci return values).
//
// Mutation kills verified by hand (see PR evidence):
//   M1 swap delta/2 <-> 1-delta/2 in feldt_alpha_ci   -> fixture lower/upper FAIL
//   M2 flip z orientation in f_cdf (d2/(d1x+d2))      -> fixture FAIL
//   M3 df2 = n-1 instead of (n-1)(p-1)                -> fixtures A/B FAIL
//       (p=2 fixture passes under M3: (n-1)(p-1) == n-1 there by identity)
//   M4 tr/sum inversion in cronbach_alpha             -> fixture FAIL
// Equivalent mutant (survives, disclosed): dropping the symmetry branch in
// inc_beta ("if true") still converges within 300 CF iterations at these dfs;
// the branch is convergence acceleration, not correctness, for this domain.
// Known limit: bisection iteration-count mutations (200 -> 50) survive at
// 1e-9 (2^-50 interval still beats the tolerance); the scipy literals are the
// discriminating anchor for everything coarser.
// ---------------------------------------------------------------------------

const ATOL: f64 = 1e-9;

#[test]
fn alpha_fixture_a_unequal_variances() {
    let d = gen_data(
        30,
        6,
        42,
        &[0.9, 0.8, 0.7, 0.6, 0.5, 0.2],
        &[10.0, -3.0, 5.0, 0.5, 100.0, 7.0],
        &[1.0, 2.0, 0.5, 3.0, 10.0, 1.5],
    );
    let a = cronbach_alpha(&d, 30, 6).unwrap();
    assert!((a - 0.26300193786625514).abs() < ATOL, "alpha {a}");
    let ci = feldt_alpha_ci(a, 30, 6, 0.95).unwrap();
    assert!(
        (ci.lower - -0.23710034474579156).abs() < ATOL,
        "lower {}",
        ci.lower
    );
    assert!(
        (ci.upper - 0.6065060295943752).abs() < ATOL,
        "upper {}",
        ci.upper
    );
    assert!(
        (ci.r_bar - 0.05613713592263862).abs() < ATOL,
        "r_bar {}",
        ci.r_bar
    );
    assert_eq!(ci.df1, 29.0);
    assert_eq!(ci.df2, 145.0);
    // Narrower level nests strictly inside (kills tail-swap mutations too).
    let ci90 = feldt_alpha_ci(a, 30, 6, 0.90).unwrap();
    assert!(
        (ci90.lower - -0.13926063775356812).abs() < ATOL,
        "lower90 {}",
        ci90.lower
    );
    assert!(
        (ci90.upper - 0.563407303756001).abs() < ATOL,
        "upper90 {}",
        ci90.upper
    );
    assert!(ci.lower < ci90.lower && ci90.upper < ci.upper);
    assert!(ci90.lower < a && a < ci90.upper);
}

#[test]
fn alpha_fixture_b() {
    let d = gen_data(
        24,
        5,
        99,
        &[0.7, 0.6, 0.5, 0.4, 0.3],
        &[0.0, 1.0, 2.0, 3.0, 4.0],
        &[1.0, 1.0, 1.0, 1.0, 1.0],
    );
    let a = cronbach_alpha(&d, 24, 5).unwrap();
    assert!((a - 0.3580775296654029).abs() < ATOL, "alpha {a}");
    let ci = feldt_alpha_ci(a, 24, 5, 0.95).unwrap();
    assert!(
        (ci.lower - -0.16244546058178866).abs() < ATOL,
        "lower {}",
        ci.lower
    );
    assert!(
        (ci.upper - 0.6888373608056122).abs() < ATOL,
        "upper {}",
        ci.upper
    );
    assert!(
        (ci.r_bar - 0.10036677558170307).abs() < ATOL,
        "r_bar {}",
        ci.r_bar
    );
}

#[test]
fn alpha_fixture_negative_p2() {
    // Anti-correlated pair -> negative alpha; p=2 boundary; CI must not clamp.
    let mut d = gen_data(20, 2, 7, &[0.8, 0.8], &[0.0, 0.0], &[1.0, 1.0]);
    for row in d.chunks_exact_mut(2) {
        row[1] = -row[1];
    }
    let a = cronbach_alpha(&d, 20, 2).unwrap();
    assert!((a - -1.2239392688014856).abs() < ATOL, "alpha {a}");
    let ci = feldt_alpha_ci(a, 20, 2, 0.95).unwrap();
    assert!(
        (ci.lower - -4.618673441887094).abs() < ATOL,
        "lower {}",
        ci.lower
    );
    assert!(
        (ci.upper - 0.11973779532270723).abs() < ATOL,
        "upper {}",
        ci.upper
    );
    assert!(
        (ci.r_bar - -0.3796409196183434).abs() < ATOL,
        "r_bar {}",
        ci.r_bar
    );
    assert_eq!(ci.df2, 19.0);
}

#[test]
fn alpha_zscored_equals_lambda3() {
    // Covariance of z-scored columns is the correlation matrix, so alpha on
    // z-scores must match guttman lambda3 on the raw data (tolerance 1e-10,
    // not exact: means/sds are recomputed in floating point).
    let d = gen_data(
        30,
        6,
        42,
        &[0.9, 0.8, 0.7, 0.6, 0.5, 0.2],
        &[10.0, -3.0, 5.0, 0.5, 100.0, 7.0],
        &[1.0, 2.0, 0.5, 3.0, 10.0, 1.5],
    );
    let g = guttman_lambdas(&d, 30, 6, 15000, 1).unwrap();
    let (n, p) = (30usize, 6usize);
    let mut z = d.clone();
    for j in 0..p {
        let mean = (0..n).map(|i| d[i * p + j]).sum::<f64>() / n as f64;
        let var = (0..n).map(|i| (d[i * p + j] - mean).powi(2)).sum::<f64>() / (n as f64 - 1.0);
        let sd = var.sqrt();
        for i in 0..n {
            z[i * p + j] = (d[i * p + j] - mean) / sd;
        }
    }
    let a = cronbach_alpha(&z, n, p).unwrap();
    assert!(
        (a - g.lambda3).abs() < 1e-10,
        "alpha {a} vs lambda3 {}",
        g.lambda3
    );
}

#[test]
fn feldt_ci_extreme_level_endpoints() {
    // Regression (impl-review D1): level so close to 1 that the quantile
    // probability rounds to 1.0 must give an infinite bound (as qf/scipy),
    // not a finite bisection cap. Asserts read crate outputs.
    let level = 1.0 - f64::EPSILON / 2.0; // nextdown(1.0), passes level < 1
    let ci = feldt_alpha_ci(0.8, 30, 6, level).unwrap();
    assert_eq!(ci.lower, f64::NEG_INFINITY, "lower {}", ci.lower);
    // delta/2 is tiny but nonzero, so the upper bound is finite and < 1.
    assert!(ci.upper.is_finite() && ci.upper < 1.0, "upper {}", ci.upper);
}

#[test]
fn alpha_rejections() {
    let d = gen_data(
        10,
        3,
        5,
        &[0.5, 0.5, 0.5],
        &[0.0, 0.0, 0.0],
        &[1.0, 1.0, 1.0],
    );
    assert!(cronbach_alpha(&d[..6], 2, 3).is_err());
    assert!(cronbach_alpha(&d[..10], 5, 2).is_ok());
    assert!(cronbach_alpha(&d, 10, 4).is_err()); // length mismatch
    let mut bad = d.clone();
    bad[0] = f64::NAN;
    assert!(cronbach_alpha(&bad, 10, 3).is_err());
    let mut flat = d.clone();
    for row in flat.chunks_exact_mut(3) {
        row[0] = 1.0; // zero-variance item
    }
    assert!(cronbach_alpha(&flat, 10, 3).is_err());
    assert!(feldt_alpha_ci(1.0, 30, 6, 0.95).is_err());
    assert!(feldt_alpha_ci(f64::NAN, 30, 6, 0.95).is_err());
    assert!(feldt_alpha_ci(0.8, 2, 6, 0.95).is_err());
    assert!(feldt_alpha_ci(0.8, 30, 1, 0.95).is_err());
    assert!(feldt_alpha_ci(0.8, 30, 6, 0.0).is_err());
    assert!(feldt_alpha_ci(0.8, 30, 6, 1.0).is_err());
}

#[test]
#[ignore = "monte carlo: 500 reps"]
fn alpha_feldt_ci_coverage_mc() {
    // Tau-equivalent model: p=8, loading 0.7, scale 1 -> true reliability of
    // the sum score rho = 31.36/39.36 (see guttman MC derivation). Empirical
    // 95% CI coverage over 500 reps should land in [0.925, 0.975]; every rep
    // reads crate outputs.
    let rho = 31.36 / 39.36;
    let reps: u64 = 500;
    let mut covered = 0;
    for r in 0..reps {
        let d = gen_data(300, 8, 1000 + r, &[0.7; 8], &[0.0; 8], &[1.0; 8]);
        let a = cronbach_alpha(&d, 300, 8).unwrap();
        let ci = feldt_alpha_ci(a, 300, 8, 0.95).unwrap();
        if ci.lower <= rho && rho <= ci.upper {
            covered += 1;
        }
    }
    let cov = covered as f64 / reps as f64;
    assert!((0.925..=0.975).contains(&cov), "coverage {cov}");
}
