//! Tests for Guttman lambda reliability (`crate::reliability`).
//!
//! Fixture literals come from an INDEPENDENT NumPy replication
//! (session files/guttman_fixture.py): np.corrcoef + np.linalg.inv +
//! itertools.combinations, with data generated by a NumPy mirror of the
//! crate LCG (np.uint64). Every assert reads a `GuttmanResult` field
//! returned by `guttman_lambdas` — no test-local recomputation of any
//! lambda.
//!
//! Mutation kills verified by hand-editing the implementation (each FAILED,
//! then was restored):
//! - M1 drop `.abs()` in `split_rb` -> fixture A/B lambda4/beta/mean_split.
//! - M2 drop the `p/(p-1)` factor inside lambda2's sqrt -> lambda2 pins.
//! - M3 lambda5 uses the SUM of `C_j` instead of the max -> lambda5 pins.
//! - M4 drop the SMC clamp / use `1/diag` without `1 -` -> lambda6 pins.
//! - M5 break the combination stepper (skip last combination) -> n_splits
//!   pin (exhaustive counts are exact binomials).
//!
//! Known identity limit (disclosed): `lambda3 = p/(p-1) * lambda1` is exact
//! algebra, so a mutation rescaling BOTH consistently cannot be caught by
//! any data fixture; the discriminating anchor is that lambda1 and lambda3
//! are pinned to independent NumPy literals, so only jointly consistent
//! mutations survive. Likewise `Vt = sum(R)` equals the per-split collapsed
//! total for every partition, so substituting one for the other is
//! mathematically identical and unkillable.
use super::*;

const TOL: f64 = 1e-9;

/// NumPy-mirrored LCG data generator (fixture input construction only; the
/// code under test never sees these helpers).
fn gen_data(
    n: usize,
    p: usize,
    seed: u64,
    loadings: &[f64],
    means: &[f64],
    scales: &[f64],
) -> Vec<f64> {
    let mut state = seed.max(1);
    let mut uniform = |state: &mut u64| -> f64 {
        *state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        (*state >> 11) as f64 / (1u64 << 53) as f64
    };
    let mut normal = |state: &mut u64| -> f64 {
        let u1 = uniform(state).max(1e-12);
        let u2 = uniform(state);
        (-2.0 * u1.ln()).sqrt() * (2.0 * std::f64::consts::PI * u2).cos()
    };
    let mut out = vec![0.0_f64; n * p];
    for i in 0..n {
        let f = normal(&mut state);
        for j in 0..p {
            let e = normal(&mut state);
            out[i * p + j] = means[j] + scales[j] * (loadings[j] * f + e);
        }
    }
    out
}

#[test]
fn fixture_a_exhaustive_even_p() {
    let data = gen_data(
        30,
        6,
        42,
        &[0.9, 0.8, 0.7, 0.6, 0.5, 0.2],
        &[10.0, -3.0, 5.0, 0.5, 100.0, 7.0],
        &[1.0, 2.0, 0.5, 3.0, 10.0, 1.5],
    );
    let g = guttman_lambdas(&data, 30, 6, 15000, 1).expect("fixture A");
    assert!((g.lambda1 - 0.41068157604336863).abs() < TOL);
    assert!((g.lambda2 - 0.5561900258418755).abs() < TOL);
    assert!((g.lambda3 - 0.49281789125204234).abs() < TOL);
    assert!((g.lambda4 - 0.6842463861953535).abs() < TOL);
    assert!((g.lambda5 - 0.5602004712206824).abs() < TOL);
    assert!((g.lambda6 - 0.59150154331973).abs() < TOL);
    assert!((g.beta - 0.1784553694910821).abs() < TOL);
    assert!((g.mean_split - 0.4928178912520423).abs() < TOL);
    assert_eq!(g.n_splits, 20); // C(6, 3)
    assert!(g.exhaustive);
}

#[test]
fn fixture_b_exhaustive_odd_p() {
    let data = gen_data(
        24,
        5,
        99,
        &[0.8, 0.7, 0.6, 0.5, 0.4],
        &[1.0, 2.0, 3.0, 4.0, 5.0],
        &[1.0, 1.0, 2.0, 1.0, 0.5],
    );
    let g = guttman_lambdas(&data, 24, 5, 15000, 1).expect("fixture B");
    assert!((g.lambda1 - 0.36304984346951963).abs() < TOL);
    assert!((g.lambda2 - 0.5427967072982294).abs() < TOL);
    assert!((g.lambda3 - 0.45381230433689956).abs() < TOL);
    assert!((g.lambda4 - 0.6863584325671727).abs() < TOL);
    assert!((g.lambda5 - 0.5668547649655623).abs() < TOL);
    assert!((g.lambda6 - 0.5667118066898096).abs() < TOL);
    assert!((g.beta - 0.04899616716352421).abs() < TOL);
    assert!((g.mean_split - 0.44545904559612853).abs() < TOL);
    assert_eq!(g.n_splits, 10); // C(5, 2): m = floor(5/2), A size 2 vs B size 3
    assert!(g.exhaustive);
}

#[test]
fn fixture_c_sampled_branch() {
    let mut loadings = vec![0.7_f64; 10];
    loadings.extend(vec![0.4_f64; 10]);
    let data = gen_data(60, 20, 7, &loadings, &[0.0; 20], &[1.0; 20]);
    let g = guttman_lambdas(&data, 60, 20, 200, 7).expect("fixture C");
    assert!((g.lambda1 - 0.8173350703037762).abs() < TOL);
    assert!((g.lambda2 - 0.8657986449939672).abs() < TOL);
    assert!((g.lambda3 - 0.8603527055829222).abs() < TOL);
    assert!((g.lambda4 - 0.921571734274876).abs() < TOL);
    assert!((g.lambda5 - 0.8439917779688363).abs() < TOL);
    assert!((g.lambda6 - 0.8931192541579849).abs() < TOL);
    assert!((g.beta - 0.7974800893409002).abs() < TOL);
    assert!((g.mean_split - 0.8623803334548827).abs() < TOL);
    assert_eq!(g.n_splits, 200);
    assert!(!g.exhaustive);
}

#[test]
fn rejections() {
    let ok = gen_data(10, 4, 3, &[0.5; 4], &[0.0; 4], &[1.0; 4]);
    assert!(guttman_lambdas(&ok, 2, 4, 100, 1).is_err()); // wrong length too
    assert!(guttman_lambdas(&ok[..8], 2, 4, 100, 1).is_err()); // n < 3
    assert!(guttman_lambdas(&ok[..20], 10, 2, 100, 1).is_err()); // p < 3
    assert!(guttman_lambdas(&ok, 10, 4, 0, 1).is_err()); // budget 0
    let mut nan = ok.clone();
    nan[5] = f64::NAN;
    assert!(guttman_lambdas(&nan, 10, 4, 100, 1).is_err());
    let mut constant = ok.clone();
    for i in 0..10 {
        constant[i * 4] = 2.5;
    }
    assert!(guttman_lambdas(&constant, 10, 4, 100, 1).is_err()); // zero variance
}

#[test]
fn singular_correlation_errs_for_lambda6() {
    // Duplicate columns: correlation_matrix succeeds (r = 1) but R is
    // exactly singular, so the SMC inverse must Err (divergence 4: psych
    // would silently Pinv; we refuse). Assert reads the crate Result.
    let base = gen_data(15, 1, 11, &[0.6], &[0.0], &[1.0]);
    let mut data = vec![0.0_f64; 15 * 3];
    for i in 0..15 {
        data[i * 3] = base[i];
        data[i * 3 + 1] = base[i]; // exact duplicate
        data[i * 3 + 2] = (i as f64).sin() + base[i];
    }
    let err = guttman_lambdas(&data, 15, 3, 100, 1).unwrap_err();
    assert!(err.contains("singular"), "unexpected error: {err}");
}

/// >= 500-replication Monte Carlo: tau-equivalent items (equal loadings,
/// equal noise), where coefficient alpha ( = lambda3) is consistent for the
/// true reliability rho = p*l^2 / (p*l^2 + p*s^2) of the unit-weighted sum
/// score under the one-factor model. With l = 0.7, s = 1, p = 8:
/// rho = 8*0.49 / (8*0.49 + 8) ... per-item communality basis; the sum-score
/// reliability is rho_sum = (p^2 l^2 sigma_f^2) / (p^2 l^2 sigma_f^2 +
/// p s^2) = (64*0.49)/(64*0.49 + 8) = 0.796696. Asserts read only crate
/// outputs (mean of returned lambda3 across reps).
#[test]
#[ignore]
fn mc_tau_equivalent_alpha_recovery() {
    let p = 8;
    let reps = 500;
    let mut sum_l3 = 0.0_f64;
    let mut ge = 0usize;
    for rep in 0..reps {
        let data = gen_data(
            300,
            p,
            1000 + rep as u64,
            &vec![0.7; p],
            &vec![0.0; p],
            &vec![1.0; p],
        );
        let g = guttman_lambdas(&data, 300, p, 500, 17).expect("mc rep");
        sum_l3 += g.lambda3;
        if g.lambda2 >= g.lambda3 - 1e-12 {
            ge += 1;
        }
    }
    let mean_l3 = sum_l3 / reps as f64;
    let rho = (64.0 * 0.49) / (64.0 * 0.49 + 8.0); // 0.796696...
    assert!(
        (mean_l3 - rho).abs() < 0.01,
        "mean lambda3 {mean_l3} vs analytic {rho}"
    );
    // Secondary (identity-adjacent, disclosed): Guttman's lambda2 >= lambda3
    // holds sample-wise; violations flag algebra mutations.
    assert_eq!(ge, reps);
}

// --- ten Berge & Zegers mu coefficients -------------------------------
//
// Fixture literals from an independent NumPy replication of tenberge.R
// (session files/tenberge_fixture.py: np.corrcoef + explicit off-diagonal
// power sums). Every assert reads TenBergeResult fields from the crate.
//
// Mutation kills verified by hand (each FAILED, then restored):
// - M1 drop the innermost `c` factor in mu2/mu3 -> mu2/mu3 pins (~5e-4
//   shift; tolerance 1e-9 kills it).
// - M2 use s2 where s4 belongs in mu2 -> mu2 pin.
// - M3 flatten one sqrt nesting level in mu3 -> mu3 pin.
//
// Disclosed identities: mu0 == guttman lambda3 and mu1 == guttman lambda2
// by exact algebra; both are pinned to independent NumPy literals (not to
// each other), so only jointly consistent mutations survive. S_2 over all
// cells vs 2x the upper triangle is identical for symmetric R; unkillable.

#[test]
fn tenberge_fixture_a() {
    let data = gen_data(
        30,
        6,
        42,
        &[0.9, 0.8, 0.7, 0.6, 0.5, 0.2],
        &[10.0, -3.0, 5.0, 0.5, 100.0, 7.0],
        &[1.0, 2.0, 0.5, 3.0, 10.0, 1.5],
    );
    let t = tenberge_mu(&data, 30, 6).expect("tenberge A");
    assert!((t.mu0 - 0.49281789125204223).abs() < TOL);
    assert!((t.mu1 - 0.5561900258418755).abs() < TOL);
    assert!((t.mu2 - 0.566334883191414).abs() < TOL);
    assert!((t.mu3 - 0.5694865282091219).abs() < TOL);
    // Cauchy-Schwarz series ordering, read from crate outputs.
    assert!(t.mu0 <= t.mu1 && t.mu1 <= t.mu2 && t.mu2 <= t.mu3);
}

#[test]
fn tenberge_fixture_b() {
    let data = gen_data(
        24,
        5,
        99,
        &[0.8, 0.7, 0.6, 0.5, 0.4],
        &[1.0, 2.0, 3.0, 4.0, 5.0],
        &[1.0, 1.0, 2.0, 1.0, 0.5],
    );
    let t = tenberge_mu(&data, 24, 5).expect("tenberge B");
    assert!((t.mu0 - 0.45381230433689973).abs() < TOL);
    assert!((t.mu1 - 0.5427967072982294).abs() < TOL);
    assert!((t.mu2 - 0.554450883437996).abs() < TOL);
    assert!((t.mu3 - 0.5577786174323536).abs() < TOL);
    assert!(t.mu0 <= t.mu1 && t.mu1 <= t.mu2 && t.mu2 <= t.mu3);
}

#[test]
fn tenberge_matches_guttman_identities() {
    // mu0 == lambda3 and mu1 == lambda2 (exact algebra, both sides crate
    // outputs from independent code paths: direct off-diag sums vs Vt - p).
    let data = gen_data(
        30,
        6,
        42,
        &[0.9, 0.8, 0.7, 0.6, 0.5, 0.2],
        &[10.0, -3.0, 5.0, 0.5, 100.0, 7.0],
        &[1.0, 2.0, 0.5, 3.0, 10.0, 1.5],
    );
    let t = tenberge_mu(&data, 30, 6).expect("mu");
    let g = guttman_lambdas(&data, 30, 6, 15000, 1).expect("lambdas");
    assert!((t.mu0 - g.lambda3).abs() < 1e-12);
    assert!((t.mu1 - g.lambda2).abs() < 1e-12);
}

#[test]
fn tenberge_rejections() {
    let ok = gen_data(10, 4, 3, &[0.5; 4], &[0.0; 4], &[1.0; 4]);
    assert!(tenberge_mu(&ok[..8], 2, 4).is_err()); // n < 3
    assert!(tenberge_mu(&ok[..20], 10, 2).is_err()); // p < 3
    assert!(tenberge_mu(&ok[..30], 10, 4).is_err()); // wrong length
    let mut nan = ok.clone();
    nan[7] = f64::INFINITY;
    assert!(tenberge_mu(&nan, 10, 4).is_err());
    let mut constant = ok.clone();
    for i in 0..10 {
        constant[i * 4 + 2] = -1.0;
    }
    assert!(tenberge_mu(&constant, 10, 4).is_err()); // zero variance
}

/// >= 500-replication Monte Carlo: same tau-equivalent design as the
/// Guttman MC. mu0 == alpha is consistent (asymptotically unbiased) for
/// rho_sum = (p^2 l^2)/(p^2 l^2 + p s^2) = 31.36/39.36 with l=0.7, s=1,
/// p=8, n=300. Also asserts the series ordering sample-wise on crate
/// outputs across all reps.
#[test]
#[ignore]
fn mc_tenberge_alpha_recovery_and_ordering() {
    let p = 8;
    let reps = 500;
    let mut sum_mu0 = 0.0_f64;
    let mut ordered = 0usize;
    for rep in 0..reps {
        let data = gen_data(
            300,
            p,
            2000 + rep as u64,
            &vec![0.7; p],
            &vec![0.0; p],
            &vec![1.0; p],
        );
        let t = tenberge_mu(&data, 300, p).expect("mc rep");
        sum_mu0 += t.mu0;
        if t.mu0 <= t.mu1 && t.mu1 <= t.mu2 && t.mu2 <= t.mu3 {
            ordered += 1;
        }
    }
    let mean_mu0 = sum_mu0 / reps as f64;
    let rho = (64.0 * 0.49) / (64.0 * 0.49 + 8.0);
    assert!(
        (mean_mu0 - rho).abs() < 0.01,
        "mean mu0 {mean_mu0} vs analytic {rho}"
    );
    assert_eq!(ordered, reps);
}

// ---------------------------------------------------------------------------
// Cronbach alpha + Feldt (1965) CI tests.
//
// Fixture literals from an independent NumPy+scipy replication
// (feldt_fixture.py; scipy.stats.f.ppf), pinned at 1e-9. Every assert reads
// crate outputs (cronbach_alpha / feldt_alpha_ci return values).
//
// Mutation kills verified by hand (see PR evidence):
//   M1 swap delta/2 <-> 1-delta/2 in feldt_alpha_ci   -> fixture lower/upper FAIL
//   M2 flip z orientation in f_cdf (d2/(d1x+d2))      -> fixture FAIL
//   M3 df2 = n-1 instead of (n-1)(p-1)                -> fixtures A/B FAIL
//       (p=2 fixture passes under M3: (n-1)(p-1) == n-1 there by identity)
//   M4 tr/sum inversion in cronbach_alpha             -> fixture FAIL
// Equivalent mutant (survives, disclosed): dropping the symmetry branch in
// inc_beta ("if true") still converges within 300 CF iterations at these dfs;
// the branch is convergence acceleration, not correctness, for this domain.
// Known limit: bisection iteration-count mutations (200 -> 50) survive at
// 1e-9 (2^-50 interval still beats the tolerance); the scipy literals are the
// discriminating anchor for everything coarser.
// ---------------------------------------------------------------------------

const ATOL: f64 = 1e-9;

#[test]
fn alpha_fixture_a_unequal_variances() {
    let d = gen_data(
        30,
        6,
        42,
        &[0.9, 0.8, 0.7, 0.6, 0.5, 0.2],
        &[10.0, -3.0, 5.0, 0.5, 100.0, 7.0],
        &[1.0, 2.0, 0.5, 3.0, 10.0, 1.5],
    );
    let a = cronbach_alpha(&d, 30, 6).unwrap();
    assert!((a - 0.26300193786625514).abs() < ATOL, "alpha {a}");
    let ci = feldt_alpha_ci(a, 30, 6, 0.95).unwrap();
    assert!(
        (ci.lower - -0.23710034474579156).abs() < ATOL,
        "lower {}",
        ci.lower
    );
    assert!(
        (ci.upper - 0.6065060295943752).abs() < ATOL,
        "upper {}",
        ci.upper
    );
    assert!(
        (ci.r_bar - 0.05613713592263862).abs() < ATOL,
        "r_bar {}",
        ci.r_bar
    );
    assert_eq!(ci.df1, 29.0);
    assert_eq!(ci.df2, 145.0);
    // Narrower level nests strictly inside (kills tail-swap mutations too).
    let ci90 = feldt_alpha_ci(a, 30, 6, 0.90).unwrap();
    assert!(
        (ci90.lower - -0.13926063775356812).abs() < ATOL,
        "lower90 {}",
        ci90.lower
    );
    assert!(
        (ci90.upper - 0.563407303756001).abs() < ATOL,
        "upper90 {}",
        ci90.upper
    );
    assert!(ci.lower < ci90.lower && ci90.upper < ci.upper);
    assert!(ci90.lower < a && a < ci90.upper);
}

#[test]
fn alpha_fixture_b() {
    let d = gen_data(
        24,
        5,
        99,
        &[0.7, 0.6, 0.5, 0.4, 0.3],
        &[0.0, 1.0, 2.0, 3.0, 4.0],
        &[1.0, 1.0, 1.0, 1.0, 1.0],
    );
    let a = cronbach_alpha(&d, 24, 5).unwrap();
    assert!((a - 0.3580775296654029).abs() < ATOL, "alpha {a}");
    let ci = feldt_alpha_ci(a, 24, 5, 0.95).unwrap();
    assert!(
        (ci.lower - -0.16244546058178866).abs() < ATOL,
        "lower {}",
        ci.lower
    );
    assert!(
        (ci.upper - 0.6888373608056122).abs() < ATOL,
        "upper {}",
        ci.upper
    );
    assert!(
        (ci.r_bar - 0.10036677558170307).abs() < ATOL,
        "r_bar {}",
        ci.r_bar
    );
}

#[test]
fn alpha_fixture_negative_p2() {
    // Anti-correlated pair -> negative alpha; p=2 boundary; CI must not clamp.
    let mut d = gen_data(20, 2, 7, &[0.8, 0.8], &[0.0, 0.0], &[1.0, 1.0]);
    for row in d.chunks_exact_mut(2) {
        row[1] = -row[1];
    }
    let a = cronbach_alpha(&d, 20, 2).unwrap();
    assert!((a - -1.2239392688014856).abs() < ATOL, "alpha {a}");
    let ci = feldt_alpha_ci(a, 20, 2, 0.95).unwrap();
    assert!(
        (ci.lower - -4.618673441887094).abs() < ATOL,
        "lower {}",
        ci.lower
    );
    assert!(
        (ci.upper - 0.11973779532270723).abs() < ATOL,
        "upper {}",
        ci.upper
    );
    assert!(
        (ci.r_bar - -0.3796409196183434).abs() < ATOL,
        "r_bar {}",
        ci.r_bar
    );
    assert_eq!(ci.df2, 19.0);
}

#[test]
fn alpha_zscored_equals_lambda3() {
    // Covariance of z-scored columns is the correlation matrix, so alpha on
    // z-scores must match guttman lambda3 on the raw data (tolerance 1e-10,
    // not exact: means/sds are recomputed in floating point).
    let d = gen_data(
        30,
        6,
        42,
        &[0.9, 0.8, 0.7, 0.6, 0.5, 0.2],
        &[10.0, -3.0, 5.0, 0.5, 100.0, 7.0],
        &[1.0, 2.0, 0.5, 3.0, 10.0, 1.5],
    );
    let g = guttman_lambdas(&d, 30, 6, 15000, 1).unwrap();
    let (n, p) = (30usize, 6usize);
    let mut z = d.clone();
    for j in 0..p {
        let mean = (0..n).map(|i| d[i * p + j]).sum::<f64>() / n as f64;
        let var = (0..n).map(|i| (d[i * p + j] - mean).powi(2)).sum::<f64>() / (n as f64 - 1.0);
        let sd = var.sqrt();
        for i in 0..n {
            z[i * p + j] = (d[i * p + j] - mean) / sd;
        }
    }
    let a = cronbach_alpha(&z, n, p).unwrap();
    assert!(
        (a - g.lambda3).abs() < 1e-10,
        "alpha {a} vs lambda3 {}",
        g.lambda3
    );
}

#[test]
fn feldt_ci_extreme_level_endpoints() {
    // Regression (impl-review D1): level so close to 1 that the quantile
    // probability rounds to 1.0 must give an infinite bound (as qf/scipy),
    // not a finite bisection cap. Asserts read crate outputs.
    let level = 1.0 - f64::EPSILON / 2.0; // nextdown(1.0), passes level < 1
    let ci = feldt_alpha_ci(0.8, 30, 6, level).unwrap();
    assert_eq!(ci.lower, f64::NEG_INFINITY, "lower {}", ci.lower);
    // delta/2 is tiny but nonzero, so the upper bound is finite and < 1.
    assert!(ci.upper.is_finite() && ci.upper < 1.0, "upper {}", ci.upper);
}

#[test]
fn alpha_rejections() {
    let d = gen_data(
        10,
        3,
        5,
        &[0.5, 0.5, 0.5],
        &[0.0, 0.0, 0.0],
        &[1.0, 1.0, 1.0],
    );
    assert!(cronbach_alpha(&d[..6], 2, 3).is_err());
    assert!(cronbach_alpha(&d[..10], 5, 2).is_ok());
    assert!(cronbach_alpha(&d, 10, 4).is_err()); // length mismatch
    let mut bad = d.clone();
    bad[0] = f64::NAN;
    assert!(cronbach_alpha(&bad, 10, 3).is_err());
    let mut flat = d.clone();
    for row in flat.chunks_exact_mut(3) {
        row[0] = 1.0; // zero-variance item
    }
    assert!(cronbach_alpha(&flat, 10, 3).is_err());
    assert!(feldt_alpha_ci(1.0, 30, 6, 0.95).is_err());
    assert!(feldt_alpha_ci(f64::NAN, 30, 6, 0.95).is_err());
    assert!(feldt_alpha_ci(0.8, 2, 6, 0.95).is_err());
    assert!(feldt_alpha_ci(0.8, 30, 1, 0.95).is_err());
    assert!(feldt_alpha_ci(0.8, 30, 6, 0.0).is_err());
    assert!(feldt_alpha_ci(0.8, 30, 6, 1.0).is_err());
}

#[test]
#[ignore = "monte carlo: 500 reps"]
fn alpha_feldt_ci_coverage_mc() {
    // Tau-equivalent model: p=8, loading 0.7, scale 1 -> true reliability of
    // the sum score rho = 31.36/39.36 (see guttman MC derivation). Empirical
    // 95% CI coverage over 500 reps should land in [0.925, 0.975]; every rep
    // reads crate outputs.
    let rho = 31.36 / 39.36;
    let reps: u64 = 500;
    let mut covered = 0;
    for r in 0..reps {
        let d = gen_data(300, 8, 1000 + r, &[0.7; 8], &[0.0; 8], &[1.0; 8]);
        let a = cronbach_alpha(&d, 300, 8).unwrap();
        let ci = feldt_alpha_ci(a, 300, 8, 0.95).unwrap();
        if ci.lower <= rho && rho <= ci.upper {
            covered += 1;
        }
    }
    let cov = covered as f64 / reps as f64;
    assert!((0.925..=0.975).contains(&cov), "coverage {cov}");
}

// ---------------------------------------------------------------------------
// separation_reliability (eRm SepRel transcription + hand-derived G)
//
// Mutation-kill audit (all asserts read crate outputs):
// - M1 EXECUTED: swap numerator to (mse - ssd) => fixture sep_rel FAILs.
// - M2 EXECUTED: population variance (n denominator) => ssd + sep_rel FAIL.
// - M3 EXECUTED: drop the square on se in mse => mse + sep_rel FAIL.
// - Disclosed non-discriminating identity: G^2 = R/(1-R) holds for ANY
//   shared (ssd, mse), so it cannot catch shared-formula bugs; the pinned
//   numpy fixture values (ssd, mse, R, G all asserted) are the anchors.

/// Pinned numpy oracle (ddof=1 var; mean se^2), 12 decimals.
/// Asserts read: crate ssd, mse, sep_rel, sep_index.
#[test]
fn seprel_numpy_oracle_fixture() {
    let x = [-1.8, -0.6, 0.15, 0.9, 2.1, -0.35, 1.4];
    let se = [0.45, 0.38, 0.35, 0.37, 0.52, 0.36, 0.41];
    let r = separation_reliability(&x, &se).unwrap();
    assert!((r.ssd - 1.743690476190).abs() < 1e-10, "ssd = {}", r.ssd);
    assert!((r.mse - 0.167771428571).abs() < 1e-10, "mse = {}", r.mse);
    assert!(
        (r.sep_rel - 0.903783709975).abs() < 1e-10,
        "sep_rel = {}",
        r.sep_rel
    );
    assert!(
        (r.sep_index - 3.064841016127).abs() < 1e-10,
        "sep_index = {}",
        r.sep_index
    );
}

/// Negative-reliability path (mse > ssd): sep_rel negative and unclamped
/// (eRm does not clamp), G NaN. Asserts read crate outputs.
#[test]
fn seprel_negative_unclamped_and_g_nan() {
    let x = [0.0, 0.1, -0.1, 0.05];
    let se = [1.0, 1.0, 1.0, 1.0];
    let r = separation_reliability(&x, &se).unwrap();
    assert!(r.sep_rel < 0.0, "sep_rel = {}", r.sep_rel);
    assert!(r.sep_index.is_nan());
    // Degenerate ssd = 0 -> sep_rel NaN (documented crate guard).
    let r0 = separation_reliability(&[1.5, 1.5, 1.5], &[0.2, 0.2, 0.2]).unwrap();
    assert!(r0.sep_rel.is_nan());
}

/// Error contract. Asserts read crate Err values.
#[test]
fn seprel_error_paths() {
    assert!(separation_reliability(&[1.0], &[0.1]).is_err());
    assert!(separation_reliability(&[1.0, 2.0], &[0.1]).is_err());
    assert!(separation_reliability(&[1.0, f64::NAN], &[0.1, 0.1]).is_err());
    assert!(separation_reliability(&[1.0, 2.0], &[0.1, -0.1]).is_err());
    assert!(separation_reliability(&[1.0, 2.0], &[0.1, f64::INFINITY]).is_err());
}

/// 500-rep MC (spec rev 2 design): x = theta + N(0, se) noise with
/// theta ~ N(0, 1), constant se = 0.5, n = 1000 per rep. Population
/// R = 1 / (1 + 0.25) = 0.8. Asserts read crate sep_rel across reps.
#[test]
#[ignore]
fn seprel_mc_recovery_500() {
    let mut state: u64 = 0x9E3779B97F4A7C15;
    let mut next_u = || {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        ((state >> 11) as f64) / ((1u64 << 53) as f64)
    };
    let mut next_normal = || {
        let (u1, u2): (f64, f64) = (next_u().max(1e-12), next_u());
        (-2.0 * u1.ln()).sqrt() * (2.0 * std::f64::consts::PI * u2).cos()
    };
    let n = 1000usize;
    let se_true = 0.5f64;
    let reps = 500;
    let mut sum_r = 0.0;
    for _ in 0..reps {
        let x: Vec<f64> = (0..n)
            .map(|_| next_normal() + se_true * next_normal())
            .collect();
        let se = vec![se_true; n];
        sum_r += separation_reliability(&x, &se).unwrap().sep_rel;
    }
    let mean_r = sum_r / reps as f64;
    let pop_r = 1.0 / (1.0 + se_true * se_true);
    assert!(
        (mean_r - pop_r).abs() < 0.01,
        "mean sep_rel = {mean_r} vs population {pop_r}"
    );
}

/// Impl-review regression: finite-but-huge inputs must Err, not leak
/// non-finite ssd/mse. Asserts read crate Err values.
#[test]
fn seprel_overflow_guard() {
    assert!(separation_reliability(&[1e308, 1e308], &[0.1, 0.1]).is_err());
    assert!(separation_reliability(&[0.0, 1.0], &[1e200, 1e200]).is_err());
}

// ===================== icc (Shrout-Fleiss family) =========================
// Pins from the exact-Fraction oracle (session files/icc_oracle.py,
// EXECUTED; scipy F dist for qf/pf), transcribed from CRAN irr 0.85
// R/icc.R. Every assert reads IccResult fields returned by `icc`.
//
// Mutation kills verified by editing the implementation (each FAILED, then
// restored):
// - MU1 MSw normalized by /nr instead of /ns -> ic_anchor_i1 o_s coeff.
// - MU2 FU quantile df order swapped -> ic_anchor_i1 o_s ubound.
// - MU3 agreement-single denominator drops (nr/ns)(MSc-MSe) ->
//   ic_anchor_i1 a_s coeff (would collapse to the consistency 920/1287).
// - MU4 r0 ignored in the F statistic -> ic_r0_i3 fvalue pins.
// - MU5 column-major stride bug -> ic_asym_i2 coeff pins.
// - MU6 CI Satterthwaite uses r0 instead of the coefficient plug-in ->
//   ic_anchor_i1 a_s lbound/ubound.

fn icc_rel(a: f64, b: f64, tol: f64) -> bool {
    (a - b).abs() <= tol * b.abs().max(1.0)
}

fn sf_table2() -> Vec<f64> {
    vec![
        9.0, 2.0, 5.0, 8.0, //
        6.0, 1.0, 3.0, 2.0, //
        8.0, 4.0, 6.0, 8.0, //
        7.0, 1.0, 2.0, 6.0, //
        10.0, 5.0, 6.0, 9.0, //
        6.0, 2.0, 4.0, 7.0,
    ]
}

fn icc_all6(data: &[f64], ns: usize, nr: usize, r0: f64, conf: f64) -> Vec<IccResult> {
    [
        ("oneway", "consistency", "single"),
        ("twoway", "consistency", "single"),
        ("twoway", "agreement", "single"),
        ("oneway", "consistency", "average"),
        ("twoway", "consistency", "average"),
        ("twoway", "agreement", "average"),
    ]
    .iter()
    .map(|(m, t, u)| icc(data, ns, nr, m, t, u, r0, conf).unwrap())
    .collect()
}

/// I1: Shrout-Fleiss (1979) Table 2, all six variants (r0=0, conf=.95).
/// Kills MU1 (o_s coeff), MU2 (o_s ubound), MU3 (a_s coeff), MU6 (a_s CI).
#[test]
fn ic_anchor_i1_sf_all_six() {
    let r = icc_all6(&sf_table2(), 6, 4, 0.0, 0.95);
    let coeffs = [
        448.0 / 2703.0,
        920.0 / 1287.0,
        184.0 / 635.0,
        1792.0 / 4047.0,
        3680.0 / 4047.0,
        736.0 / 1187.0,
    ];
    for (res, want) in r.iter().zip(coeffs) {
        assert!(icc_rel(res.value, want, 1e-12), "{} vs {want}", res.value);
        assert_eq!(res.subjects, 6);
        assert_eq!(res.raters, 4);
        assert_eq!(res.df1, 5.0);
    }
    // F/df2/p: oneway pair shares F, twoway quartet shares F at r0=0
    // (agreement Satterthwaite v == (ns-1)(nr-1) exactly when r0=0).
    for i in [0usize, 3] {
        assert!(icc_rel(r[i].fvalue, 1.7946784922394678, 1e-12));
        assert_eq!(r[i].df2, 18.0);
        assert!((r[i].p_value - 0.16476880834463953).abs() < 1e-9);
    }
    for i in [1usize, 2, 4, 5] {
        assert!(icc_rel(r[i].fvalue, 11.02724795640327, 1e-12));
        assert!(icc_rel(r[i].df2, 15.0, 1e-12));
        assert!((r[i].p_value - 0.00013456651648433688).abs() < 1e-9);
    }
    let cis = [
        (-0.13293232487475098, 0.722560062328121),
        (0.3424647650339252, 0.9458582599553595),
        (0.018786513374712013, 0.7610843696489528),
        (-0.8844421552381201, 0.9124154203407755),
        (0.6756747138163046, 0.9858916781690623),
        (0.03944017992139112, 0.9285731833771681),
    ];
    for (res, (lb, ub)) in r.iter().zip(cis) {
        assert!(icc_rel(res.lbound, lb, 1e-9), "lb {} vs {lb}", res.lbound);
        assert!(icc_rel(res.ubound, ub, 1e-9), "ub {} vs {ub}", res.ubound);
    }
}

/// I2: asymmetric 4x3 fixture; kills MU5 (stride/transposition bugs).
#[test]
fn ic_asym_i2() {
    let data = vec![1.0, 3.0, 6.0, 2.0, 2.0, 7.0, 4.0, 5.0, 9.0, 3.0, 3.0, 8.0];
    let r = icc_all6(&data, 4, 3, 0.0, 0.95);
    let coeffs = [
        -23.0 / 139.0,
        48.0 / 59.0,
        8.0 / 53.0,
        -23.0 / 31.0,
        144.0 / 155.0,
        8.0 / 23.0,
    ];
    for (res, want) in r.iter().zip(coeffs) {
        assert!(icc_rel(res.value, want, 1e-12), "{} vs {want}", res.value);
    }
    assert!(icc_rel(r[1].fvalue, 14.090909090909092, 1e-12));
    assert_eq!(r[1].df2, 6.0);
    assert!((r[1].p_value - 0.00399953361525563).abs() < 1e-9);
    assert!(icc_rel(r[2].lbound, -0.005333344546176069, 1e-9));
    assert!(icc_rel(r[2].ubound, 0.7496392441094206, 1e-9));
}

/// I3: r0=0.3 changes F/df2/p but not coefficients or CIs. Kills MU4.
#[test]
fn ic_r0_i3() {
    let base = icc_all6(&sf_table2(), 6, 4, 0.0, 0.95);
    let r = icc_all6(&sf_table2(), 6, 4, 0.3, 0.95);
    for (a, b) in r.iter().zip(&base) {
        assert_eq!(a.value, b.value); // coeff bitwise-unaffected by r0
        assert_eq!(a.lbound, b.lbound);
        assert_eq!(a.ubound, b.ubound);
    }
    assert!(icc_rel(r[0].fvalue, 0.6611973392461197, 1e-12));
    assert!((r[0].p_value - 0.6573818056947218).abs() < 1e-9);
    assert!(icc_rel(r[1].fvalue, 4.062670299727521, 1e-12));
    assert!(icc_rel(r[2].fvalue, 0.9561240676364373, 1e-12));
    assert!(icc_rel(r[2].df2, 4.7463353743354775, 1e-12));
    assert!((r[2].p_value - 0.5219672328433673).abs() < 1e-9);
    assert!(icc_rel(r[3].fvalue, 1.2562749445676273, 1e-12));
    assert!(icc_rel(r[4].fvalue, 7.719073569482289, 1e-12));
    assert!(icc_rel(r[5].fvalue, 3.0350332119134347, 1e-12));
    assert!(icc_rel(r[5].df2, 7.136518826153806, 1e-12));
}

/// I4: conf=.80 changes CIs but not F/p. Kills conf-ignored mutants.
#[test]
fn ic_conf_i4() {
    let base = icc_all6(&sf_table2(), 6, 4, 0.0, 0.95);
    let r = icc_all6(&sf_table2(), 6, 4, 0.0, 0.80);
    for (a, b) in r.iter().zip(&base) {
        assert_eq!(a.fvalue, b.fvalue);
        assert_eq!(a.p_value, b.p_value);
    }
    assert!(icc_rel(r[0].lbound, -0.047857465433838266, 1e-9));
    assert!(icc_rel(r[0].ubound, 0.5441024283192402, 1e-9));
    assert!(icc_rel(r[1].lbound, 0.4905340604697688, 1e-9));
    assert!(icc_rel(r[1].ubound, 0.8966577783576283, 1e-9));
    assert!(icc_rel(r[2].lbound, 0.0788459479007961, 1e-9));
    assert!(icc_rel(r[2].ubound, 0.6022571128642371, 1e-9));
    assert!(icc_rel(r[5].lbound, 0.2287806352847549, 1e-9));
    assert!(icc_rel(r[5].ubound, 0.8597203175540028, 1e-9));
}

/// I5: a NaN anywhere in a row drops it listwise; results are bitwise
/// identical to calling with that row removed.
#[test]
fn ic_nan_drop_i5() {
    let mut with_nan = sf_table2();
    with_nan[3 * 4 + 2] = f64::NAN; // poison row 3
    let direct: Vec<f64> = sf_table2()
        .chunks(4)
        .enumerate()
        .filter(|(i, _)| *i != 3)
        .flat_map(|(_, r)| r.to_vec())
        .collect();
    for (m, t, u) in [
        ("oneway", "consistency", "single"),
        ("twoway", "consistency", "single"),
        ("twoway", "agreement", "average"),
    ] {
        let a = icc(&with_nan, 6, 4, m, t, u, 0.0, 0.95).unwrap();
        let b = icc(&direct, 5, 4, m, t, u, 0.0, 0.95).unwrap();
        assert_eq!(a.subjects, 5);
        assert_eq!(a.value.to_bits(), b.value.to_bits());
        assert_eq!(a.fvalue.to_bits(), b.fvalue.to_bits());
        assert_eq!(a.lbound.to_bits(), b.lbound.to_bits());
        assert_eq!(a.ubound.to_bits(), b.ubound.to_bits());
    }
    // Oracle pin for the dropped-row fixture (c_s).
    let c = icc(&direct, 5, 4, "twoway", "consistency", "single", 0.0, 0.95).unwrap();
    assert!(icc_rel(c.value, 329.0 / 459.0, 1e-12));
    assert!(icc_rel(c.fvalue, 11.123076923076923, 1e-12));
    assert_eq!(c.df2, 12.0);
}

/// Every documented error branch. Asserts read crate Err values.
#[test]
fn ic_error_contract() {
    let d = sf_table2();
    let ok = |e: Result<IccResult, String>, frag: &str| {
        let msg = e.unwrap_err();
        assert!(msg.contains(frag), "{msg} lacks {frag}");
    };
    ok(
        icc(&d, 6, 4, "3way", "consistency", "single", 0.0, 0.95),
        "model",
    );
    ok(icc(&d, 6, 4, "twoway", "abs", "single", 0.0, 0.95), "type");
    ok(
        icc(&d, 6, 4, "twoway", "consistency", "med", 0.0, 0.95),
        "unit",
    );
    ok(
        icc(&d, 6, 4, "twoway", "consistency", "single", 1.0, 0.95),
        "r0",
    );
    ok(
        icc(&d, 6, 4, "twoway", "consistency", "single", -0.1, 0.95),
        "r0",
    );
    ok(
        icc(&d, 6, 4, "twoway", "consistency", "single", f64::NAN, 0.95),
        "r0",
    );
    ok(
        icc(&d, 6, 4, "twoway", "consistency", "single", 0.0, 1.0),
        "conf_level",
    );
    ok(
        icc(&d, 6, 4, "twoway", "consistency", "single", 0.0, f64::NAN),
        "conf_level",
    );
    ok(
        icc(&d[..4], 4, 1, "oneway", "consistency", "single", 0.0, 0.95),
        "raters",
    );
    ok(
        icc(&d, 5, 4, "oneway", "consistency", "single", 0.0, 0.95),
        "length",
    );
    ok(
        icc(
            &[f64::INFINITY, 0.0, 1.0, 2.0],
            2,
            2,
            "oneway",
            "consistency",
            "single",
            0.0,
            0.95,
        ),
        "infinit",
    );
    // All-but-one rows dropped -> too few complete rows.
    let mut nan_heavy = sf_table2();
    for i in 0..5 {
        nan_heavy[i * 4] = f64::NAN;
    }
    ok(
        icc(
            &nan_heavy,
            6,
            4,
            "oneway",
            "consistency",
            "single",
            0.0,
            0.95,
        ),
        "complete subject rows",
    );
    // Constant matrix: every mean square is 0 -> degenerate.
    let konst = vec![3.0; 12];
    assert!(icc(&konst, 4, 3, "oneway", "consistency", "single", 0.0, 0.95).is_err());
    // Perfect agreement (rows differ, columns identical): MSe == MSw == 0,
    // icc == 1 -> degenerate CI/pivot must Err, not leak inf/NaN.
    let perfect = vec![1.0, 1.0, 2.0, 2.0, 3.0, 3.0, 4.0, 4.0];
    assert!(icc(&perfect, 4, 2, "twoway", "agreement", "single", 0.0, 0.95).is_err());
    assert!(icc(&perfect, 4, 2, "twoway", "consistency", "single", 0.0, 0.95).is_err());
    // Huge magnitudes overflow the SS accumulation -> explicit error.
    let huge = vec![1e300, -1e300, 1e300, -1e300, -1e300, 1e300, 1e300, 1e300];
    assert!(icc(&huge, 4, 2, "oneway", "consistency", "single", 0.0, 0.95).is_err());
}

/// MC-500: subject- and rater-permutation invariance plus the
/// Spearman-Brown identity between the crate's own single- and
/// average-unit outputs, for all three model families (algebraic identity
/// verified in spec review; both sides read crate outputs, so a mutation
/// breaking either unit's formula independently fails the bridge).
#[test]
#[ignore]
fn ic_mc_500_invariance() {
    let mut state = 0x1CC5EEDu64;
    let mut uni = |s: &mut u64| -> f64 {
        *s = s
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        (*s >> 11) as f64 / (1u64 << 53) as f64
    };
    for rep in 0..500 {
        let ns = 4 + (uni(&mut state) * 6.0) as usize;
        let nr = 2 + (uni(&mut state) * 4.0) as usize;
        let data: Vec<f64> = (0..ns * nr)
            .map(|_| (uni(&mut state) * 10.0).round())
            .collect();
        let variants = [
            ("oneway", "consistency"),
            ("twoway", "consistency"),
            ("twoway", "agreement"),
        ];
        // Skip degenerate draws (constant matrices, near-1 CI pivots etc.)
        // in ANY variant/unit combination.
        if variants.iter().any(|(m, t)| {
            icc(&data, ns, nr, m, t, "single", 0.0, 0.95).is_err()
                || icc(&data, ns, nr, m, t, "average", 0.0, 0.95).is_err()
        }) {
            continue;
        }
        // Subject reversal.
        let rev_rows: Vec<f64> = (0..ns)
            .rev()
            .flat_map(|i| data[i * nr..(i + 1) * nr].to_vec())
            .collect();
        // Rater reversal.
        let rev_cols: Vec<f64> = (0..ns)
            .flat_map(|i| (0..nr).rev().map(move |j| (i, j)))
            .map(|(i, j)| data[i * nr + j])
            .collect();
        for (m, t) in variants {
            let s = icc(&data, ns, nr, m, t, "single", 0.0, 0.95).unwrap();
            let a = icc(&data, ns, nr, m, t, "average", 0.0, 0.95).unwrap();
            let sr = icc(&rev_rows, ns, nr, m, t, "single", 0.0, 0.95).unwrap();
            let sc = icc(&rev_cols, ns, nr, m, t, "single", 0.0, 0.95).unwrap();
            assert!(icc_rel(sr.value, s.value, 1e-10), "rep {rep} row-perm");
            assert!(icc_rel(sc.value, s.value, 1e-10), "rep {rep} col-perm");
            // Spearman-Brown bridge between two crate outputs.
            let k = nr as f64;
            let sb = k * s.value / (1.0 + (k - 1.0) * s.value);
            assert!(
                icc_rel(a.value, sb, 1e-10),
                "rep {rep} {m}/{t} SB: {} vs {sb}",
                a.value
            );
        }
    }
}

// ---------------------------------------------------------------------------
// kripp_alpha (irr 0.85 kripp.alpha.R). Pins are exact Fractions from the
// executed oracle (files/kripp_oracle.py); K1 matches the irr man page's
// published values. Every assert reads KrippResult fields returned by the
// crate.
// ---------------------------------------------------------------------------

fn ka_close(a: f64, b: f64) -> bool {
    let d = (a - b).abs();
    d <= 1e-12 || d <= 1e-12 * b.abs()
}

/// irr man-page `nmm` matrix, raters x subjects (4 x 12); NaN = missing.
fn ka_k1() -> Vec<f64> {
    let nan = f64::NAN;
    // Column-major R matrix(nrow=4) transposed to rater rows.
    let cols: [[f64; 4]; 12] = [
        [1.0, 1.0, nan, 1.0],
        [2.0, 2.0, 3.0, 2.0],
        [3.0, 3.0, 3.0, 3.0],
        [3.0, 3.0, 3.0, 3.0],
        [2.0, 2.0, 2.0, 2.0],
        [1.0, 2.0, 3.0, 4.0],
        [4.0, 4.0, 4.0, 4.0],
        [1.0, 1.0, 2.0, 1.0],
        [2.0, 2.0, 2.0, 2.0],
        [nan, 5.0, 5.0, 5.0],
        [nan, nan, 1.0, 1.0],
        [nan, nan, 3.0, nan],
    ];
    let mut x = vec![0.0; 4 * 12];
    for (c, col) in cols.iter().enumerate() {
        for (r, v) in col.iter().enumerate() {
            x[r * 12 + c] = *v;
        }
    }
    x
}

#[test]
fn ka_anchor_k1_all_methods() {
    // Kills MU1 (diag 1/mc: nominal -> 501/869 = 0.5765...), MU3 (ordinal
    // full weights -> 167915/216366), MU4 (interval |d| -> 417/521),
    // MU5 (nmv excludes diagonal -> 145/152), MU6 (num*nc products).
    let x = ka_k1();
    let want = [
        ("nominal", 113.0 / 152.0),
        ("ordinal", 108577.0 / 133160.0),
        ("interval", 951.0 / 1120.0),
        ("ratio", 18222619.0 / 22852465.0),
    ];
    for (m, v) in want {
        let r = kripp_alpha(&x, 4, 12, m).unwrap();
        assert!(ka_close(r.value, v), "{m}: {} vs {v}", r.value);
        assert_eq!(r.nmatchval, 40.0, "{m} nmv");
        assert_eq!(r.subjects, 12);
        assert_eq!(r.raters, 4);
        assert_eq!(r.levels, 5);
    }
}

#[test]
fn ka_no_na_quirk_k2() {
    // Complete data uses divisor mc = 1, NOT m - 1 (R lines 12-13 quirk).
    // Kills MU2 (mc always m-1): mutant nominal would be 11/18 != 43/72.
    let x = [
        1.0, 2.0, 3.0, 3.0, 2.0, //
        1.0, 2.0, 3.0, 3.0, 1.0, //
        2.0, 2.0, 3.0, 3.0, 2.0,
    ];
    let n = kripp_alpha(&x, 3, 5, "nominal").unwrap();
    assert!(ka_close(n.value, 43.0 / 72.0), "nominal {}", n.value);
    assert_eq!(n.nmatchval, 30.0);
    let i = kripp_alpha(&x, 3, 5, "interval").unwrap();
    assert!(ka_close(i.value, 97.0 / 126.0), "interval {}", i.value);
    // Guard the guard: the MU2 mutant value differs from the true pin.
    assert!(!ka_close(n.value, 11.0 / 18.0));
}

#[test]
fn ka_hand_fixture_k3() {
    let x = [1.0, 2.0, 3.0, 1.0, 1.0, 3.0, 3.0, 2.0];
    let n = kripp_alpha(&x, 2, 4, "nominal").unwrap();
    assert!(ka_close(n.value, 1.0 / 3.0), "nominal {}", n.value);
    let o = kripp_alpha(&x, 2, 4, "ordinal").unwrap();
    assert!(ka_close(o.value, 17.0 / 24.0), "ordinal {}", o.value);
    // Interval coincidentally equals ordinal on this fixture (both crate
    // outputs; the ordinal/interval swap mutant is killed on K1 where the
    // two pins differ).
    let iv = kripp_alpha(&x, 2, 4, "interval").unwrap();
    assert!(ka_close(iv.value, 17.0 / 24.0), "interval {}", iv.value);
    assert!(ka_close(iv.value, o.value));
    let rt = kripp_alpha(&x, 2, 4, "ratio").unwrap();
    assert!(ka_close(rt.value, 1889.0 / 2841.0), "ratio {}", rt.value);
    assert_eq!(n.nmatchval, 8.0);
    assert_eq!(n.levels, 3);
}

#[test]
fn ka_single_level_k4() {
    // R line 45: fewer than 2 levels -> alpha = 1.
    let x = [2.0, 2.0, 2.0, 2.0];
    let r = kripp_alpha(&x, 2, 2, "nominal").unwrap();
    assert_eq!(r.value, 1.0);
    assert_eq!(r.nmatchval, 4.0);
    assert_eq!(r.levels, 1);
}

#[test]
fn ka_error_contract() {
    let ok = [1.0, 2.0, 2.0, 1.0];
    assert!(kripp_alpha(&ok, 2, 2, "euclid")
        .unwrap_err()
        .contains("method"));
    assert!(kripp_alpha(&ok, 1, 4, "nominal")
        .unwrap_err()
        .contains("raters"));
    assert!(kripp_alpha(&[], 2, 0, "nominal")
        .unwrap_err()
        .contains("subject"));
    assert!(kripp_alpha(&ok, 2, 3, "nominal")
        .unwrap_err()
        .contains("length"));
    let inf = [1.0, f64::INFINITY, 2.0, 1.0];
    assert!(kripp_alpha(&inf, 2, 2, "nominal")
        .unwrap_err()
        .contains("infinit"));
    let nan = f64::NAN;
    assert!(kripp_alpha(&[nan, nan, nan, nan], 2, 2, "nominal")
        .unwrap_err()
        .contains("missing"));
    // Ratio metric undefined when a level pair sums to zero.
    let zsum = [-1.0, 1.0, 1.0, -1.0];
    assert!(kripp_alpha(&zsum, 2, 2, "ratio")
        .unwrap_err()
        .contains("ratio"));
    // Same data is fine for nominal/interval (crate outputs finite).
    assert!(kripp_alpha(&zsum, 2, 2, "nominal")
        .unwrap()
        .value
        .is_finite());
    assert!(kripp_alpha(&zsum, 2, 2, "interval")
        .unwrap()
        .value
        .is_finite());
}

#[test]
#[ignore = "MC-500: run explicitly with cargo test -- --ignored"]
fn ka_mc_500_permutation_invariance() {
    // Alpha is invariant under rater-row and subject-column permutation;
    // both sides of every comparison are crate outputs.
    let mut state = 0xCA5EEDu64;
    let mut next = |s: &mut u64| -> u64 {
        *s = s
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        *s >> 11
    };
    let base = ka_k1();
    let methods = ["nominal", "ordinal", "interval", "ratio"];
    for rep in 0..500 {
        let m = methods[rep % 4];
        let want = kripp_alpha(&base, 4, 12, m).unwrap();
        // Fisher-Yates over rater rows.
        let mut rows: Vec<usize> = (0..4).collect();
        for i in (1..4).rev() {
            let j = (next(&mut state) % (i as u64 + 1)) as usize;
            rows.swap(i, j);
        }
        let mut cols: Vec<usize> = (0..12).collect();
        for i in (1..12).rev() {
            let j = (next(&mut state) % (i as u64 + 1)) as usize;
            cols.swap(i, j);
        }
        let mut xp = vec![0.0; 48];
        for (rn, &ro) in rows.iter().enumerate() {
            for (cn, &co) in cols.iter().enumerate() {
                xp[rn * 12 + cn] = base[ro * 12 + co];
            }
        }
        let got = kripp_alpha(&xp, 4, 12, m).unwrap();
        assert!(
            ka_close(got.value, want.value),
            "rep {rep} {m}: {} vs {}",
            got.value,
            want.value
        );
        assert_eq!(got.nmatchval, want.nmatchval, "rep {rep} nmv");
        assert_eq!(got.levels, want.levels, "rep {rep} levels");
    }
}

// ---------------------------------------------------------------------------
// Finn (1970) coefficient (`finn_coefficient`). Pins from the EXECUTED
// exact-Fraction oracle (session files/finn_oracle.py, output
// finn_oracle_output.txt); every assert reads FinnResult fields returned by
// the crate. Mutation kills (each EXECUTED: mutant compiled, test FAILED,
// restored): MU1 MSexp = s^2/12 -> fn1_anchor_oneway value pin; MU2
// population row variance -> fn1_anchor_oneway; MU3 twoway MSe drops MSc ->
// fn1_anchor_twoway; MU4 df2 = (ns-1)(nr-1) -> fn1_anchor_oneway p pin; MU5
// flipped p tail -> fn1_anchor_oneway p pin; MU6 listwise drop skipped ->
// fn1_listwise_drop (NaN row must reproduce the 5-row pins exactly).

// FN1 fixture: 6x4 integer ratings, s = 5 (oracle FN1).
const FN1: [f64; 24] = [
    2.0, 3.0, 2.0, 3.0, 4.0, 4.0, 5.0, 4.0, 1.0, 2.0, 1.0, 1.0, 3.0, 3.0, 3.0, 4.0, 5.0, 4.0, 5.0,
    5.0, 2.0, 2.0, 3.0, 2.0,
];

#[test]
fn fn1_anchor_oneway() {
    // Oracle FN1: coeff = 125/144, F = 144/19, df2 = 18,
    // p = 4.47127350746514e-06. Kills MU1 (131/150), MU2 (173/192),
    // MU4 (p 2.7664901762462074e-05), MU5 (p 0.9999955287264926).
    let r = finn_coefficient(&FN1, 6, 4, 5, "oneway").unwrap();
    assert!((r.value - 125.0 / 144.0).abs() < 1e-15);
    assert!((r.statistic - 144.0 / 19.0).abs() < 1e-13);
    assert_eq!(r.df2, 18.0);
    assert!((r.p_value - 4.47127350746514e-06).abs() < 1e-12);
    assert_eq!(r.subjects, 6);
    assert_eq!(r.raters, 4);
}

#[test]
fn fn1_anchor_twoway() {
    // Oracle FN2: coeff = 617/720, F = 720/103, df2 = 18 (R quirk: twoway
    // also uses ns*(nr-1)), p = 8.469265956566033e-06. Kills MU3 (101/120).
    let r = finn_coefficient(&FN1, 6, 4, 5, "twoway").unwrap();
    assert!((r.value - 617.0 / 720.0).abs() < 1e-15);
    assert!((r.statistic - 720.0 / 103.0).abs() < 1e-13);
    assert_eq!(r.df2, 18.0);
    assert!((r.p_value - 8.469265956566033e-06).abs() < 1e-12);
}

#[test]
fn fn1_listwise_drop() {
    // FN1 rows minus row 2 plus a NaN row: must equal the oracle FN3 5-row
    // pins exactly (coeff 13/15, F 15/2, df2 15, p 2.9654977282546142e-05).
    // A mutant that keeps, imputes, or NaN-propagates the row cannot
    // reproduce these finite pins (kills MU6).
    let mut with_nan: Vec<f64> = Vec::new();
    for (i, chunk) in FN1.chunks(4).enumerate() {
        if i == 2 {
            with_nan.extend_from_slice(&[1.0, f64::NAN, 1.0, 1.0]);
        } else {
            with_nan.extend_from_slice(chunk);
        }
    }
    let r = finn_coefficient(&with_nan, 6, 4, 5, "oneway").unwrap();
    assert_eq!(r.subjects, 5);
    assert!((r.value - 13.0 / 15.0).abs() < 1e-15);
    assert!((r.statistic - 7.5).abs() < 1e-13);
    assert_eq!(r.df2, 15.0);
    assert!((r.p_value - 2.9654977282546142e-05).abs() < 1e-12);
}

#[test]
fn fn1_anchor_two_raters() {
    // Oracle FN4 5x2 s=3: oneway coeff 1/10, F 10/9, df2 5,
    // p 0.5201165618867003; twoway coeff -1/8 (negative valid), F 8/9,
    // p 0.655566243225814.
    let fn4 = [1.0, 2.0, 2.0, 2.0, 3.0, 1.0, 1.0, 1.0, 2.0, 3.0];
    let r = finn_coefficient(&fn4, 5, 2, 3, "oneway").unwrap();
    assert!((r.value - 0.1).abs() < 1e-15);
    assert!((r.statistic - 10.0 / 9.0).abs() < 1e-14);
    assert_eq!(r.df2, 5.0);
    assert!((r.p_value - 0.5201165618867003).abs() < 1e-12);
    let t = finn_coefficient(&fn4, 5, 2, 3, "twoway").unwrap();
    assert!((t.value - (-0.125)).abs() < 1e-15);
    assert!((t.statistic - 8.0 / 9.0).abs() < 1e-14);
    assert!((t.p_value - 0.655566243225814).abs() < 1e-12);
}

#[test]
fn fn1_perfect_agreement() {
    // MSw == 0 (oneway): all raters agree per row -> value 1, F +Inf, p 0.
    let perfect = [1.0, 1.0, 3.0, 3.0, 5.0, 5.0, 2.0, 2.0];
    let r = finn_coefficient(&perfect, 4, 2, 5, "oneway").unwrap();
    assert_eq!(r.value, 1.0);
    assert!(r.statistic.is_infinite() && r.statistic > 0.0);
    assert_eq!(r.p_value, 0.0);
    // MSe == 0 (twoway): additive row + column structure has zero residual;
    // x_ij = row_i + col_j with rows [0,1,2], cols [0,1].
    let additive = [1.0, 2.0, 2.0, 3.0, 3.0, 4.0];
    let t = finn_coefficient(&additive, 3, 2, 5, "twoway").unwrap();
    assert_eq!(t.value, 1.0);
    assert!(t.statistic.is_infinite() && t.statistic > 0.0);
    assert_eq!(t.p_value, 0.0);
}

#[test]
fn fn1_error_contract() {
    let ok = [1.0, 2.0, 2.0, 1.0];
    assert!(finn_coefficient(&ok, 2, 2, 3, "both")
        .unwrap_err()
        .contains("model"));
    assert!(finn_coefficient(&ok, 2, 2, 1, "oneway")
        .unwrap_err()
        .contains("s_levels"));
    assert!(finn_coefficient(&ok, 4, 1, 3, "oneway")
        .unwrap_err()
        .contains("raters"));
    assert!(finn_coefficient(&ok, 2, 3, 3, "oneway")
        .unwrap_err()
        .contains("length"));
    let inf = [1.0, f64::INFINITY, 2.0, 1.0];
    assert!(finn_coefficient(&inf, 2, 2, 3, "oneway")
        .unwrap_err()
        .contains("infinit"));
    // NaN deletion leaving exactly one complete row.
    let nan = f64::NAN;
    let one_left = [1.0, 2.0, nan, 2.0, 3.0, nan];
    assert!(finn_coefficient(&one_left, 3, 2, 3, "oneway")
        .unwrap_err()
        .contains("complete"));
}

#[test]
#[ignore = "MC-500: run with --ignored"]
fn fn1_mc_500_permutation_invariance() {
    // Property: oneway/twoway Finn coefficients are invariant under subject
    // permutation, and oneway is invariant under rater permutation (MSw is
    // a row-wise statistic; twoway MSe is also rater-permutation invariant
    // since MSc uses the unordered set of column means). Asserts compare
    // crate outputs against crate outputs on permuted input.
    let mut state: u64 = 0x00C0FFEE;
    let mut next = move || {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        ((state >> 33) % 7) as f64 + 1.0
    };
    for rep in 0..500 {
        let ns = 4 + (rep % 5);
        let nr = 2 + (rep % 3);
        let data: Vec<f64> = (0..ns * nr).map(|_| next()).collect();
        for model in ["oneway", "twoway"] {
            let base = finn_coefficient(&data, ns, nr, 7, model).unwrap();
            // Subject permutation: reverse rows.
            let rev: Vec<f64> = (0..ns)
                .rev()
                .flat_map(|i| data[i * nr..(i + 1) * nr].to_vec())
                .collect();
            let p = finn_coefficient(&rev, ns, nr, 7, model).unwrap();
            assert!((base.value - p.value).abs() < 1e-12, "{model} rep {rep}");
            assert!((base.p_value - p.p_value).abs() < 1e-12);
            // Rater permutation: reverse columns.
            let cperm: Vec<f64> = (0..ns)
                .flat_map(|i| (0..nr).rev().map(move |j| (i, j)))
                .map(|(i, j)| data[i * nr + j])
                .collect();
            let c = finn_coefficient(&cperm, ns, nr, 7, model).unwrap();
            assert!((base.value - c.value).abs() < 1e-12, "{model} rep {rep}");
        }
    }
}

// ---------------------------------------------------------------------------
// Maxwell's RE (maxwell_re) — anchors from the executed exact-Fraction oracle
// replicating irr 0.84.1 maxwell.R. Every assert reads crate outputs.
// Known unkillable identity: column swap (the match count #{r1 == r2} is
// symmetric in the two columns by definition — an estimand property).
// ---------------------------------------------------------------------------

/// M1 anchor: 10 subjects in {0,1}, 7 exact matches -> RE = 2*7/10 - 1 = 2/5.
/// 2/5 is not dyadic -> tolerance assert. Kills MU5a (self-compare counts
/// 10/10 -> 1.0) and MU5b (`<=` counts 9/10 -> 0.8).
#[test]
fn mx_anchor_m1() {
    let r = [
        0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0,
        0.0, 1.0,
    ];
    let out = maxwell_re(&r, 10, 2).unwrap();
    assert!((out.value - 0.4).abs() < 1e-15, "value {}", out.value);
    assert_eq!(out.subjects, 10);
    assert_eq!(out.raters, 2);
}

/// M2: M1 plus two NaN rows (one NaN in each column) inserted mid-matrix.
/// Listwise deletion must drop both rows, leaving the M1 result with
/// subjects == 10 (not 12). Kills MU4 (skip deletion -> NaN rows counted in
/// the denominator, no NaN agreements -> value (2*7/12 - 1) != 2/5 and
/// subjects 12).
#[test]
fn mx_nan_rows_dropped_m2() {
    let nan = f64::NAN;
    let r = [
        0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, nan, 1.0, 0.0, nan, 1.0, 0.0, 1.0, 1.0,
        0.0, 0.0, 1.0, 1.0, 0.0, 1.0,
    ];
    let out = maxwell_re(&r, 12, 2).unwrap();
    assert!((out.value - 0.4).abs() < 1e-15, "value {}", out.value);
    assert_eq!(out.subjects, 10);
}

/// M2b anchor: 10 rows, 2 dropped by NaN -> ns = 8, agree = 5,
/// RE = 2*5/8 - 1 = 1/4 exactly (dyadic -> exact ==). Mutant pins (executed):
/// MU1 (drop factor 2) -> -0.375; MU2 (drop -1) -> 1.25; MU4 (no deletion)
/// -> 0.0 with subjects 10.
#[test]
fn mx_anchor_m2b_exact() {
    let nan = f64::NAN;
    let r = [
        0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, nan, 0.0,
        0.0, nan,
    ];
    let out = maxwell_re(&r, 10, 2).unwrap();
    assert_eq!(out.value, 0.25, "value {}", out.value);
    assert_eq!(out.subjects, 8);
}

/// M3: perfect agreement -> exactly 1.0 (also exercises the allowed
/// single-distinct-value case); total disagreement -> exactly -1.0.
#[test]
fn mx_bounds_m3() {
    let perfect = [1.0; 12];
    let out = maxwell_re(&perfect, 6, 2).unwrap();
    assert_eq!(out.value, 1.0);
    let disagree = [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0];
    let out = maxwell_re(&disagree, 6, 2).unwrap();
    assert_eq!(out.value, -1.0);
}

/// M4: nonstandard binary labels {2.5, 7.0}; 4 of 6 agree -> RE = 1/3.
/// Kills mutants hard-coding {0,1} labels.
#[test]
fn mx_nonstandard_labels_m4() {
    let r = [2.5, 2.5, 7.0, 7.0, 2.5, 7.0, 7.0, 7.0, 2.5, 2.5, 7.0, 2.5];
    let out = maxwell_re(&r, 6, 2).unwrap();
    assert!((out.value - 1.0 / 3.0).abs() < 1e-15, "value {}", out.value);
}

/// E1 + error contract. E1 (col1 in {0,1}, col2 in {0,2}: each column
/// individually binary but union has 3 levels) kills MU3 (per-column binary
/// check instead of union).
#[test]
fn mx_error_contract() {
    // E1: union of 3 levels rejected.
    let e1 = [0.0, 0.0, 1.0, 2.0, 0.0, 0.0, 1.0, 2.0];
    assert!(maxwell_re(&e1, 4, 2).is_err());
    // 3 distinct values within one column.
    let tri = [0.0, 0.0, 1.0, 1.0, 2.0, 2.0];
    assert!(maxwell_re(&tri, 3, 2).is_err());
    // nr != 2.
    assert!(maxwell_re(&[0.0, 1.0], 2, 1).is_err());
    assert!(maxwell_re(&[0.0, 1.0, 0.0, 1.0, 0.0, 1.0], 2, 3).is_err());
    // ns == 0 and length mismatch.
    assert!(maxwell_re(&[], 0, 2).is_err());
    assert!(maxwell_re(&[0.0, 1.0, 0.0], 2, 2).is_err());
    // Inf rejected.
    assert!(maxwell_re(&[0.0, f64::INFINITY, 1.0, 1.0], 2, 2).is_err());
    // All rows NaN-dropped.
    let nan = f64::NAN;
    assert!(maxwell_re(&[nan, 0.0, 1.0, nan], 2, 2).is_err());
    // One row remaining after drop is allowed (ns = 1 after deletion).
    let out = maxwell_re(&[nan, 0.0, 1.0, 1.0], 2, 2).unwrap();
    assert_eq!(out.value, 1.0);
    assert_eq!(out.subjects, 1);
}

/// MC-500: random binary 2-column matrices with random NaN holes. The
/// test-side oracle is an independent loop (listwise drop, union check,
/// match count, 2*A/m - 1) that never calls the crate. Also checks
/// row-permutation invariance crate-vs-crate (kills row-position
/// dependence).
#[test]
#[ignore]
fn mx_mc_500_independent_oracle() {
    let mut state: u64 = 0x4D61_7857_454C_4C31;
    let mut lcg = move || {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        ((state >> 33) as f64) / ((1u64 << 31) as f64)
    };
    for rep in 0..500 {
        let ns = 4 + (lcg() * 40.0) as usize;
        let hi = 1.0 + lcg() * 9.0; // nonstandard second label
        let mut r = Vec::with_capacity(ns * 2);
        for _ in 0..(ns * 2) {
            let u = lcg();
            if u < 0.1 {
                r.push(f64::NAN);
            } else if u < 0.55 {
                r.push(0.0);
            } else {
                r.push(hi);
            }
        }
        // Independent test-side oracle: listwise drop + match count.
        let mut m = 0usize;
        let mut agree = 0usize;
        for p in 0..ns {
            let (a, b) = (r[p * 2], r[p * 2 + 1]);
            if a.is_nan() || b.is_nan() {
                continue;
            }
            m += 1;
            if a == b {
                agree += 1;
            }
        }
        let res = maxwell_re(&r, ns, 2);
        if m == 0 {
            assert!(res.is_err(), "rep {rep}: expected Err on empty");
            continue;
        }
        let expected = 2.0 * agree as f64 / m as f64 - 1.0;
        let out = res.unwrap();
        assert!(
            (out.value - expected).abs() < 1e-14,
            "rep {rep}: crate {} vs oracle {}",
            out.value,
            expected
        );
        assert_eq!(out.subjects, m as u64, "rep {rep}");
        // Row-permutation invariance (deterministic rotation), crate-vs-crate.
        let k = 1 + (lcg() * (ns as f64 - 1.0)) as usize;
        let mut rot = Vec::with_capacity(ns * 2);
        for p in 0..ns {
            let q = (p + k) % ns;
            rot.push(r[q * 2]);
            rot.push(r[q * 2 + 1]);
        }
        let out2 = maxwell_re(&rot, ns, 2).unwrap();
        assert_eq!(out.value, out2.value, "rep {rep}: permutation variance");
    }
}
