//! Tests for Guttman lambda reliability (`crate::reliability`).
//!
//! Fixture literals come from an INDEPENDENT NumPy replication
//! (session files/guttman_fixture.py): np.corrcoef + np.linalg.inv +
//! itertools.combinations, with data generated by a NumPy mirror of the
//! crate LCG (np.uint64). Every assert reads a `GuttmanResult` field
//! returned by `guttman_lambdas` — no test-local recomputation of any
//! lambda.
//!
//! Mutation kills verified by hand-editing the implementation (each FAILED,
//! then was restored):
//! - M1 drop `.abs()` in `split_rb` -> fixture A/B lambda4/beta/mean_split.
//! - M2 drop the `p/(p-1)` factor inside lambda2's sqrt -> lambda2 pins.
//! - M3 lambda5 uses the SUM of `C_j` instead of the max -> lambda5 pins.
//! - M4 drop the SMC clamp / use `1/diag` without `1 -` -> lambda6 pins.
//! - M5 break the combination stepper (skip last combination) -> n_splits
//!   pin (exhaustive counts are exact binomials).
//!
//! Known identity limit (disclosed): `lambda3 = p/(p-1) * lambda1` is exact
//! algebra, so a mutation rescaling BOTH consistently cannot be caught by
//! any data fixture; the discriminating anchor is that lambda1 and lambda3
//! are pinned to independent NumPy literals, so only jointly consistent
//! mutations survive. Likewise `Vt = sum(R)` equals the per-split collapsed
//! total for every partition, so substituting one for the other is
//! mathematically identical and unkillable.
use super::*;

const TOL: f64 = 1e-9;

/// NumPy-mirrored LCG data generator (fixture input construction only; the
/// code under test never sees these helpers).
fn gen_data(
    n: usize,
    p: usize,
    seed: u64,
    loadings: &[f64],
    means: &[f64],
    scales: &[f64],
) -> Vec<f64> {
    let mut state = seed.max(1);
    let mut uniform = |state: &mut u64| -> f64 {
        *state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        (*state >> 11) as f64 / (1u64 << 53) as f64
    };
    let mut normal = |state: &mut u64| -> f64 {
        let u1 = uniform(state).max(1e-12);
        let u2 = uniform(state);
        (-2.0 * u1.ln()).sqrt() * (2.0 * std::f64::consts::PI * u2).cos()
    };
    let mut out = vec![0.0_f64; n * p];
    for i in 0..n {
        let f = normal(&mut state);
        for j in 0..p {
            let e = normal(&mut state);
            out[i * p + j] = means[j] + scales[j] * (loadings[j] * f + e);
        }
    }
    out
}

#[test]
fn fixture_a_exhaustive_even_p() {
    let data = gen_data(
        30,
        6,
        42,
        &[0.9, 0.8, 0.7, 0.6, 0.5, 0.2],
        &[10.0, -3.0, 5.0, 0.5, 100.0, 7.0],
        &[1.0, 2.0, 0.5, 3.0, 10.0, 1.5],
    );
    let g = guttman_lambdas(&data, 30, 6, 15000, 1).expect("fixture A");
    assert!((g.lambda1 - 0.41068157604336863).abs() < TOL);
    assert!((g.lambda2 - 0.5561900258418755).abs() < TOL);
    assert!((g.lambda3 - 0.49281789125204234).abs() < TOL);
    assert!((g.lambda4 - 0.6842463861953535).abs() < TOL);
    assert!((g.lambda5 - 0.5602004712206824).abs() < TOL);
    assert!((g.lambda6 - 0.59150154331973).abs() < TOL);
    assert!((g.beta - 0.1784553694910821).abs() < TOL);
    assert!((g.mean_split - 0.4928178912520423).abs() < TOL);
    assert_eq!(g.n_splits, 20); // C(6, 3)
    assert!(g.exhaustive);
}

#[test]
fn fixture_b_exhaustive_odd_p() {
    let data = gen_data(
        24,
        5,
        99,
        &[0.8, 0.7, 0.6, 0.5, 0.4],
        &[1.0, 2.0, 3.0, 4.0, 5.0],
        &[1.0, 1.0, 2.0, 1.0, 0.5],
    );
    let g = guttman_lambdas(&data, 24, 5, 15000, 1).expect("fixture B");
    assert!((g.lambda1 - 0.36304984346951963).abs() < TOL);
    assert!((g.lambda2 - 0.5427967072982294).abs() < TOL);
    assert!((g.lambda3 - 0.45381230433689956).abs() < TOL);
    assert!((g.lambda4 - 0.6863584325671727).abs() < TOL);
    assert!((g.lambda5 - 0.5668547649655623).abs() < TOL);
    assert!((g.lambda6 - 0.5667118066898096).abs() < TOL);
    assert!((g.beta - 0.04899616716352421).abs() < TOL);
    assert!((g.mean_split - 0.44545904559612853).abs() < TOL);
    assert_eq!(g.n_splits, 10); // C(5, 2): m = floor(5/2), A size 2 vs B size 3
    assert!(g.exhaustive);
}

#[test]
fn fixture_c_sampled_branch() {
    let mut loadings = vec![0.7_f64; 10];
    loadings.extend(vec![0.4_f64; 10]);
    let data = gen_data(60, 20, 7, &loadings, &[0.0; 20], &[1.0; 20]);
    let g = guttman_lambdas(&data, 60, 20, 200, 7).expect("fixture C");
    assert!((g.lambda1 - 0.8173350703037762).abs() < TOL);
    assert!((g.lambda2 - 0.8657986449939672).abs() < TOL);
    assert!((g.lambda3 - 0.8603527055829222).abs() < TOL);
    assert!((g.lambda4 - 0.921571734274876).abs() < TOL);
    assert!((g.lambda5 - 0.8439917779688363).abs() < TOL);
    assert!((g.lambda6 - 0.8931192541579849).abs() < TOL);
    assert!((g.beta - 0.7974800893409002).abs() < TOL);
    assert!((g.mean_split - 0.8623803334548827).abs() < TOL);
    assert_eq!(g.n_splits, 200);
    assert!(!g.exhaustive);
}

#[test]
fn rejections() {
    let ok = gen_data(10, 4, 3, &[0.5; 4], &[0.0; 4], &[1.0; 4]);
    assert!(guttman_lambdas(&ok, 2, 4, 100, 1).is_err()); // wrong length too
    assert!(guttman_lambdas(&ok[..8], 2, 4, 100, 1).is_err()); // n < 3
    assert!(guttman_lambdas(&ok[..20], 10, 2, 100, 1).is_err()); // p < 3
    assert!(guttman_lambdas(&ok, 10, 4, 0, 1).is_err()); // budget 0
    let mut nan = ok.clone();
    nan[5] = f64::NAN;
    assert!(guttman_lambdas(&nan, 10, 4, 100, 1).is_err());
    let mut constant = ok.clone();
    for i in 0..10 {
        constant[i * 4] = 2.5;
    }
    assert!(guttman_lambdas(&constant, 10, 4, 100, 1).is_err()); // zero variance
}

#[test]
fn singular_correlation_errs_for_lambda6() {
    // Duplicate columns: correlation_matrix succeeds (r = 1) but R is
    // exactly singular, so the SMC inverse must Err (divergence 4: psych
    // would silently Pinv; we refuse). Assert reads the crate Result.
    let base = gen_data(15, 1, 11, &[0.6], &[0.0], &[1.0]);
    let mut data = vec![0.0_f64; 15 * 3];
    for i in 0..15 {
        data[i * 3] = base[i];
        data[i * 3 + 1] = base[i]; // exact duplicate
        data[i * 3 + 2] = (i as f64).sin() + base[i];
    }
    let err = guttman_lambdas(&data, 15, 3, 100, 1).unwrap_err();
    assert!(err.contains("singular"), "unexpected error: {err}");
}

/// >= 500-replication Monte Carlo: tau-equivalent items (equal loadings,
/// equal noise), where coefficient alpha ( = lambda3) is consistent for the
/// true reliability rho = p*l^2 / (p*l^2 + p*s^2) of the unit-weighted sum
/// score under the one-factor model. With l = 0.7, s = 1, p = 8:
/// rho = 8*0.49 / (8*0.49 + 8) ... per-item communality basis; the sum-score
/// reliability is rho_sum = (p^2 l^2 sigma_f^2) / (p^2 l^2 sigma_f^2 +
/// p s^2) = (64*0.49)/(64*0.49 + 8) = 0.796696. Asserts read only crate
/// outputs (mean of returned lambda3 across reps).
#[test]
#[ignore]
fn mc_tau_equivalent_alpha_recovery() {
    let p = 8;
    let reps = 500;
    let mut sum_l3 = 0.0_f64;
    let mut ge = 0usize;
    for rep in 0..reps {
        let data = gen_data(
            300,
            p,
            1000 + rep as u64,
            &vec![0.7; p],
            &vec![0.0; p],
            &vec![1.0; p],
        );
        let g = guttman_lambdas(&data, 300, p, 500, 17).expect("mc rep");
        sum_l3 += g.lambda3;
        if g.lambda2 >= g.lambda3 - 1e-12 {
            ge += 1;
        }
    }
    let mean_l3 = sum_l3 / reps as f64;
    let rho = (64.0 * 0.49) / (64.0 * 0.49 + 8.0); // 0.796696...
    assert!(
        (mean_l3 - rho).abs() < 0.01,
        "mean lambda3 {mean_l3} vs analytic {rho}"
    );
    // Secondary (identity-adjacent, disclosed): Guttman's lambda2 >= lambda3
    // holds sample-wise; violations flag algebra mutations.
    assert_eq!(ge, reps);
}
