//! Tests for Haberman (2008) subscore added-value analysis.
//!
//! Fixture literals were generated by an independent Python/NumPy script
//! transcribing the CRAN `subscore` R semantics (ddof=1 throughout), never
//! calling this crate. Each test documents the crate value its asserts read
//! and at least one mutation it kills.

use super::*;

const TOL: f64 = 1e-12;

/// 10 persons x 4 binary items, subscales {0,1} and {2,3}. Chosen so all
/// alphas are in (0,1), correlations are non-degenerate, and the two
/// subscales give DIFFERENT added_value_sx outcomes (asymmetric fixture).
fn fixture() -> (Vec<Vec<f64>>, Vec<usize>) {
    let x = vec![
        vec![0., 0., 0., 1.],
        vec![0., 1., 0., 0.],
        vec![1., 1., 0., 1.],
        vec![0., 0., 1., 0.],
        vec![1., 1., 1., 1.],
        vec![1., 0., 1., 1.],
        vec![0., 0., 0., 0.],
        vec![1., 1., 1., 0.],
        vec![0., 1., 1., 1.],
        vec![1., 1., 0., 0.],
    ];
    (x, vec![0, 0, 1, 1])
}

/// Reads: alpha, alpha_total. Kills: dropping the m/(m-1) factor in
/// cronbach_alpha (alpha would become [0.4348, 0.2500], alpha_x 0.3356);
/// using biased (n) variance in only one of numerator/denominator.
#[test]
fn alpha_matches_independent_reference() {
    let (x, g) = fixture();
    let r = subscores(&x, &g).unwrap();
    assert!((r.alpha[0] - 0.5797101449275359).abs() < TOL);
    assert!((r.alpha[1] - 0.33333333333333326).abs() < 1e-10);
    assert!((r.alpha_total - 0.44742729306487705).abs() < TOL);
}

/// Reads: prmse_x. Kills the two documented rowsum mutants:
/// including the total column in cov_k gives r_stxt from
/// cov_rowsum = [1.4333, 1.1111]; skipping the true-variance diagonal
/// replacement gives cov_rowsum = [0.8778, 0.7778]. Both move PRMSE_x far
/// outside the asserted tolerance (reference cov_rowsum = [0.5556, 0.3333],
/// r_stxt = [0.9375, 0.675]).
#[test]
fn prmse_x_matches_independent_reference() {
    let (x, g) = fixture();
    let r = subscores(&x, &g).unwrap();
    assert!((r.prmse_x[0] - 0.41946308724832204).abs() < 1e-10);
    assert!((r.prmse_x[1] - 0.3020134228187919).abs() < 1e-10);
}

/// Reads: tau, beta, gamma, prmse_sx. Kills: sign flip in the tau numerator
/// (tau[0] would be negative); swapping beta and gamma (they differ by an
/// order of magnitude here); using r instead of r^2 in the tau denominator.
#[test]
fn augmented_regression_matches_independent_reference() {
    let (x, g) = fixture();
    let r = subscores(&x, &g).unwrap();
    assert!((r.tau[0] - 0.1385414635898375).abs() < 1e-10);
    assert!((r.tau[1] - 0.27024443691002326).abs() < 1e-10);
    assert!((r.beta[0] - 0.49752475247524747).abs() < 1e-10);
    assert!((r.beta[1] - 0.21782178217821788).abs() < 1e-10);
    assert!((r.gamma[0] - 0.07178217821782161).abs() < 1e-10);
    assert!((r.gamma[1] - 0.09900990099009896).abs() < 1e-10);
    assert!((r.prmse_sx[0] - 0.5872524752475244).abs() < 1e-10);
    assert!((r.prmse_sx[1] - 0.3663366336633662).abs() < 1e-10);
}

/// Reads: corr (K+1 x K+1, total last), prmse_s. Kills: variance/covariance
/// index transposition; normalizing by variance instead of SD.
#[test]
fn correlations_match_independent_reference() {
    let (x, g) = fixture();
    let r = subscores(&x, &g).unwrap();
    assert!((r.corr[0][2] - 0.7791290756515445).abs() < 1e-10);
    assert!((r.corr[1][2] - 0.7403367031320777).abs() < 1e-10);
    assert!((r.corr[2][0] - 0.7791290756515445).abs() < 1e-10);
    assert!((r.prmse_s[0] - r.alpha[0]).abs() < TOL);
    assert!((r.prmse_s[1] - r.alpha[1]).abs() < TOL);
    for k in 0..3 {
        assert!((r.corr[k][k] - 1.0).abs() < TOL);
    }
}

/// Reads: subscore_s, subscore_x, subscore_sx for person 0 (s = [0, 1],
/// x = 1). Kills: using observed instead of true SD in the s_hat_x slope
/// (0.7309 vs 0.6152 for subscale 0); centering on x instead of s in
/// s_hat_s; swapping mean_s and mean_x.
#[test]
fn person_estimates_match_independent_reference() {
    let (x, g) = fixture();
    let r = subscores(&x, &g).unwrap();
    assert!((r.subscore_s[0][0] - 0.4623188405797105).abs() < 1e-10);
    assert!((r.subscore_s[0][1] - 1.0).abs() < 1e-10);
    assert!((r.subscore_x[0][0] - 0.7308724832214768).abs() < 1e-10);
    assert!((r.subscore_x[0][1] - 0.778523489932886).abs() < 1e-10);
    assert!((r.subscore_sx[0][0] - 0.47376237623762407).abs() < 1e-10);
    assert!((r.subscore_sx[0][1] - 0.8910891089108911).abs() < 1e-10);
    assert!((r.observed[0][0] - 0.0).abs() < TOL);
    assert!((r.observed[0][1] - 1.0).abs() < TOL);
    assert!((r.total[0] - 1.0).abs() < TOL);
}

/// Reads: added_value_s, added_value_sx. The fixture is deliberately
/// asymmetric across subscales in added_value_sx ([false, true]), so any
/// mutant collapsing the decision to a constant, comparing against the wrong
/// PRMSE, or dropping the +0.01 margin (subscale 0 has
/// PRMSE_sx - PRMSE_s = 0.00754 < 0.01, which flips to true without the
/// margin) fails here.
#[test]
fn added_value_decisions_match_independent_reference() {
    let (x, g) = fixture();
    let r = subscores(&x, &g).unwrap();
    assert_eq!(r.added_value_s, vec![true, true]);
    assert_eq!(r.added_value_sx, vec![false, true]);
}

/// Reads: Err from negatively-keyed within-subscale items (alpha < 0).
/// Kills: removing the alpha-range guard (analysis would emit NaN PRMSEs).
#[test]
fn rejects_negative_alpha() {
    // Item 1 is the reverse of item 0 within subscale 0 -> alpha_0 < 0.
    let x: Vec<Vec<f64>> = (0..10)
        .map(|p| {
            let a = f64::from((p % 2 == 0) as u8);
            let c = f64::from((p % 3 == 0) as u8);
            let d = f64::from((p % 4 == 0) as u8);
            vec![a, 1.0 - a, c, d]
        })
        .collect();
    let err = subscores(&x, &[0, 0, 1, 1]).unwrap_err();
    assert!(err.contains("outside (0, 1]"), "{err}");
}

/// Reads: Err from a subscore collinear with the total. Duplicated subscales
/// make corr(s_k, x) = 1 exactly; the review mandated this be a REJECTION
/// (tau divides by 1 - r^2 = 0), not a parallel-forms anchor. Kills:
/// removing the collinearity guard (tau/PRMSE_sx would be inf/NaN).
#[test]
fn rejects_collinear_subscore() {
    let (x, _) = fixture();
    // Both subscales are the SAME two items duplicated: x = 2 s_1.
    let dup: Vec<Vec<f64>> = x
        .iter()
        .map(|row| vec![row[0], row[1], row[0], row[1]])
        .collect();
    let err = subscores(&dup, &[0, 0, 1, 1]).unwrap_err();
    assert!(err.contains("collinear"), "{err}");
}

/// Reads: Err on structural validation. Kills: skipping partition checks
/// (out-of-bounds panic or silent nonsense instead of Err).
#[test]
fn rejects_bad_inputs() {
    let (x, _) = fixture();
    assert!(subscores(&x[..2], &[0, 0, 1, 1]).is_err()); // n < 3
    assert!(subscores(&x, &[0, 0, 1]).is_err()); // groups length mismatch
    assert!(subscores(&x, &[0, 0, 0, 0]).is_err()); // K = 1
    assert!(subscores(&x, &[0, 1, 1, 1]).is_err()); // singleton subscale
    assert!(subscores(&x, &[0, 0, 1_000_000_000, 1_000_000_000]).is_err()); // sparse index DoS
    let mut nanx = x.clone();
    nanx[0][0] = f64::NAN;
    assert!(subscores(&nanx, &[0, 0, 1, 1]).is_err()); // incomplete data
    let zero = vec![vec![0., 0., 1., 0.]; 5];
    assert!(subscores(&zero, &[0, 0, 1, 1]).is_err()); // zero variance
}

/// Reads: prmse_sx vs prmse_s/prmse_x across many random guard-passing
/// datasets. The dominance PRMSE_sx >= max(PRMSE_s, PRMSE_x) is CONDITIONAL
/// on the guards (spec-review finding); asserted only on accepted samples.
/// Note: PRMSE_sx >= PRMSE_s is the identity alpha + tau^2 (1 - r^2) >=
/// alpha, which no mutant of the comparison inputs can violate on its own;
/// the discriminating half is PRMSE_sx >= PRMSE_x, which fails under the
/// rowsum/diagonal mutants documented in `prmse_x_matches_independent_reference`.
#[test]
fn dominance_holds_on_guard_passing_data() {
    // Deterministic LCG so the test is reproducible without rand dep.
    let mut state = 0x2545F4914F6CDD1Du64;
    let mut next = move || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        ((state >> 33) as f64) / ((1u64 << 31) as f64)
    };
    let mut accepted = 0;
    for _ in 0..200 {
        // Common-factor items so alphas are usually positive.
        let n = 40;
        let x: Vec<Vec<f64>> = (0..n)
            .map(|_| {
                let f = next();
                (0..6)
                    .map(|_| f64::from((0.6 * f + 0.4 * next() > 0.5) as u8))
                    .collect()
            })
            .collect();
        if let Ok(r) = subscores(&x, &[0, 0, 0, 1, 1, 1]) {
            accepted += 1;
            for k in 0..2 {
                assert!(
                    r.prmse_sx[k] + 1e-9 >= r.prmse_s[k].max(r.prmse_x[k]),
                    "dominance violated: sx={} s={} x={}",
                    r.prmse_sx[k],
                    r.prmse_s[k],
                    r.prmse_x[k]
                );
            }
        }
    }
    assert!(accepted >= 50, "too few guard-passing samples: {accepted}");
}

/// Reads: disattenuated_corr. Kills: dividing by alpha instead of
/// sqrt(alpha_a alpha_b); forgetting the NaN diagonal.
#[test]
fn disattenuated_correlation() {
    let (x, g) = fixture();
    let r = subscores(&x, &g).unwrap();
    let expect = 0.35355339059327384;
    assert!((r.disattenuated_corr[0][1] - expect).abs() < 1e-10);
    assert!((r.corr[0][1] - 0.15541746804005227).abs() < 1e-10);
    assert!(r.disattenuated_corr[0][0].is_nan());
}

/// 500-replication Monte Carlo: with a strong common factor plus weak
/// specific factors, the augmented estimator's MSE against the true subscore
/// should not exceed the observed-subscore estimator's MSE on average.
/// Reads: subscore_sx, subscore_s. Kills gross beta/gamma miscalibration
/// that the single-fixture literals could compensate for by luck.
#[test]
#[ignore = "500-rep Monte Carlo; run with -- --ignored"]
fn monte_carlo_augmented_mse() {
    let mut state = 0x9E3779B97F4A7C15u64;
    let mut next = move || {
        state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        ((state >> 33) as f64) / ((1u64 << 31) as f64)
    };
    let mut mse_s = 0.0f64;
    let mut mse_sx = 0.0f64;
    let mut reps = 0;
    for _ in 0..500 {
        let n = 200;
        let mut x = Vec::with_capacity(n);
        let mut true_s0 = Vec::with_capacity(n);
        for _ in 0..n {
            let f = next() * 2.0 - 1.0; // common factor
            let u0 = next() * 0.6 - 0.3; // weak specific factors
            let u1 = next() * 0.6 - 0.3;
            let mut row = Vec::with_capacity(8);
            let mut t0 = 0.0;
            for j in 0..8 {
                let load = if j < 4 { f + u0 } else { f + u1 };
                let p = 1.0 / (1.0 + (-2.0 * load).exp());
                if j < 4 {
                    t0 += p;
                }
                row.push(f64::from((next() < p) as u8));
            }
            true_s0.push(t0);
            x.push(row);
        }
        if let Ok(r) = subscores(&x, &[0, 0, 0, 0, 1, 1, 1, 1]) {
            reps += 1;
            for p in 0..n {
                mse_s += (r.subscore_s[p][0] - true_s0[p]).powi(2);
                mse_sx += (r.subscore_sx[p][0] - true_s0[p]).powi(2);
            }
        }
    }
    assert!(reps >= 400, "too few valid replications: {reps}");
    assert!(
        mse_sx <= mse_s * 1.001,
        "augmented MSE {mse_sx} exceeds observed-subscore MSE {mse_s}"
    );
}
