name: ClusterFuzzLite PR fuzzing
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft, closed]
    paths:
      - ".clusterfuzzlite/**"
      - ".github/workflows/cflite_pr.yml"
      - "Cargo.toml"
      - "crates/**"
      - "fuzz/**"

permissions:
  contents: read
  security-events: write

jobs:
  central:
    uses: ContextualWisdomLab/.github/.github/workflows/fast-mlsirm-cflite_pr.yml@deb86d0a96a9478319dd015a902131d698fa79e2
