name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, converted_to_draft, closed]

permissions:
  contents: read

jobs:
  central:
    uses: ContextualWisdomLab/.github/.github/workflows/fast-mlsirm-ci.yml@b97821885a08d9dae556da34b730677d14ee8c97
